### ISSUE TITLE
Typing issue: コロンビア

### ISSUE THREAD

**Issue by CRC32EX** [google/mozc#1001]
## Category of the typing issue
3. Conversion issue

## Issues
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| ころんびあ | Colombia | Columbia|

## Version or commit-id
GoogleJapaneseInput-2.29.5370.0+24.11.9

## Additional context
> コロンビアの国名の正しいつづりは「Colombia」。ところが米ニューヨークにある大学などの名と混同して、「Columbia」と間違えられてしまうことが多い。
https://www.cnn.co.jp/tech/35028544.html

**Comment by hiroyuki-komatsu** [comment]
Hi CRC32EX,

Thank you for your feedback with the reference.
I will update test cases and evaluations based on your report.
