### ISSUE TITLE
Typing issue: 儛草神社

### ISSUE THREAD

**Issue by fu-creator** [google/mozc#1008]
## Category of the typing issue
Choose one of them (delete rest of them)
1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

## Issues
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| もくさじんじゃ | 儛草神社 | 目さ神社 |

## Version or commit-id
Mozc-2.30.5544.102+24.11.oss

## Additional context
岩手県にある神社。読みは法人登記簿による。

> [!NOTE]
>
> Typing issues will be closed when the entries are added to test cases and
> evaluations.
>
> https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
> https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv

**Comment by hiroyuki-komatsu** [comment]
Hi fu-creator,

Thank you for your feedback.
I will update test cases and evaluations based on this and other your reports.
