### ISSUE TITLE
誤変換: スーツのBTNを翔け違っている

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#103]
```
Mozc-1.2.809.102
すーつのぼたんをかけちがっている =>
スーツのBTNを翔け違っている
「ボタンを掛け違っている」

非常に目立つ例なので独立したIssueとして投稿します。
```

Original issue reported on code.google.com by `heathros...@gmail.com` on 26 Aug 2011 at 9:15

**Comment by hiroyuki-komatsu** [comment]
Added evaluation test cases in this issue.

* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv
