### ISSUE TITLE
Typing issue: 北日本新聞杯

### ISSUE THREAD

**Issue by ghost** [google/mozc#1048]
## Category of the typing issue
Choose one of them (delete rest of them)
1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

## Issues
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| きたにっぽんしんぶんはい | 北日本新聞杯 | 北日本新聞はい |

## Version or commit-id
Mozc-2.30.5544.102+24.11.oss

## Additional context
競馬のレース名。

> [!NOTE]
>
> Typing issues will be closed when the entries are added to test cases and
> evaluations.
>
> https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
> https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv

**Comment by tats-u** [comment]
○○新聞杯は他にも割とあるので「しんぶん」「はい」と来たら「新聞杯」になるように「杯」の優先度を調整するのが汎用性があります
