### ISSUE TITLE
Consider switching to `WiX 5.0.2` from `WiX 4.0.5`

### ISSUE THREAD

**Issue by yukawa** [google/mozc#1070]
## Description
WiX 5.0.2 was released on Oct 4, 2024.

 * https://github.com/wixtoolset/wix/releases/tag/v5.0.2

Unlike WiX 5.0.1, which failed to compile our [`installer_oss_64bit.wxs`](https://github.com/google/mozc/blob/ace314567109cbc30dc336fb27844dacff782dd9/src/win32/installer/installer_oss_64bit.wxs), WiX 5.0.2 looks to have no issue on building it without any modification.

## Steps to reproduce
1. Replace `4.0.5` with `5.0.2` in the following files.
  * https://github.com/google/mozc/blob/ace314567109cbc30dc336fb27844dacff782dd9/dotnet-tools.json#L1-L12
  * https://github.com/google/mozc/blob/ace314567109cbc30dc336fb27844dacff782dd9/src/MODULE.bazel#L165-L168
  * https://github.com/google/mozc/blob/ace314567109cbc30dc336fb27844dacff782dd9/src/WORKSPACE.bazel#L225-L230
2. Build Mozc (with either GYP or Bazel)

## Expected behavior
There is no difference in `Mozc64.msi` built.

## Actual behavior
There is no difference in `Mozc64.msi` built.

## Version or commit-id
ace314567109cbc30dc336fb27844dacff782dd9

## Environment
 - OS: Windows 11 23H2

**Comment by yukawa** [comment]
@hiroyuki-komatsu Can you take a look at this when you have time?  I guess all we need to do is just replacing `4.0.5` with `5.0.2` in the above 3 files.

**Comment by hiroyuki-komatsu** [comment]
Sure!

**Comment by hiroyuki-komatsu** [comment]
Done.
