### ISSUE TITLE
`installer_64bit.wxs` needs to specify `Bitness="always32"` for Omaha-related registry keys

### ISSUE THREAD

**Issue by yukawa** [google/mozc#1072]
## Description
When Mozc is built with `BRANDING=GoogleJapaneseInput`, `GoogleJapaneseInput64.msi` should create several registry values for [Omaha](https://github.com/google/omaha).

 * `HKLM\Software\WOW6432Node\Google\Update\Clients\{DDCCD2A9-025E-4142-BCEB-F467B88CF830}`
 * `HKLM\Software\WOW6432Node\Google\Update\ClientState\{DDCCD2A9-025E-4142-BCEB-F467B88CF830}`

These values need to be under `WOW6432Node` because Omaha is still a 32-bit app.

https://github.com/google/omaha/blob/b9a47da58af12d5d51b78846909668499f37b8af/doc/Omaha3Walkthrough.md
> * Machine Omaha: Omaha is installed in a machine-wide manner. The files live in the machine’s app directory -- for example, `\Program Files (x86)\Google\Update` -- and all relevant Registry keys are stored in `HKLM\Software\Google\Update` (for 32-bit) or `HKLM\Software\Wow6432Node\Google\Update` (for 64-bit).

In recent versions, however, `GoogleJapaneseInput64.msi` writes these values into the following locations, which are most likely not recognized by Omaha.

 * `HKLM\Software\Google\Update\Clients\{DDCCD2A9-025E-4142-BCEB-F467B88CF830}`
 * `HKLM\Software\Google\Update\ClientState\{DDCCD2A9-025E-4142-BCEB-F467B88CF830}`

This might be a regression when we migrated from WiX v3 to v4 (cbd55566caaf321009b1254bbf45588eeac38e10).

 * https://github.com/google/mozc/issues/894

## Steps to reproduce
1. Install Google Japanese Input 2.30.5590.0 dev version from https://tools.google.com/dlpage/japaneseinput/eula.html?hl=ja&extra=dev
2. `reg query HKLM\Software\Google\Update\Clients\{DDCCD2A9-025E-4142-BCEB-F467B88CF830} /s /reg:32`

## Expected behavior
* Post install dialog is shown after the initial installation after the step 1
* Registry entries are shown at the step 2.

## Actual behavior
* Post install dialog is not shown after the initial installation after the step 1
* Registry entries are shown at the step 2.

## Version or commit-id
2e19e74cf0c9e341e94616cb78e1f0e974f380a0

## Environment
 - OS: Windows 11 23H2

## Additional context
 * `Mozc64.msi` built with `BRANDING=Mozc` is not affected as it does not depend on [Omaha](https://github.com/google/omaha).
 * `GoogleJapaneseInput64-2.30.5590.0.msi` is affected by this issue.
 * `GoogleJapaneseInput64-2.29.5370.0.msi` is not affected by this issue yet.
 * This is unlikely to be the root cause of the hung-up issue in `SearchHost.exe`.

## Proposed fix
A straightforward fix would be specifying `Bitness="always32"` to `<Component>` elements.

https://github.com/google/mozc/blob/2e19e74cf0c9e341e94616cb78e1f0e974f380a0/src/win32/installer/installer_64bit.wxs#L329-L339

https://github.com/google/mozc/blob/2e19e74cf0c9e341e94616cb78e1f0e974f380a0/src/win32/installer/installer_64bit.wxs#L351-L353

```
    <!-- Write registry keys to make the installer compatible with Omaha. -->
    <Component Id="OmahaRegister" Directory="TARGETDIR" Bitness="always32">
      <RegistryValue Id="OmahaClientRegPv" Root="HKLM" Key="$(var.OmahaClientKey)" Name="pv" Value="$(var.MozcVersion)" Action="write" Type="string" />
      <RegistryValue Id="OmahaClientRegName" Root="HKLM" Key="$(var.OmahaClientKey)" Name="name" Value="Google 日本語入力" Action="write" Type="string" />
      <RegistryValue Id="OmahaClientRegLang" Root="HKLM" Key="$(var.OmahaClientKey)" Name="lang" Value="ja" Action="write" Type="string" />
      <RegistryValue Id="OmahaClientRegOOPCrashes" Root="HKLM" Key="$(var.OmahaClientKey)" Name="oopcrashes" Value="1" Action="write" Type="integer" />
      <!-- enable usagestats for dev channel users -->
      <?if ($(var.OmahaChannelType) = "dev") ?>
        <RegistryValue Id="OmahaUsageStats" Root="HKLM" Key="$(var.OmahaClientStateKey)" Name="usagestats" Value="1" Action="write" Type="integer" />
      <?endif?>
    </Component>
```

```
    <Component Id="OmahaRegLaunchCmdLine" Permanent="no" Directory="TARGETDIR" Condition="(NOT UPGRADING)" Bitness="always32">
      <RegistryValue Id="OmahaLaunchCmdLineValue" Root="HKLM" Key="$(var.OmahaClientStateKey)" Name="InstallerSuccessLaunchCmdLine" Action="write" Type="string" Value="&quot;[GIMEJaDir]GoogleIMEJaTool.exe&quot; --mode=post_install_dialog" />
    </Component>
```

**Comment by yukawa** [comment]
@hiroyuki-komatsu sorry about the trouble, but can you add `Bitness="always32"` to `installer_64bit.wxs` line 330 and line 351 as above?

Regarding existing users, I hope most of users are still receiving updates as `GoogleJapaneseInputSetup.exe` also writes version entry to the following location anyway, but it'd be safer to double check it.

 * `HKLM\Software\WOW6432Node\Google\Update\ClientState\{DDCCD2A9-025E-4142-BCEB-F467B88CF830}`

**Comment by hiroyuki-komatsu** [comment]
Thank you for the report.
Sure, we are reviewing #1073 now.
