### ISSUE TITLE
Migrate to Bazel 8.0

### ISSUE THREAD

**Issue by yukawa** [google/mozc#1118]
## Description
As Bazel 8.0 is expected to be released in late November 2024, it's time for us to start preparing for the transition from Bazel 7.4.x to Bazel 8.0.x.

 * https://github.com/bazelbuild/bazel/issues/23315

## Tasks

 * Pin Bazel version to Bazel 7.4.x until we Mozc becomes fully compatible with Bazel 8.0
   * For GitHub Actions where Bazelisk is actually used, we can rely on `USE_BAZEL_VERSION` to specify the Bazel version.
 * Make sure all the dependent Bazel modules are compatible with Bazel 8.0
   * Update module versions as needed.
 * Make sure Mozc's own build rules are compatible with Bazel 8.0
   * Update Mozc's own build rules as needed.
 * Once Mozc becomes fully compatible with Bazel 8.0, drop Bazel 7.x support.

## Version or commit-id
e1b40ed2714f82552f3e63d50fc714c751779c46

**Comment by wengxt** [comment]
Just FYI that with rules_apple bumped to 3.16.1 (I'm not sure if a minimum working version preferred but I just tried the latest one) & #1144 , I'm able to build a usable server & gui tool & fcitx5 support on linux.
