### ISSUE TITLE
前に文章があると「気にする」の候補が出ない

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#119]
```
バージョン: Mozc-1.3.975.102

1.
「気にする」単独だとすぐ変換できますが、
「そんなことを着にしていても仕方ない」だと
「きにしていても」の候補群の中に
「気にしていても」がありません。

「そんなことをきにするな」の場合でも、
「気にするな」の候補がありません。

頻繁に使う表現なのでとても不便です。

2.
「カラ話したけど」のように助詞から書き継ぐと、
「カラ」がカタカナになります。
K-POPグループの名称が強く出ているのかな。

3.
「そうなった文だけでも」のような「〜ぶん」が
「文」になってしまいます。

4.
「りょうほう」の第一候補が「療法」になっています。
これは「両方」であってほしいです。

5.
他にも使っていて不自然に感じる変換がポロポロ出ます。
「交換情報」が「巷間常法」になったり。
「交換」「情報」単独だとそれぞれ問題なく変換されるの��
�、
余計に奇異に感じます。
```

Original issue reported on code.google.com by `heathros...@gmail.com` on 29 Jan 2012 at 12:36

**Comment by hiroyuki-komatsu** [comment]
Added evaluation test cases in this issue.

* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv
