### ISSUE TITLE
誤変換: 注文時期にもよるケド

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#120]
```
注文時期にもよるケド
「ケド」がカタカナになります。

他の誤変換:
仕上げは明日に使用（しよう）
汗を水槽なので（吸いそう）
日々気が豊かになる（響き）
そういう話ができる次期が来たら（時期）

Mozc-1.3.975.102
シークレットモードを有効にしてテストしました。

ネットでは「こんな単語も変換できる」と
面白がる人が多いようですが、
「日々気」「巷間常法」など従来ではありえない変換も多��
�です。
収集したパターンからちょっとでも外れると、
日常使われない単語でも強引に嵌めて答えを出してくる感��
�です。
```

Original issue reported on code.google.com by `heathros...@gmail.com` on 2 Feb 2012 at 12:52

**Comment by hiroyuki-komatsu** [comment]
Added evaluation test cases in this issue.

* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv
