### ISSUE TITLE
誤変換: 朝礼の阿戸は海技だ

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#122]
```
朝礼の阿戸は海技だ（朝礼の|後は|あとは|会議だ）
3年版の（3年半[3ねんはん]）
5年版の（5年半[5ねんはん]）
支ってに愚痴って（勝手[かって]に愚痴って）
さり際がかっこいい（去り際[さりぎわ]の登録がない？）
支配浴が大きい人だ（支配欲）
翌々考えたら（よくよく）

前後のつながりだけでなく、
単語そのものの出現頻度も考慮に入れて結果を出すように��
�ないと、
「阿戸」とか「海技」とかが
条件次第で上位に出てきてしまいます。
```

Original issue reported on code.google.com by `heathros...@gmail.com` on 3 Feb 2012 at 6:14

**Comment by hiroyuki-komatsu** [comment]
Added evaluation test cases in this issue.

* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv
