### ISSUE TITLE
誤変換: 個の商品を解体

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#125]
```
個の商品を解体（この商品を買いたい）
このテレビを解体（買いたい）
個の商品を買いたいので（この商品を）

Mozc-1.3.975.102
シークレットモード有効
```

Original issue reported on code.google.com by `heathros...@gmail.com` on 12 Feb 2012 at 7:44

**Comment by hiroyuki-komatsu** [comment]
Added evaluation test cases in this issue.

* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv
