### ISSUE TITLE
誤変換: ヒトのヒョウカをきにするな

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#129]
```
ヒトのヒョウカをきにするな（人の評価を気にするな）
Mozc-1.3.975.102

なぜかカタカナになります。
他の例は忘れましたが、
たまに漢字であるべきところが
カタカナになることがありますね。
```

Original issue reported on code.google.com by `heathros...@gmail.com` on 29 Feb 2012 at 9:23

**Comment by hiroyuki-komatsu** [comment]
Added evaluation test cases in this issue.

* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv
