### ISSUE TITLE
Use static linking against protobuf even for Linux version of Mozc 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#14]
```
In related to the previous issue #13, please consider using statically linking 
with protobuf even for the Linux version of Mozc.

I request this because of the design of protobuf not to handle "bundle modules 
linking with protobuf" by dlopen(3) decently (related to issue #128 of 
protobuf).  Specifically for mozc_tool in Linux, which uses Qt4 library as a 
GUI frontend and of course linking with shared protobuf library, it loads 
bundle modules with dlopen(3) when creating a input context.  And as input 
module of uim for Qt do dlopen uim-mozc bundle (which is also linking with 
shared protobuf library dynamically) at that time, it will cause crash of 
protobuf as follows.

    libprotobuf ERROR google/protobuf/descriptor_database.cc:56] File already exists in database: session/config.proto
    libprotobuf FATAL google/protobuf/descriptor.cc:857] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):

I think this can be solved by using mozc_tool with protobuf library linked 
statically.

Cheers,
```

Original issue reported on code.google.com by `ek.k...@gmail.com` on 17 Jun 2010 at 3:44

**Comment by fweimer-rh** [comment]
What is issue 128 of protobuf in this context?

**Comment by yukawa** [comment]
> What is issue 128 of protobuf in this context?

@fweimer-rh At that time, the protobuf OSS project was hosted on [Google Code](https://code.google.com/archive/), which also had its own issue tracker. The issue 128 was the issue number there, not the one in the GitHub. Note also that the Mozc project was also hosted on Google Code at that time.

To access the original issue 128 which is already archived, run the following command for example. See also https://code.google.com/archive/schema.

```sh
curl -s https://storage.googleapis.com/google-code-archive/v2/code.google.com/protobuf/issues/issue-128.json | jq .
```

I guess the original reporter was referring to the following message, which was from the Protobuf maintainer at that time if I remember correctly.
```
The design of the protobuf library is currently such that if you unload a dynamic
library containing a protobuf class, you *must* simultaneously unload the copy of
libprotobuf that it is linked against.  Therefore, if you are writing a dynamic
library which may be loaded and unloaded at runtime, you should probably statically
link it against protocol buffers.

Alternatively, if you use:
  option optimize_for = LITE_RUNTIME;
and you do not use extensions, then I believe this will produce code that does not
use any global registries and thus does not have these problems.
```

**Comment by fweimer-rh** [comment]
@yukawa If that's the only concern, it would be possible to prevent object unloading by setting the `NODELETE` flag. Obviously, it interferes with dynamic code replacement, but it prevents the protobuf library from crashing due to stale references to something that has been unloaded by `dlclose`.

**Comment by yukawa** [comment]
@fweimer-rh, thank you for the info, but the original thread was more than 15 years ago anyway, and many things have been changed since then. Right now in this repository statically linking to protobuf (and abseil) is the only supported build configuration not only in Linux but also in other target platforms such as Windows, macOS, and Android. Currently there is no plan to support dynamic linking to protobuf (and abseil) as an officially supported build configuration.

See also my commend below.

 * https://github.com/google/mozc/issues/509#issuecomment-1704654739

If you have something to discuss further, feel free to open a new thread in our [Discussion forum](https://github.com/google/mozc/discussions).
