### ISSUE TITLE
誤変換: 田子浦

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#141]
```
たごうら
誤: 他強羅
正: 田子浦

Mozc-1.4.1003.102
```

Original issue reported on code.google.com by `sekinemi...@gmail.com` on 20 Mar 2012 at 3:05

**Comment by hiroyuki-komatsu** [comment]
Added evaluation test cases in this issue.

* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv
