### ISSUE TITLE
誤変換: 1爪の話は（1つ目の、1つめの）

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#155]
```
tweetで出ていた誤変換:
1爪の話は（1つ目の、1つめの）
9爪の話は（9つ目の、9つめの）

その他:
えいえい辞典　（「英英」が収録されていない）
％に換算すると（「ぱーせんと」の第一候補が「パーセン��
�」にならない）
「％」が欲しいときは Shift+5 で一発入力すると思います

Mozc-1.4.1033.102

```

Original issue reported on code.google.com by `heathros...@gmail.com` on 18 Apr 2012 at 2:18

**Comment by hiroyuki-komatsu** [comment]
26409dd and c67b4c91b3f10098803c3990620e428ebf8b0ebe added the words and the test cases.
We close issues tracked by the test cases regardless the conversion result.
