### ISSUE TITLE
誤変換：見に覚えのない

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#192]
```
「みにおぼえのない」
で変換すると、
「見に覚えのない」
となってしまいます。

「身に覚えのない」が正しいと思うのですが

Mozc 1.6.1187.2

```

Original issue reported on code.google.com by `tanaka.h...@gmail.com` on 19 Jun 2013 at 5:11

**Comment by tomatojuicengc5195** [comment]
私も同様の問題に遭遇しています。

**Comment by hiroyuki-komatsu** [comment]
c539217f59b5e36b6fd67ff6e185ecb18a7ff8fd and f6d294e316303f0f728533a3cee87f7b8eae8c19 added the word and the test case.
