### ISSUE TITLE
A Chinese variant?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#209]
```
It may be rediculous, but is it possible to create a mozc-powered Chinese input 
method? All these existing Chinese IMs are filled with bugs, or advertisements.
```

Original issue reported on code.google.com by `typeof....@gmail.com` on 28 Feb 2014 at 2:45

**Comment by yukawa** [comment]
Thank you for the feedback.  Actually we used to use Mozc to support Chinese input for Chromium OS, which was already deprecated.  So far we do not have any new plan to do that.

**Comment by buaabyl** [comment]
I am interesting in the reason for deprecated. I like Google PinYin Input for windows, but seems that Google have no plan maintain it any more (stopped at version 2.7.128). And that input method without linux porting...

**Comment by edwardchanjw** [comment]
Hi, I knew this topic is old. Does Google willing to archive/open source the Chinese variant. I am betting it will still be top 3 or even top 1 in Chinese Language in free / OSS category.
