### ISSUE TITLE
Typos in the member function to create existence filters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#214]
```
This is a very minor issue. It looks like there are typos in the static member 
function on ExistenceFilter class for creating an immutable existence filter. 
The name is "CreateImmutableExietenceFilter", but I think it should be 
"CreateImmutableExistenceFilter".

Attached patch fixes the typos.

What version of the product are you using? On what operating system?
r191

```

Original issue reported on code.google.com by `tetsuo.s...@gmail.com` on 4 May 2014 at 7:25

Attachments:
- [existence_filter.patch](https://storage.googleapis.com/google-code-attachments/mozc/issue-214/comment-0/existence_filter.patch)

**Comment by hiroyuki-komatsu** [comment]
CreateImmutableExistenceFilter is no longer necessary.
So d381608 removed this function.

Thank you,
