### ISSUE TITLE
Mozc-0.13.464.102: Wrong conversion

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#25]
```
時間に負われている　追われて
禁じ手　(候補なし)
女子高生　(候補なし)
ダックスフントはたん速です　短足、せめて嘆息
終を迎えた 「おわり」で「終わり」にならない
カネノナルキだ　金のなる木
笑点　(候補なし)
別途シーツを交換した　ベッドシーツ。「ベッド」の優先��
�が低い
岩瀬月　言わせるな。「そんなことを言わせるな」はOK。
ナラには　「奈良」の候補なし
介護完成　下位互換性。「下位」がなかなか出ない。
「上位互換性」はすぐ出る

> ナラには　「奈良」の候補なし
I think the new Mozc dictionary has a critical bug.

```

Original issue reported on code.google.com by `heathros...@gmail.com` on 15 Sep 2010 at 6:19

**Comment by hiroyuki-komatsu** [comment]
I added conversion test cases and the results based on reports in this issue.

https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv

We track the status of conversion results.
