### ISSUE TITLE
Preedit and candidate changes buffer modification flag.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#254]
```
What steps will reproduce the problem?
1. setup mozc.el under emacs.
2. activate mozc, and input something in preedit on unmodified buffer.
3. push ESC for clear preedit string.

What is the expected output?
The buffer modification flag isn't changed. (keep unmodified)

What do you see instead?
The buffer modification flag is turned on.

What version of the product are you using? On what operating system?
2.16.1924.102

Please provide any additional information below.
A propose patch is attached.
```

Original issue reported on code.google.com by `d588...@gmail.com` on 24 Nov 2014 at 11:14

Attachments:
* [mozc-el-diff](https://storage.googleapis.com/google-code-attachments/mozc/issue-254/comment-0/mozc-el-diff)

**Comment by yukawa** [comment]
Thank you for the report.  d7b6196aeac52dd908ca051ba65e97b389f4503a should addressed this issue.

As for the patch, we do not accept any patch from external contributor as explained in [CONTRIBUTING.md](https://github.com/google/mozc/blob/master/CONTRIBUTING.md).  We appreciate for your understanding.
