### ISSUE TITLE
歴とした

### ISSUE THREAD

**Issue by Shudouken** [google/mozc#308]
This reads れっきとした, but can't be produced when typing this
It can only be done when typing れきとした

**Comment by hiroyuki-komatsu** [comment]
Thank you for your feedback.

We added a test case for this conversion:
* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv#L86

The results of the test case is here:
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv#L86
