### ISSUE TITLE
Switch to Qt5 from Qt4

### ISSUE THREAD

**Issue by yukawa** [google/mozc#327]
Currently `mozc_tool` uses Qt4, which is no longer actively developed.  It is still usable, but things like HiDPI supports and newer compiler supports are only available in Qt5.  We should switch to Qt5.

Remaining tasks are:
- [x] Switch to Qt5 in Windows builds.
- [x] Switch to Qt5 in OS X builds.
- [x] Switch to Qt5 in Linux desktop builds.

**Comment by yukawa** [comment]
We have make all the planned changes. Qt 5 is ready to be tested on Windows, macOS, and Linux. Any other issue that is reproducible only with Qt 5 should be handled as a separate bug.

**Comment by DanielJoyce** [comment]
Hidpi still broken

**Comment by ftake** [comment]
Mozc should take an appropriate way to design GUI (Qt Creator etc.)
