### ISSUE TITLE
com.google.android.inputmethod.japanese use out pthread mmap space

### ISSUE THREAD

**Issue by besthust** [google/mozc#340]
When I do some monkey test, we found that com.google.android.inputmethod.japanese will some times tombstone which caused by mmap space use out. and print out a lot of message as below:
01-01 15:13:34.665   366   382 W libc    : pthread_create failed: couldn't allocate 1044480-bytes mapped space: Out of memory.
after check the behavior, we found that when do input text, repeat hide the input method bar, show the input method bar, we found the /proc/pidof(inputmethod)/maps will increase some anonymous mapping, with size 0x1000+0xfe000, which should be thread_create mapping space. After trace more about the thread create, we found, during show the input method bar, a thread named "Session worker“ will always create thread twice, but with the same thread id, and without any free operation. 
We haven't found such behavior for AOSP input method, and also I found there is a fix about resource leak before in BUG=Issue mozc:265, is it possible still potential thread space leak pending?

**Comment by yukawa** [comment]
Thank you for the report.  Can you give me following additional information?
 * Version of ```com.google.android.inputmethod.japanese``` and Android OS.you used.
 * Device name you used.
 * Whether the issue is reproducible with the latest Mozc built from the source code. As explained in [About Mozc](https://github.com/google/mozc/blob/master/doc/about_branding.md), ```com.google.android.inputmethod.japanese``` and OSS Mozc are basically different products.  Hence it would make more sense if you can confirm the issue is reproducible with OSS Mozc.

**Comment by besthust** [comment]
The version of com.google.android.inputmethod.japanese is 2.17.2101.3-x86
Android version is Android 6.0
I'm not very sure the device name.
I will have a try to use the latest code.

**Comment by besthust** [comment]
Hi Yukawa,
    After more debug with the thread create track, I found that when touch a text message, which will call input method and show the bar, two thread were created, (named Session worker), searched in the source code, it seems like below code will new a thread.
   
  private static HandlerThread getHandlerThread() {
    Optional<HandlerThread> result = sessionHandlerThread;
    if (!result.isPresent()) {
      synchronized (SessionExecutor.class) {
        result = sessionHandlerThread;
        if (!result.isPresent()) {
          result = Optional.of(new HandlerThread("Session worker thread"));
          result.get().setDaemon(true);
          result.get().start();
          sessionHandlerThread = result;
        }
      }
    }
    return result.get();
  }

**Comment by besthust** [comment]
BTW, I have tried on Nexus 6, with Android 6.0, Mozc version 2.17.2103.3-arm, it also has the same issue.

**Comment by justoneplanet** [comment]
I submit stack traces about this issue.

It seems that the "nativeCreate" method of "Thread.java", which is called from various classes, is failed as you see. 

```text
Caused by: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1063)
（from various classes）
```

And SessionExecutor has a little crashes like following.

```text
java.lang.RuntimeException: java.io.IOException: mmap failed: ENOMEM (Out of memory)
	at org.mozc.android.inputmethod.japanese.session.a.initialize(SourceFile:99)
	at org.mozc.android.inputmethod.japanese.session.g.handleMessage(SourceFile:311)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.io.IOException: mmap failed: ENOMEM (Out of memory)
	at java.nio.MemoryBlock.mmap(MemoryBlock.java:125)
	at java.nio.FileChannelImpl.map(FileChannelImpl.java:257)
	at org.mozc.android.inputmethod.japanese.h.o.xp(SourceFile:204)
	at org.mozc.android.inputmethod.japanese.h.l.a(SourceFile:249)
	at org.mozc.android.inputmethod.japanese.h.l.a(SourceFile:237)
	at org.mozc.android.inputmethod.japanese.session.a.initialize(SourceFile:80)
	... 4 more
Caused by: android.system.ErrnoException: mmap failed: ENOMEM (Out of memory)
	at libcore.io.Posix.mmap(Native Method)
	at libcore.io.ForwardingOs.mmap(ForwardingOs.java:115)
	at java.nio.MemoryBlock.mmap(MemoryBlock.java:122)
	... 9 more
```

SourceFile:99 is in getInstanceInternal method of SessionExecutor.java.

However, I cannot find crashes at getHandlerThread method of SesstionExecutor.java in my PlayStore console.

These crashes are seen on Android 6.0 devices, which are Nexus 5, Nexus 6, Nexus 7 and Nexus 9.
I suspect that the double-checked locking pattern using  the keyword "volatile" on Marshmallow ART does not work correctly.
Based on my hypothesis, I verify my application, removing the pattern now.

**Comment by besthust** [comment]
@justoneplanet , I suspect your stack should be similar issue as mine.
BTW, what do you mean about "I suspect that the double-checked locking pattern using the keyword "volatile" on Marshmallow ART does not work correctly." ?

**Comment by justoneplanet** [comment]
To my regret, my hypothesis was wrong. Removing double-checked locking pattern could not solve this problem. Sorry!

**Comment by matsuza** [comment]
Hi guys,

I cannot reproduce this issue because I guess my reproduction step is incorrect.
Could anyone provide more detailed repro step?

**Comment by besthust** [comment]
@matsuza , I just find a place which can input text(like google search bar, message etc), then touch the space which will be input, the inputmethod bar will be shown, touch some place else, let the input method bar disappear, then repeat above again and again, you will found the memory will be used out soon. If your device is root, you can easily track with "cat /proc/pid/maps", the mapping is increased for each above operation.

**Comment by yukawa** [comment]
Merging into #355.
