### ISSUE TITLE
Build had succeeded but Run failed on Android

### ISSUE THREAD

**Issue by oyayubikun** [google/mozc#366]
On the latest mozc for Android (Ver. 2.23), I succeeded on building the apk file in accordance with the instructions (How to build Mozc in Docker), signing the file, and installing it on an actual Android device.

However, when I tried to run the App, it disappears suddenly. It seems the run had failed.
I tried this on another Android device but had failed again behaving like the same.

I wrote this matter on my blog.
http://happylifelaboratory.blog.fc2.com/blog-entry-138.html

**Comment by oldergod** [comment]
Why not use the official application? https://play.google.com/store/apps/details?id=com.google.android.inputmethod.japanese&hl=ja

**Comment by yukawa** [comment]
Can you try debug build, which doesn't require you to do signing it by yourself?
```
python build_mozc.py build -c Debug android/android.gyp:apk
```

If you tried release build and it doesn't run, I suspect that you forgot to run [zipalign](https://github.com/google/mozc/blob/master/doc/build_mozc_in_docker.md#zipalign), but it's really hard for us to point out what went wrong without clear steps to reproduce the issue and the actual log (e.g. output of ```adb logcat```).  I don't understand what command you did to sign the file, and I don't understand what version of Android you used.  I feel I have to understand what you actually did and what was actually happening in your device to answer to your question.

Thanks,

**Comment by oyayubikun** [comment]
Thank you. I will try it again and write here the result later.

**Comment by yukawa** [comment]
Just FYI, I've built Mozc for Android (2.17.2322.102) as follows and verified that it works fine on Nexus 6P (MHC19Q Android 6.0.1).

```
python build_mozc.py gyp --target_platform=Android
python build_mozc.py build -c Release android/android.gyp:apk

keytool -genkey -v -keystore ~/.android/debug.keystore -alias mozc_key -keyalg RSA -keysize 2048 -validity 10000

cp android/bin/MozcForAndroid-release-unsigned.apk MozcForAndroid-release-signed-unaligned.apk

jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ~/.android/debug.keystore /home/mozc_builder/work/mozc/src/android/bin/MozcForAndroid-release-unsigned.apk mozc_key

../../android-sdk-linux/build-tools/22.0.0/zipalign -v 4 MozcForAndroid-release-signed-unaligned.apk MozcForAndroid-release-signed.apk
```

**Comment by oyayubikun** [comment]
Yukawa-san,
Thank you for your detailed explanation and commands. I succeeded on running the apk that was debug built. This is sufficient for my purpose for now. So far, I have not succeeded on running the signed version but I think it's because of my lack of skills in signing an apk file.

**Comment by yukawa** [comment]
Thank you for testing that.  Closing.
