### ISSUE TITLE
HUAWEI P9 lite does not show MozcView.

### ISSUE THREAD

**Issue by justoneplanet** [google/mozc#384]
### Devices

- HUAWEI P9 lite: HUAWEI VNS-L22

### What steps will reproduce the problem?

1. Start typing on the any text fields.

### What is the expected output?

MozcView will be shown.

### What do you see instead?

Nothing will be shown.

### What version of the product are you using? On what operating system?

Android 6.0
mozc 1.15.1917.103

### Please provide any additional information below.

The following lines will fix this problem.

```java
-    super(base.getAssets(), null, null);
+    super(base.getAssets(), base.getDisplayMetrics(), base.getConfiguration());
```

like following...

- https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v7/appcompat/src/android/support/v7/widget/ResourcesWrapper.java#46

On the HwResources class of HUAWEI VNS-L22, density property of DisplayMetrics, which is set on the constructor, will be accessed. It seems that causes NullPointerException.

**Comment by yukawa** [comment]
Thank you for the report!

Looks like you are talking about [src/android/src/com/google/android/inputmethod/japanese/util/ResourcesWrapper.java ](https://github.com/google/mozc/blob/d44d0644bf6d73d1d32e55115e2463526a1427c0/src/android/src/com/google/android/inputmethod/japanese/util/ResourcesWrapper.java), right?

If so seem that we can simply use ```android.support.v7.widget.ResourcesWrapper``` rather than keeping maintaining our own version of ```ResourcesWrapper```.

**Comment by justoneplanet** [comment]
> Looks like you are talking about src/android/src/com/google/android/inputmethod/japanese/util/ResourcesWrapper.java , right?

Yes!

> If so seem that we can simply use android.support.v7.widget.ResourcesWrapper
> rather than keeping maintaining our own version of ResourcesWrapper.

I think so, but this class in the support library is not public.😢

**Comment by yukawa** [comment]
>> If so seem that we can simply use android.support.v7.widget.ResourcesWrapper rather than keeping maintaining our own version of ResourcesWrapper.
> I think so, but this class in the support library is not public.:cry:

Ah, I see. Then fixing ```org.mozc.android.inputmethod.japanese.util.ResourcesWrapper``` makes sense. Will update this thread when it is done.

Thanks!
