### ISSUE TITLE
Can't build mozc on win10

### ISSUE THREAD

**Issue by oiale** [google/mozc#393]
Hello, I seem to have a problem with building mozc on win10 x64.
Output:

```INFO: Running: ninja.exe -C out_win/ReleaseDynamic mozc_win32_build32_dynamic
ninja: Entering directory `out_win/ReleaseDynamic'
[143/515] ACTION Generating Resource file from word_register_dialog.qrc
FAILED: gen/gui/word_register_dialog/qrc_word_register_dialog.cc
C:\Tools\Python27\python.exe gyp-win-tool action-wrapper environment.x86 gen_word_register_dialog_files_target_qrc_cba037c509fb4dd901efc523670f516d..rsp ..\..\gui
The system cannot find the path specified.
[148/515] CXX obj\third_party\zinnia\zinnia\zinnia.feature.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "build_mozc.py", line 1242, in <module>
    main()
  File "build_mozc.py", line 1229, in main
    BuildMain(cmd_opts, cmd_args)
  File "build_mozc.py", line 857, in BuildMain
    BuildOnWindows(targets)
  File "build_mozc.py", line 842, in BuildOnWindows
    RunOrDie([ninja, '-C', build_arg, target_name])
  File "c:\Temp\mozc\src\build_tools\util.py", line 99, in RunOrDie
    '==========']))
build_tools.util.RunOrDieError:
==========
 ERROR: ninja.exe -C out_win/ReleaseDynamic mozc_win32_build32_dynamic
```

I couldn't find the place in the script where I could insert something to get some more info on the file that is missing. Could you please help me with that?

Additional info.
I generated the gyp files with --qtver=5 --qtdir=C:\Qt\Qt5.7.0
Build options only had -c Release package and nothing else

**Comment by yukawa** [comment]
I suspect that it's because `--qtdir=` you specified is not correct.  Can you try the following directory?  In my local Windows 10 environment (Windows 10 Pro Insider Preview Build 14965.rs_prerelease.161104-1700) the build suceeds without any error.

```
python build_mozc.py gyp --qtver=5 --qtdir=c:\Qt\Qt5.7.0\5.7\msvc2015
```

**Comment by oiale** [comment]
Thank you very much. I had to install the 32 bit version of Qt and link it as you showed. Also, I think you should update the instructions for building mozc on windows.
It would be great if users could specify what version to build (32/64) with linkage of 32/64 Qt.
