### ISSUE TITLE
Preference dialogue is broken in a high-DPI system.

### ISSUE THREAD

**Issue by HubKing** [google/mozc#394]
I am using XFCE with a high-DPI setting. The preference dialogue looks like this.

http://imgur.com/a/APIB5

The window buttons and contents are clipped out, and I cannot resize the dialogue.

**Comment by yukawa** [comment]
If you are using Qt 5.6 or later [1], I guess the following environment variable needs to be set before Mozc's config dialog is launched, but what is the correct way to fix it really depends on what version of Qt is used in your environment.
```
export QT_AUTO_SCREEN_SCALE_FACTOR=1
```

My suggestion would be to consult with someone who is maintaining Qt 5 in your Linux distribution, or to ask this issue in some user forums where your can find someone who is familiar with Hi DPI support in Qt applications in your Linux distribution.

 [1]:  [High-DPI Support in Qt 5.6](https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/)

**Comment by yukawa** [comment]
Please let us know if you can still reproduce this issue even with building Mozc with Qt 5.6 or later and `QT_AUTO_SCREEN_SCALE_FACTOR=1` is specified.
