### ISSUE TITLE
building error:  unknown target 'ibus_mozc'

### ISSUE THREAD

**Issue by lv7777** [google/mozc#401]
when i build mozc, this error occurred.

```
root@evil:/home/a/mozc/src# python build_mozc.py build -c Release unix/ibus/ibus.gyp:ibus_mozc unix/emacs/emacs.gyp:mozc_emacs_helper server/server.gyp:mozc_server gui/gui.gyp:mozc_tool renderer/renderer.gyp:mozc_renderer
INFO: Running: ninja -C out_linux/Release ibus_mozc mozc_emacs_helper mozc_server mozc_tool mozc_renderer
ninja: Entering directory `out_linux/Release'
ninja: error: unknown target 'ibus_mozc'
Traceback (most recent call last):
  File "build_mozc.py", line 1239, in <module>
    main()
  File "build_mozc.py", line 1226, in main
    BuildMain(cmd_opts, cmd_args)
  File "build_mozc.py", line 857, in BuildMain
    BuildWithNinja(options, targets)
  File "build_mozc.py", line 831, in BuildWithNinja
    RunOrDie([ninja, '-C', build_arg] + ninja_targets)
  File "/home/a/mozc/src/build_tools/util.py", line 99, in RunOrDie
    '==========']))
build_tools.util.RunOrDieError: 
==========
 ERROR: ninja -C out_linux/Release ibus_mozc mozc_emacs_helper mozc_server mozc_tool mozc_renderer
==========


```

but...I trying without `unix/ibus/ibus.gyp:ibus_mozc`, the build was success.

**Comment by yukawa** [comment]
The build target in question `unix/ibus/ibus.gyp:ibus_mozc` is available when and only when 1) the host environment is Linux and 2) `pkg-config --exists ibus-1.0 >= 1.4.1` command succeeds.

[src/build_mozc.py line 170-175](https://github.com/google/mozc/blob/4767ce2f2b6a63f1f139daea6e98bc7a564d5e4e/src/build_mozc.py#L170-L175)

```py
  elif options.target_platform == 'Linux':
    gyp_file_names.extend(glob.glob('%s/unix/*/*.gyp' % SRC_DIR))
    # Add ibus.gyp if ibus version is >=1.4.1.
    if not PkgExists('ibus-1.0 >= 1.4.1'):
      logging.info('removing ibus.gyp.')
      gyp_file_names.remove('%s/unix/ibus/ibus.gyp' % SRC_DIR)
```

I don't know on what OS you are trying to build Mozc, but for example on Ubuntu 14.04 you need to install `libibus-1.0-dev` package to build `ibus-mozc`.

I've confirmed that as of commit [4767ce2f](https://github.com/google/mozc/tree/4767ce2f2b6a63f1f139daea6e98bc7a564d5e4e) following commands succeed without any error in the corresponding [Docker container](https://github.com/google/mozc/blob/4767ce2f2b6a63f1f139daea6e98bc7a564d5e4e/docker/ubuntu14.04/Dockerfile).

```
git checkout 4767ce2f2b6a63f1f139daea6e98bc7a564d5e4e
git submodule update --init --recursive
python build_mozc.py gyp
python build_mozc.py build -c Release unix/ibus/ibus.gyp:ibus_mozc unix/emacs/emacs.gyp:mozc_emacs_helper server/server.gyp:mozc_server gui/gui.gyp:mozc_tool renderer/renderer.gyp:mozc_renderer

```

**Comment by lv7777** [comment]
thanks.

my environment is leastest kali linux.
and my environment is not responded `pkg-config --exists ibus-1.0 >= 1.4.1`
this behave is not changed when i install `libibus-1.0-dev`

```
root@evil:~# dpkg -l | grep ibus
ii  gir1.2-ibus-1.0:amd64                  1.5.14-1                             amd64        Intelligent Input Bus - introspection data
ii  ibus                                   1.5.14-1                             amd64        Intelligent Input Bus - core
ii  ibus-mozc                              2.18.2595.102+dfsg-1+b1              amd64        Mozc engine for IBus - Client of the Mozc input method
ii  libgusb2:amd64                         0.2.9-1                              amd64        GLib wrapper around libusb1
ii  libibus-1.0-5:amd64                    1.5.14-1                             amd64        Intelligent Input Bus - shared library
ii  libusb-0.1-4:amd64                     2:0.1.12-30                          amd64        userspace USB programming library
ii  libusb-1.0-0:amd64                     2:1.0.20-1                           amd64        userspace USB programming library
ii  libusbmuxd4:amd64                      1.0.10-3                             amd64        USB multiplexor daemon for iPhone and iPod Touch devices - library

root@evil:/home/a/mozc/src# pkg-config --list-all | grep ibus
ibus-1.0                       IBus - IBus Library
root@evil:/home/a/mozc/src# pkg-config --exists ibus-1.0 >= 1.4.1
root@evil:/home/a/mozc/src# pkg-config --exists ibus-1.0 <= 1.4.1
```
I try build with above state, build is not success in the same way as earlier.

**Comment by yukawa** [comment]
> ```
> root@evil:/home/a/mozc/src# pkg-config --exists ibus-1.0 >= 1.4.1
> root@evil:/home/a/mozc/src# pkg-config --exists ibus-1.0 <= 1.4.1
> ```

Oops, I should have checked that command locally. Can you try the following command instead?

```
pkg-config --exists "ibus-1.0 >= 1.4.1"; echo $?
```

If it shows `0`, then that's fine. If it shows some non-zero value, then that's the direct reason you cannot build `unix/ibus/ibus.gyp:ibus_mozc`.

**Comment by lv7777** [comment]
first, I tried the command, but I can't build, in spite of `$?` is displayed 0

```
a@evil:~/mozc/src$ pkg-config --exists "ibus-1.0 >= 1.4.1"
a@evil:~/mozc/src$ echo $?
0
a@evil:~/mozc/src$ sudo python build_mozc.py build -c Release unix/ibus/ibus.gyp:ibus_mozc unix/emacs/emacs.gyp:mozc_emacs_helper server/server.gyp:mozc_server gui/gui.gyp:mozc_tool renderer/renderer.gyp:mozc_renderer
INFO: Running: ninja -C out_linux/Release ibus_mozc mozc_emacs_helper mozc_server mozc_tool mozc_renderer
ninja: Entering directory `out_linux/Release'
ninja: error: unknown target 'ibus_mozc'
Traceback (most recent call last):
  File "build_mozc.py", line 1239, in <module>
    main()
  File "build_mozc.py", line 1226, in main
    BuildMain(cmd_opts, cmd_args)
  File "build_mozc.py", line 857, in BuildMain
    BuildWithNinja(options, targets)
  File "build_mozc.py", line 831, in BuildWithNinja
    RunOrDie([ninja, '-C', build_arg] + ninja_targets)
  File "/home/a/mozc/src/build_tools/util.py", line 99, in RunOrDie
    '==========']))
build_tools.util.RunOrDieError: 
==========
 ERROR: ninja -C out_linux/Release ibus_mozc mozc_emacs_helper mozc_server mozc_tool mozc_renderer
==========

```

but **I am succeed in build** when 
1. `git checkout 4767ce`
1'. `apt-get purge ibus`,`apt-get install ibus`
2. `python build_mozc.py clean`,
3. ` python build_mozc.py gyp --target_platform=Linux`
4. `sudo python build_mozc.py build -c Release unix/ibus/ibus.gyp:ibus_mozc unix/emacs/emacs.gyp:mozc_emacs_helper server/server.gyp:mozc_server gui/gui.gyp:mozc_tool renderer/renderer.gyp:mozc_renderer`

I think the behave is regression bug maybe.
(sorry I have not conviction)

**Comment by yukawa** [comment]
> I think the behave is regression bug maybe.

Hmm, if I understood your reply correctly you could build Mozc revision 4767ce2f2b6a63f1f139daea6e98bc7a564d5e4e (version [`2.20.2677.102`](https://github.com/google/mozc/blob/4767ce2f2b6a63f1f139daea6e98bc7a564d5e4e/src/data/version/mozc_version_template.bzl)), right?  If so it basically means that you succeeded to build Mozc version `2.20.2677.102`, which is the latest version as of writing. What is the problem then?

**Comment by lv7777** [comment]
sorry for late reply.
if revision 4767ce2 is leastest (when issued this problem) , that is no ploblem.
thank you.
