### ISSUE TITLE
Is there any way to create a custom scheme?

### ISSUE THREAD

**Issue by tomasgodoi** [google/mozc#402]
Is there any way to create a custom scheme with this IME like documented at https://www.google.com/inputtools/windows/canonical.html?

I specifically would like to integrate Cangjie codes so I can input Japanese Kana and at the same time use Cangjie to input Kanji.

I know there's the Romaji table that maybe can help me with this but I want to know if there's another option like the cited above. With Romaji table I cannot have the same code associated with more than one Kanji, which can happen in Cangjie.

**Comment by yukawa** [comment]
> Is there any way to create a custom scheme with this IME like documented at
> https://www.google.com/inputtools/windows/canonical.html?

Unfortunately, no.

Sorry for not being able to support such use cases. In order to keep Mozc code as simple and maintainable as possible, it's highly unlikely that we would port and/or implement that feature into Mozc in future.
