### ISSUE TITLE
[IBUS] Ship a usable keymap for IBM 104 keyboard

### ISSUE THREAD

**Issue by mozbugbox** [google/mozc#403]
All the `keymap styles` shipped with ibus-mozc map input mode switching actions to some kind of japanese specific keys on a _japanese_ keyboard. 

This 'feature' forces every user who use a standard IBM 104 keyboard to make her own customized keymap, like mapping ctrl-` to switching on hiragana mode. 

ibus-mozc should ship a `MS-IME(104)` keymap style which has all the functionality of the `MS-IME` keymap but using standard keys of a 104 keyboard _only_.

**Comment by hiroyuki-komatsu** [comment]
The recent commits (e.g. 467a91c) let you customize keyboard configurations.

Sample configures:
https://github.com/google/mozc/issues/201#issuecomment-803289142
