### ISSUE TITLE
Android build showing green "build passing" graphic, but logs show "BUILD FAILED"

### ISSUE THREAD

**Issue by frostybeard** [google/mozc#410]
I am also trying to build it on a local machine, and getting the same result, with a nearly identical build log.
[buildlog.txt](https://github.com/google/mozc/files/726641/buildlog.txt)

**Comment by frostybeard** [comment]
I built locally on a 14.04 Ubuntu machine with all the packages from the Docker file installed and all the environment variables set up accordingly.  
This also appears to be a duplicate with:
https://github.com/google/mozc/issues/406

**Comment by xieunext** [comment]
I have the same build errors. any update about it?

**Comment by boris-arzur** [comment]
I had the same issue.

It's related to the absence of android-support-v13.jar in ~/work/mozc/src/android/libs .

I saw this http://blog.bitrise.io/2016/12/13/android-extra-android-support-no-longer-available.html
They suggest replacing some sdk packages with others, but you still need to build the jar from sources you obtain this way. The canonical way to do so seems to be via build.gradle, but I think this project uses gyp instead? I'm not really familiar with all this.

I solved it by using android-support-v13.jar from https://chromium.googlesource.com/android_tools

host$ sudo docker run -ti -v $(pwd):/data $USER/mozc_ubuntu14.04
# note that I map ~/ubuntu-14.04 to /data, for convenience
mozc_builder@00docker000:~/work/mozc/src$ python build_mozc.py gyp --target_platform=Android
~/work/mozc/src$ python build_mozc.py build -c Debug android/android.gyp:apk
# fails
~/work/mozc/src$ ls android/libs/
# no android-support-v13.jar
~/work/mozc/src$ pushd ~
~$ git clone https://chromium.googlesource.com/android_tools --single-branch --depth=1
# quite wasteful, but I could not get git-archive to work...
# http://stackoverflow.com/questions/2466735/how-to-checkout-only-one-file-from-git-repository
~$ popd
~/work/mozc/src$ cp android_tools/sdk/extras/android/support/v13/android-support-v13.jar android/libs/
~/work/mozc/src$ python build_mozc.py build -c Debug android/android.gyp:apk
 # success !
~/work/mozc/src$ cp android/bin/MozcForAndroid-debug.apk /data/
# remember that -v option to docker ...

I don't think this is a satisfactory answer to the build problem at hand, but it works as a workaround...

**Comment by picsi** [comment]
@boris-arzur Could you patch the documentation on your fork with this workaround, so that people can point to it? I think it would help a lot of folks.
