### ISSUE TITLE
Mozc removes consonants before generating the kana output.

### ISSUE THREAD

**Issue by dabura667** [google/mozc#413]
https://bugs.chromium.org/p/chromium/issues/detail?id=681389

The above issue has animated GIFs to show the problem. Someone was able to recreate in the issue above.

The reason I am posting this issue upstream is that the issue has also started appearing in the LINE windows app running through Wine 2.0... Maybe LINE recently switched to use reactJS-native?... but either way it seems like it must be a problem with mozc.

I am using fcitx-mozc 2.17.2116.102+gitfd0f5b34+dfsg-1ubuntu1.1 which seems to be lagging behind this branch... If someone using the most recent version could check if this is still an issue or not, I would appreciate it. fcitx/mozc github has disabled issue creation, so I can not bring it up with them unless I make a fake pull request and just explain the issue there.

> Steps to reproduce the problem:
> 1. Install Linux Mint 18.1 Cinnamon
> 2. in terminal, install Japanese IME with following command:
> $ sudo apt install fcitx-mozc --install-recommends
> 3. Then activate by using:
> $ im-config -n fcitx
> 4. Log out, then log in your Linux user.
> 5. You will notice keyboard icon on system tray.
> 6. Ctrl + Space to enable Japanese input (Orange icon with japanese symbol in it)
> 7. Visit Facebook, and place cursor in any text box, enable Japanese input and type in saigo<spacebar>ni<enter>
> 8. Notice 最後い is shown instead of the actual proper 最後に (the kana is showing "i" instead of "ni")
> 
> retry 7 and 8 using firefox on the same system and notice it will show 最後に properly.
> 
> What is the expected behavior?
> Do not auto-remove consonants after pressing space bar to select a kanji combination.
> 
> What went wrong?
> it looks like the normal HTML input tags are OK, but the special reactJS generated text input for writing something on your feed or writing a comment on someone else's post is broken with Japanese input on Chrome only.

Chrome
![2235c434-37f6-4744-97b8-39d1e9b21a97](https://cloud.githubusercontent.com/assets/6586275/23092980/1e294458-f61a-11e6-86ca-a97b0a857194.gif)

Firefox
![de3dddc1-53e4-44c0-aa80-5e394155b61b](https://cloud.githubusercontent.com/assets/6586275/23092982/28b57464-f61a-11e6-9014-6d0ea1454b91.gif)

**Comment by dabura667** [comment]
Also, I explain how to use with a US keyboard in the explanation but I am using an iBuffalo Japanese keyboard, if that makes a difference, (I doubt it)

**Comment by darksoul42** [comment]
Also hit by this problem, it's extremely annoying.

**Comment by hiroyuki-komatsu** [comment]
Hi, thank you for reporting.

Because this happens on a specific application, we think this is an issue of that application and/or an issue between IMF (i.e. fcitx) and the application. In this case, it could also be an issue of the web application.

Unfortunately, this kind of issue is not controllable from our implementation layer.
