### ISSUE TITLE
Issue with building mozc

### ISSUE THREAD

**Issue by kikiotsuka** [google/mozc#417]
Your build system doesn't respect the following python pep: https://www.python.org/dev/peps/pep-0394/ and therefore I cannot build your software on Arch Linux. Specifically, I get this [error](https://bpaste.net/show/0bf5c533a2d3)

Please fix your build system to reference the version of python it uses, rather than depending on whichever version of python happens to be the default on the current system

**Comment by yukawa** [comment]
Sorry, 1195cf739ba9575156f127d2a00a2ff8f002e8a7 was unrelated.

**Comment by hiroyuki-komatsu** [comment]
Please let us close this issue as obsolete.

Note, as of 2021 May, we only support Python3 since Python2 has been deprecated.
