### ISSUE TITLE
re.sub() with misplaced flags

### ISSUE THREAD

**Issue by jwilk** [google/mozc#419]
`src/dictionary/gen_zip_code_seed.py` contains the following code:
```python
  level3 = re.sub(u'（.*）', u'', level3, re.U)
```
But the 4th argument to `re.sub()` is supposed to be maximum number of substitutions, not flags.

NB, the `re.U` flag affects only semantics of `\w`, `\W`, `\b`, `\B`, `\d`, `\D`, `\s` and `\S`, so it wouldn't have any effect on this regular expression.

This bug was found using [pydiatra](https://github.com/jwilk/pydiatra).

**Comment by hiroyuki-komatsu** [comment]
Thank you for the report.

473a26c fixed this issue. Fortunately, the practical output is not changed.
