### ISSUE TITLE
emacs mozc.el: unmatch choice values and default value type.

### ISSUE THREAD

**Issue by nilninull** [google/mozc#421]
The values of customization are quoted twice.

I've wrote a small patch, but pull requests were not allowed.

https://github.com/nilninull/mozc/commit/ac1eff654eeb426b4794cd0aa34994ade628115b?diff=split

**Comment by hiroyuki-komatsu** [comment]
Thank you for the report.

https://github.com/google/mozc/commit/b8dc3b676c0443853bf55c3ab5b73db54132441d fixed this issue.
