### ISSUE TITLE
mozc_renderer should be automatically disabled on wayland session

### ISSUE THREAD

**Issue by yukawa** [google/mozc#431]
## Environment

- Fedora 27
- Mozc 2.23.2783.102 (39fbd0e97fb106a7dbc9ac81670719cd21c64677)

## Steps to reproduce

1. Build and Install Mozc into Fedora 27
2. Open gedit
3. Type something

## Expected behavior
`ibus_mozc` falls back to IBus's default candidate window.
![Expected behavior](https://user-images.githubusercontent.com/5861397/34466031-be7c8fc8-ee7b-11e7-8151-75d44147a5c7.png)

## Actual behavior
`ibus_mozc` uses `mozc_renderer`, which does not work well on a wayland session.
![Actual behavior](https://user-images.githubusercontent.com/5861397/34466034-d2161b12-ee7b-11e7-8389-24859de49250.png)

**Comment by Lilalas** [comment]
I have the same issue on Ubuntu 18.04 using Wayland. The version of `ibus-mozc` Ubuntu currently distributes is `2.20.2673.102+dfsg-2`.

@yukawa Is the fix not included in this version yet?

**Comment by ammgws** [comment]
@Lilalas Did you get anywhere with this?

On Arch Linux with `ibus-mozc 2.23.2815.102-3` and `XDG_SESSION_TYPE` set to wayland, I do not even get the "default candidate window" shown in the first screenshot but can still toggle through iterations. With XDG_SESSION_TYPE set to tty I get the mozc_renderer fallback, but this one actually shows the pop-up candidate window and can be used.

**Comment by ammgws** [comment]
@Lilalas Did you get anywhere with this?

On Arch Linux with `ibus-mozc 2.23.2815.102-3` and `XDG_SESSION_TYPE` set to wayland, I do not even get the "default candidate window" shown in the first screenshot but can still toggle through iterations. With XDG_SESSION_TYPE set to tty I get the mozc_renderer fallback, but this one actually shows the pop-up candidate window and can be used.

**Comment by Lilalas** [comment]
@ammgws Sorry for replying very late—but no, I never got anywhere with this. I actually switched away from Wayland for some other issue. For the sake of writing this comment, I switched back to a Wayland session and it still behaves exactly like shown in the “actual behavior” above.

The thing is, Ubuntu still only provides version `2.20.2673.102+dfsg-2ubuntu0.18.04.1` for my system via APT, so I guess it’s their fault for not updating the package.

Unfortunately I do not understand how to manipulate this `XDG_SESSION_TYPE` you’re talking about, so I can’t test anything with that.

**Comment by AdrienLemaire** [comment]
@yukawa is mozc supposed to work in wayland? Because I realized in https://github.com/swaywm/sway/issues/4841 that it never works on native wayland applications, and I need to switch these apps to xwayland in order to get japanese input... 意味がない
