### ISSUE TITLE
Android: no candidates, only hiragana, crash on tap

### ISSUE THREAD

**Issue by ashimokawa** [google/mozc#432]
I built a working mozc successfully in January 2017, now with latest master there are no kanji candidates listed and when tapping on the only hiragana string, mozc crashes and displays:

```
01-12 08:31:21.598  1385  1410 F Mozc    : 2606643488  ../../session/session_converter.cc(739) CHECK [(0) == (segments_->conversion_segments_size())] 
```

**Comment by ashimokawa** [comment]
reverting 1aa25f461b823a43b1b92e4c4234a5bb0d0f2a80 fixes the problem for me

**Comment by furkanmustafa** [comment]
Thanks, reverting that fixed it for me too.

**Comment by picsi** [comment]
How do you go about reverting it?

**Comment by furkanmustafa** [comment]
@picsi 
Clone the repository and type;

```
git revert 1aa25f4
```

It's going to cause a small conflict, but you can fix that conflict, it's just a version string.

**Comment by picsi** [comment]
This is what I got:

> $ git revert 1aa25f4
error: could not revert 1aa25f46... Support minimal engine
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

What can I do?

**Comment by furkanmustafa** [comment]
Here is an already fixed one;
 - [Release v2.23.102-rlab](https://git.rlab.io/android/mozc/tags)
 - [Revert Commit](https://git.rlab.io/android/mozc/commit/e577549e749a3d4c2d3005551e695b0e7ea4343e)
 - [Direct apk download](https://git.rlab.io/android/mozc/uploads/6e7ad3ff163be23a8c4837aa8f21e7c5/mozc-debug.apk)

**Comment by picsi** [comment]
Perfect, thanks a lot!

**Comment by picsi** [comment]
@furkanmustafa is that link still up? I cannot access it

**Comment by furkanmustafa** [comment]
Sorry, down temporarily due to technical problems.

You can try this URL: http://furkanmustafa.net/files/mozc-debug.apk
SHA256: `3a481026f1323e0fdfbb60e33d1140eeb1f2e3d894f349713b045bea93460b7e`
