### ISSUE TITLE
mocz_tool --mode=hand_writing dosen't work on manjaro linux

### ISSUE THREAD

**Issue by BeatsMe** [google/mozc#438]
I have problem with mozc_tool's handwriting recognition.
The problem is that every kanji characters I input are resulted as error like below.
![image](https://user-images.githubusercontent.com/11363216/39635256-ed670a6a-4ff7-11e8-8f45-3fbff5c0342a.png)
I posted the error to the manjaro user's forums but no one can't fix it.
[https://forum.manjaro.org/t/japanese-hand-writing-recognition-is-broken/41082](https://forum.manjaro.org/t/japanese-hand-writing-recognition-is-broken/41082)

Thanks in advance.

**Comment by jamesrwaugh** [comment]
Correct me if I'm wrong but it looks like the cloud handwriting mode contains secret sauce not exposed by Google, which won't work out of this box, so the Zinnia mode is always used:
https://github.com/google/mozc/blob/master/src/handwriting/cloud_handwriting.cc#L44

When I build in Debug, and enable logs, I get the following, meaning it seems the Zinnia mode is enabled by default:

`./mozc_tool --mode=hand_writing --logtostderr`

`
2019-07-20 23:39:05 20859 140500315393152 ../../handwriting/zinnia_handwriting.cc(76) LOG(ERROR) Cannot open model file:/usr/share/tegaki/models/zinnia/handwriting-ja.model`

So, perhaps it would be enough to install the Zinnia model (https://github.com/taku910/zinnia, the default tomoe model most likely) before running. It looks like there are Gyp scripts to do this here as well.

**Comment by BeatsMe** [comment]
Installing tegaki-models-zinnia-japanese package has resolved the problem. Thank you.
