### ISSUE TITLE
Cannot find tools/ant/build.xml

### ISSUE THREAD

**Issue by Rudloff** [google/mozc#439]
Hello,

I get this error when I run `python build_mozc.py build -c Debug android/android.gyp:apk`:
```
BUILD FAILED
/home/pierre/www/mozc/src/android/build.xml:120: Cannot find /home/pierre/lib/android-sdk/tools/ant/build.xml imported from /home/pierre/www/mozc/src/android/build.xml
```

I think this file is not provided by the Android SDK anymore.

**Comment by hiroyuki-komatsu** [comment]
Since the build system for Android library has been changed to Bazel, and CIs for Android was resumed.
Please let us close this issue as obsolete.

Thanks,
