### ISSUE TITLE
Travis CI broken on TARGET_PLATFORM=NaCl

### ISSUE THREAD

**Issue by yodalee** [google/mozc#446]
Travis log:
https://travis-ci.org/google/mozc/jobs/384786382

Seems a certificate problem

**Comment by yodalee** [comment]
https://groups.google.com/forum/#!topic/native-client-discuss/ViBofmhWpyM
It seems a certificate problem, comment out the certificate lines can solve this issue.

However, consider the situation that NaCl is going to be replaced by Wasm
https://developer.chrome.com/native-client/migration
I think maybe the mozc can migrate to Wasm and deprecate NaCl support too?

**Comment by hiroyuki-komatsu** [comment]
NaCl is deprecated, and CIs with GitHub Actions have been introduced.
https://github.com/google/mozc/commit/3aa19b0c65024d4e27431e7cedeb9d84b838642b

Thank you,
