### ISSUE TITLE
Недочеты в WTL 10

### ISSUE THREAD

**Issue by ArgusC** [google/mozc#449]
При работе над программой в MS VS 2017 использовал WTL/ATL 10, но в нем есть ошибки. В частности не была определена переменная COLOR_MENUHILIGH в файле atlctrlw.h. В данной версии (@mozc@ определил ее как 9.1.5321) имеются строки:

#ifndef COLOR_MENUHILIGHT
						const int COLOR_MENUHILIGHT = 29;
#endif // !COLOR_MENUHILIGHT

За это я ему и благодарен! Успехов и удачи!

**Comment by hiroyuki-komatsu** [comment]
The latest version (e.g. 4700ed5fb96064317f66de90dfb9b4cef90e95b6) supports the build with MS VS 2017.

Would you please try the latest version?
If you still have a problem, please feel free to reopen it.
