### ISSUE TITLE
Cannot build an Android app when specifying --android_application_id

### ISSUE THREAD

**Issue by oyayubikun** [google/mozc#451]
Although I can successfully build an Android app when I did not change android_application_id (org.mozc.android.inputmethod.japanese), I cannot build an app when specifying --android_application_id like:
python build_mozc.py gyp --target_platform=Android --android_application_id com.myapp.ime.a1.g1

build_mozc_in_docker.md says "Currently the application package is fixed (org.mozc.android.inputmethod.japanese). Don't publish the built package. If you want to publish, specify `--android_application_id` to `build_mozc.py gyp` command and manually update related files."

Therefore, I tried manually update related files, like grep & replace all "org.mozc.android.inputmethod.japanese" and all "org/mozc/android/inputmethod/japanese" in the files when trying the second build command (python build_mozc.py build -c Debug android/android.gyp:apk) but I cannot succeed.
It gives me the following messages after [609/609]:
[609/609] ACTION apk: apk_bec1b109f2cd44ee526559877aaecd2b
...
[buildconfig] Generating BuildConfig class.
-pre-compile:
-compile:
    [javac] Compiling 2410 source files to /home/mozc_builder/mozc3/src/android/bin/classes
    [javac] /home/mozc_builder/mozc3/src/android/gen/com/myapp/ime/a1/g1/BuildConfig.java:2: error: ';' expected
    [javac] package com.myapp.ime.a1.g1;
    [javac]                         ^
    [javac] /home/mozc_builder/mozc3/src/android/gen/com/myapp/ime/a1/g1/R.java:8: error: ';' expected
    [javac] package com.myapp.ime.a1.g1;
    [javac]                         ^
    [javac] 2 errors

Can anyone teach me what file should I look into?

**Comment by jamesrwaugh** [comment]
@oyayubikun Did you solve the issue?
