### ISSUE TITLE
"～" is not "WAVE DASH"

### ISSUE THREAD

**Issue by redpizza** [google/mozc#452]
キーボードから`～`(U+FF5E)を入力して変換すると変換候補の`～`に`[全] 波ダッシュ`という説明が表示されますがこれは`FULLWIDTH TILDE`です
`WAVE DASH`ではないのでこの説明は混乱を招きます

![default](https://user-images.githubusercontent.com/31765780/45262493-bb731700-b452-11e8-82ab-7560f90e1801.png)

ついでにいうと半角の波ダッシュなどというものは存在しないので`~`に`[半] 波ダッシュ`と表示されるのは変です

それぞれは`[全] チルダ` `[半] チルダ`と表示されるのが望ましいと思われます

**Comment by tomatojuicengc5195** [comment]
これに賛同します。

**Comment by hiroyuki-komatsu** [comment]
Thank you for the feedback.

I will try to make time to address this issue.
Note, this happens only on Windows.

**Comment by hiroyuki-komatsu** [comment]
d546d6a and a0d2cf1 fixed this issue.
Thank you for the report.
