### ISSUE TITLE
Building android version without docker/with newer SDKs

### ISSUE THREAD

**Issue by TiloWiklund** [google/mozc#459]
It would be nice to be be able to easily build mozc without docker and with a system SDK. After a bit of experimenting I managed to get it to compile on my (Gentoo) system with a recent SDK with only a couple of hurdles. One must:

*  force system to default to python2 ([related issue](https://github.com/google/mozc/issues/417))
*  modify mozc/src/android/android_env.gypi and to fix hardcoded path /usr/share/java path
*  download/copy the ant build-scripts (sdk/tools/ant) ([related issue](https://github.com/google/mozc/issues/439))
*  make sure android support library is available (in sdk/android/support/), [direct link](https://dl.google.com/dl/android/repository/support_r23.1.1.zip) can be found in the dockerfile
*  copy org.apache.http.legacy.jar from sdk/platforms/*/optional to mozc/src/android/libs
*  patch a couple of legacy Float.sqrt calls (see e.g. https://stackoverflow.com/questions/32065160/method-floatmath-sqrt-not-found)
*  patch a couple of depricated Canvas.save(int) calls (see e.g. https://github.com/timusus/RecyclerView-FastScroll/pull/96), just replace with Canvas.save()
*  ComposingTextTrackingInputConnection is lacking a couple of overrides:
    - commitContent (just return false?)
    - closeConnection (just make it nop?)
    - getHandler (just return null?)
    - deleteSurroundingTextInCodePoints (just return false?)

**Comment by hiroyuki-komatsu** [comment]
Since the build system for Android library has been changed to Bazel, and CIs for Android was resumed.
Please let us close this issue as obsolete.

Thanks,
