### ISSUE TITLE
Add support for U+32FF (two-kanji square ligature for Japan's new era name)

### ISSUE THREAD

**Issue by kenlunde** [google/mozc#461]
**Background** → Japan is planning to announce the name of their new era on 2019-04-01 (_no joke_), which takes effect on 2019-05-01. Unicode will issue Version 12.1 of their standard to add U+32FF, which is for the two-kanji square ligature form of the new era name. I will be supplying to Google an updated set of _Noto Sans CJK_ fonts no later than 2019-04-12 (Version 2.001) that will include the horizontal and vertical glyphs for U+32FF. This is for Google's ecosystem. (The Version 2.000 fonts actually included blank placeholder glyphs for U+32FF, which is intended to make the Version 2.001 update an easier process for me.)

Modern Japanese IMEs allow the user to enter the name of a Japanese era, such as 平成 (_heisei_), and to convert it into the two-kanji square ligature form, which is ㍻ (U=337B) for this example. The screenshot below that was provided to me by a colleague shows that this Japanese IME supports such functionality for the current era name that was exemplified in this paragraph:

![CurrentEraHeiseiLigature](https://user-images.githubusercontent.com/3988788/55046114-9b293500-4ffd-11e9-9c1b-08b380715d45.png)

Adding such support may very well be on the radar already, but if not, please don't let if fall between the proverbial cracks.

**Comment by utuhiro78** [comment]
This patch will add the U+32FF candidate.
[add-new-japanese-era.patch.txt](https://github.com/google/mozc/files/3114284/add-new-japanese-era.patch.txt)

Please use this font to show the character properly.
https://github.com/googlefonts/noto-cjk/blob/master/NotoSansCJK-Regular.ttc

Type "reiwa". You will see the candidates.
![reiwa-20190425](https://user-images.githubusercontent.com/34818411/56695469-20e6f000-6724-11e9-80b8-8318d639a724.png)

The patch will also add Reiwa (令和, a new Japanese era) to date_rewriter.cc.
It generates some Reiwa candidates.
"kotosi" (this year) => "令和元年" (Reiwa 1)
"kyou" (today) => "令和元年5月1日" (Reiwa 1, May 1)

**Comment by hiroyuki-komatsu** [comment]
The conversion to a single character for the new era "㋿" (U+32FF) was added by the update on 2020-08-22 (a1dcada).

Thank you,
