### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by Arfrever** [google/mozc#462]
Python 2.7 will be discontinued by upstream in 9 months, on 2020-01-01. See https://pythonclock.org/.
Python code in Mozc should be ported to Python 3.

**Comment by Keruspe** [comment]
Any progress on this?

**Comment by Arfrever** [comment]
Patch: [mozc-2.23.2815.102-python-3.patch.txt](https://github.com/google/mozc/files/4048079/mozc-2.23.2815.102-python-3.patch.txt)

Patch successfully tested on GNU/Linux system.

Besides files actually used on GNU/Linux system:
* `src/android/gen_emoji_data.py` tested and seems to work.
* `src/android/gen_emoticon_data.py` tested and seems to work.
* `src/android/gen_mozc_drawable.py` tested and seems to work.
* `src/android/gen_touch_event_stats.py` operates on statistics unavailable in Mozc open-source repository (`src/android/collected_keyboards.csv` and `src/data/typing/touch_event_stats.csv` are almost empty), so this script creates only empty directory.
* `src/android/run_android_test.py` cannot be tested without Android-related tools (e.g. `adb`) and device (`INFO:user:All the activated devices are []`, `INFO:user:No devices are specified. Do nothing.`)
* `src/chrome/nacl/nacl_net_test_server.py` not tested.
* `src/chrome/nacl/pnacl_translate.py` not tested.
* `src/chrome/nacl/run_nacl_test.py` not tested.
* `src/client/gen_client_quality_test_data.py` not normally used anywhere but manually tested and seems to work.
* `src/data/test/calculator/gen_test.py` not normally used anywhere but manually tested and seems to work.
* `src/mac/generate_mapping.py` tested and seems to work.
* `src/win32/installer/postbuilds_win.py` is broken on Windows (`NameError: name 'PostProcessOnWindows' is not defined`) and does nothing on non-Windows.

**Comment by utuhiro78** [comment]
Thanks Arfrever, your patch works fine on Arch Linux.
I posted new PKGBUILD to https://bugs.archlinux.org/task/65124 .

**Comment by hiroyuki-komatsu** [comment]
Python3 is supported since the update on 2020-10-18 (a5a4927c1f709d2ff0c681585c746f73a434e4c9).
Thank you,
