### ISSUE TITLE
Android 64-bit for new Google Play requirement

### ISSUE THREAD

**Issue by oyayubikun** [google/mozc#463]
As of August, 2019, Google Play requires to support 64-bit version too.
But I don't know how to build a 64-bit version.
Can anyone teach me how to and where to look when building a 64-bit version of mozc for Android?

**Comment by oyayubikun** [comment]
When I tried to build an arm64 apk by specifying 'arm64' in '--android_arch', the build process stops fails with the following log. Can anyone help me with this? Should I update protobuf?
[109/609] CXX obj/third_party/protobuf/src/google/protobuf/protobuf.descriptor.pb.o
FAILED: /home/mozc_builder/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm64/bin/aarch64-linux-android-g++ -MMD -MF obj/third_party/protobuf/src/google/protobuf/protobuf.descriptor.pb.o.d -DMOZC_BUILD -DCHANNEL_DEV -DMOZC_USE_SEPARATE_CONNECTION_DATA -DMOZC_USE_SEPARATE_DICTIONARY -DNO_USAGE_REWRITER -DGOOGLE_PROTOBUF_NO_RTTI -DOS_ANDROID -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ -DNDEBUG -DQT_NO_DEBUG -DNO_LOGGING -DIGNORE_HELP_FLAG -DIGNORE_INVALID_FLAG -I/home/mozc_builder/mozc/src -Igen -I../../protobuf -I../../third_party/protobuf/src -Wall -Wno-char-subscripts -Wno-sign-compare -Wno-deprecated-declarations -Wwrite-strings -fPIC -fno-exceptions -fmessage-length=0 -fno-strict-aliasing -funsigned-char -include base/namespace.h -pipe -pthread -fno-omit-frame-pointer -fstack-protector --param=ssp-buffer-size=4 -Wno-conversion-null -Wno-unused-function -Wno-unknown-warning-option -Wno-unused-local-typedefs -fPIE -O2 -Wno-deprecated -std=gnu++0x  -c ../../third_party/protobuf/src/google/protobuf/descriptor.pb.cc -o obj/third_party/protobuf/src/google/protobuf/protobuf.descriptor.pb.o
In file included from ../../third_party/protobuf/src/google/protobuf/stubs/atomicops.h:59:0,
                 from ../../third_party/protobuf/src/google/protobuf/stubs/once.h:81,
                 from ../../third_party/protobuf/src/google/protobuf/descriptor.pb.cc:10:
../../third_party/protobuf/src/google/protobuf/stubs/platform_macros.h:61:2: error: #error Host architecture was not detected as supported by protobuf
 #error Host architecture was not detected as supported by protobuf
  ^
In file included from ../../third_party/protobuf/src/google/protobuf/stubs/once.h:81:0,
                 from ../../third_party/protobuf/src/google/protobuf/descriptor.pb.cc:10:
../../third_party/protobuf/src/google/protobuf/stubs/atomicops.h:161:1: error: stray '#' in program
 #error "Atomic operations are not supported on your platform"
 ^
../../third_party/protobuf/src/google/protobuf/stubs/atomicops.h:191:1: note: in expansion of macro 'GOOGLE_PROTOBUF_ATOMICOPS_ERROR'
 GOOGLE_PROTOBUF_ATOMICOPS_ERROR
 ^
../../third_party/protobuf/src/google/protobuf/stubs/atomicops.h:161:2: error: 'error' does not name a type
 #error "Atomic operations are not supported on your platform"

**Comment by hiroyuki-komatsu** [comment]
Since the build system for Android library has been changed to Bazel, and CIs for Android was resumed.
Please let us close this issue as obsolete.

Thanks,
