### ISSUE TITLE
Patent infringement claim from Toshiyasu Abe

### ISSUE THREAD

**Issue by oyayubikun** [google/mozc#465]
I received a patent infringement notification letter regarding my Android App from Protea Legal Co. who represents Mr. Toshiyasu Abe who lives in Oregon, US.

It seems that the patent owner has sent the letter because of "flick input" used in my App. The flick input part is not modified from the original "mozc for Android".

The letter mentions US Patent 6,520,699 (filed on 2001/2/16) and China Patent 100396499.
https://patents.google.com/patent/US6520699B2/en

It seems that the patent owner has started a lawsuit against Apple in June 2018.
https://www.patentlyapple.com/patently-apple/2018/06/a-patent-infringement-lawsuit-has-been-filed-against-apple-for-their-flick-style-idevice-keyboards.html
The case is now closed because of Voluntary Dismissal filed by Abe.
https://www.pacermonitor.com/public/case/24840013/Abe_v_Apple,_Inc

The complaint focuses on claim 52 of US Patent 6,520,699.

52. A user interface device comprising:
a plurality of buttons displayed on a touch sensitive screen, each button being associated with a plurality of characters or functions;
a force detector for detecting force applied to one or more of the plurality of buttons;
a lateral movement sensor for sensing direction of motion of a stroke performed on the touch sensitive screen; and
a selection component for selecting at least one of a character or function based on the detected force and the sensed direction of motion.

Has anybody else received the letter?
I know that a flick input was developed earlier by Mr. Hashimoto who filed a patent application JP2000-112636A1 that was laid open on 2000/4/21 prior to the filing of the Abe patent.
https://worldwide.espacenet.com/publicationDetails/biblio?DB=EPODOC&II=0&ND=3&adjacent=true&locale=en_EP&FT=D&date=20000421&CC=JP&NR=2000112636A&KC=A#

Of course, the Abe patent cannot be used to enforce what is written in Hashimoto patent application if the invention was made later than the laid open date or a release date. Abe patent may be limited to specific technology or may be invalid. 
Anyone has any information?

**Comment by oyayubikun** [comment]
I forgot to mention that, since "first to invent" rule is applied to US Patent 6,520,699, the patent owner may assert (with proof) that the invention was made as early as 2000/2/16, earlier than the laid open date (2000/4/21) of patent application of Mr. Hashimoto who made the "Hanabi" app for Apple Newton PDA.

**Comment by agajo** [comment]
@oyayubikun 
I received a very similar claim from Mr. Abe and Attorney, Protea Legal Co.
I don't know how precise I can write about the claim in this open comment.
Can you contact me?
https://twitter.com/agajo_tech

**Comment by oyayubikun** [comment]
Thank you for your reply.
I had worked for a Japanese electronics company to deal this type of issue and US patent litigations.
I will email you today.
