### ISSUE TITLE
Support Reiwa

### ISSUE THREAD

**Issue by kurehajime** [google/mozc#466]
Please support Reiwa.

ex:
2019年 -> 令和元年

**Comment by oyayubikun** [comment]
In addition to adding a line in src\data\dictionary_oss\dictionary08.txt, Reiwa support can be done by inserting 5 lines in line 1505 in src\rewriter\date_rewriter.cc like the following:
    // "平成" "へいせい"
    1989,
    "\xE5\xB9\xB3\xE6\x88\x90",
    "\xE3\x81\xB8\xE3\x81\x84\xE3\x81\x9B\xE3\x81\x84",
  }, {
    // "令和" "れいわ"
    2019,
    "\xE4\xBB\xA4\xE5\x92\x8C",
    "\xE3\x82\x8C\xE3\x81\x84\xE3\x82\x8F",
  }

**Comment by Arfrever** [comment]
Duplicate of #461.
