### ISSUE TITLE
Support environmental variables

### ISSUE THREAD

**Issue by Arfrever** [google/mozc#470]
It would be useful if Mozc supported environmental variables for additional run-time configurability.
Suggested environmental variables:
- `MOZC_SERVER_DIRECTORY`
This variable would override build-time `server_dir` GYP option (`/usr/lib/mozc` by default).
- `MOZC_DOCUMENTS_DIRECTORY`
This variable would override build-time `document_dir` GYP option (`/usr/lib/mozc/documents` by default).
- `MOZC_ZINNIA_MODEL_FILE`
This variable would override build-time `zinnia_model_file` GYP option (e.g. `/usr/share/tegaki/models/zinnia/handwriting-ja.model`).
- `MOZC_CONFIGURATION_DIRECTORY`
This variable would set Mozc configuration directory (e.g. `/home/username/.mozc`).
- `HOME`
This variable would be used on Unix-like systems for calculating Mozc configuration directory if `MOZC_CONFIGURATION_DIRECTORY` variable is not set.
If `MOZC_CONFIGURATION_DIRECTORY` variable is not set and `HOME` variable is set, then `${HOME}/.mozc` would be used.
If neither `MOZC_CONFIGURATION_DIRECTORY` variable nor `HOME` variable is set, then preexisting logic would be used, which gets home directory from `/etc/passwd` file.

Patch: [mozc-environmental_variables.patch.txt](https://github.com/google/mozc/files/3930957/mozc-environmental_variables.patch.txt)

**Comment by hiroyuki-komatsu** [comment]
Hi, thank you for the suggestions.

We do not have a plan to support run-time configurations of the install paths, because it introduces additional edge cases we need to care about.

Instead, we have supported $XDG_CONFIG_HOME as mentioned in #474
