### ISSUE TITLE
Conversion from `きょう' does not support Japanese new era

### ISSUE THREAD

**Issue by nilninull** [google/mozc#472]
「きょう」を変換すると表示される当日日付の和暦表示が、「平成」のままになっています。

ちなみに、書き込み時点での結果は、「きょう」→ 「平成31年12月11日」です。

The date displayed when converting from "きょう" remains "平成" in the Japanese calendar.

The conversion result as of today is `平成31年12月11日'.

My mozc version is 2.23.2815.102.

**Comment by LavP** [comment]
明らかにmozcがメンテナンスされてない感じがします(ToT)

**Comment by LavP** [comment]
![image](https://user-images.githubusercontent.com/13294981/70698607-2e7cd480-1d0b-11ea-8ed1-658abcf9c0be.png)

少なくとも、私が使用ているバージョン `GoogleJapaneseInput-2.25.3700.1+24.7.9` ではサポートされています。

また、既にこれは[issue](https://github.com/google/mozc/issues/461)が立てられていて解決しているようです。

mozcを明示的にバージョンアップしてみてはどうでしょう？

**Comment by Arfrever** [comment]
あいにく、Mozc (open source) は Google Japanese Input (closed source) に遅れを取っています。
Mozcの[一番新しいバージョン](https://github.com/google/mozc/commits/master)は2.23.2815です.

**Comment by hiroyuki-komatsu** [comment]
The conversion to the new era "令和" was added by the update on 2020-08-22 (a1dcadabd3a1c604e8beff1e45830c1d9adfce84).

Thanks,
