### ISSUE TITLE
Could not build mozc for Android although I followed instructions

### ISSUE THREAD

**Issue by aspirefive** [google/mozc#476]
I tried to build mozc for Android but failed. Can someone help me with this?
Here's what I did.
I followed docs/build_mozc_in_docker.md.
I set up docker CE in ubuntu 14.04.
After getting Dockerfile by

> curl -O https://raw.githubusercontent.com/google/mozc/master/docker/ubuntu14.04/Dockerfile

I removed several NaCl lines because they seem to have problems and I don't build NaCl apps.
Then, I did "docker build" and "docker run" as written.
Then, in docker, when I tried to build by:

> python build_mozc.py gyp --target_platform=Android

it gave me the following error messages.

> INFO: Generating version definition file...
> INFO: Version string is 3.5.3050.103
> INFO: Running: /usr/bin/python /home/mozc_builder/mozc/src/build_tools/ensure_gyp_module_path.py --expected=/home/mozc_builder/mozc/src/third_party/gyp/pylib/gyp
> INFO: Build tool: ninja
> INFO: Building GYP command line...
> INFO: Android home is set from  --android_home option: /home/mozc_builder/work/android-sdk-linux
> INFO: Android NDK home is set from  --android_ndk_home option: /home/mozc_builder/work/android-ndk-r16b
> WARNING: gmock not found. Disabling unittest.
> INFO: Running GYP...
> INFO: Running: /usr/bin/python /home/mozc_builder/mozc/src/third_party/gyp/gyp_main.py --depth=. --include=./gyp/common.gypi -D abs_depth=/home/mozc_builder/mozc/src -D additional_third_party_dir=/home/mozc_builder/mozc/src/third_party -D python_executable=/usr/bin/python ./android/android.gyp ./android/genproto_java.gyp ./android/protobuf/protobuf.gyp ./android/resources/resources.gyp ./android/userfeedback/userfeedback.gyp ./base/base.gyp ./base/base_test.gyp ./client/client.gyp ./client/client_test.gyp ./composer/composer.gyp ./composer/composer_test.gyp ./config/config.gyp ./config/config_test.gyp ./converter/converter.gyp ./converter/converter_base.gyp ./converter/converter_main.gyp ./converter/converter_test.gyp ./data/test/session/scenario/scenario.gyp ./data/test/session/scenario/usage_stats/usage_stats.gyp ./data_manager/chromeos/chromeos_data_manager.gyp ./data_manager/chromeos/chromeos_data_manager_base.gyp ./data_manager/chromeos/chromeos_data_manager_test.gyp ./data_manager/data_manager.gyp ./data_manager/data_manager_test.gyp ./data_manager/oss/oss_data_manager.gyp ./data_manager/oss/oss_data_manager_base.gyp ./data_manager/oss/oss_data_manager_test.gyp ./data_manager/packed/packed_data_manager.gyp ./data_manager/packed/packed_data_manager_base.gyp ./data_manager/testing/mock_data_manager.gyp ./data_manager/testing/mock_data_manager_base.gyp ./data_manager/testing/mock_data_manager_test.gyp ./dictionary/dictionary.gyp ./dictionary/dictionary_base.gyp ./dictionary/dictionary_test.gyp ./dictionary/file/dictionary_file.gyp ./dictionary/file/dictionary_file_test.gyp ./dictionary/system/system_dictionary.gyp ./dictionary/system/system_dictionary_test.gyp ./engine/engine.gyp ./gui/gui.gyp ./gyp/tests.gyp ./handwriting/handwriting.gyp ./handwriting/handwriting_test.gyp ./handwriting/zinnia.gyp ./ipc/ipc.gyp ./net/jsoncpp.gyp ./net/net.gyp ./net/net_test.gyp ./prediction/prediction.gyp ./prediction/prediction_base.gyp ./prediction/prediction_test.gyp ./protobuf/protobuf.gyp ./protocol/protocol.gyp ./renderer/renderer.gyp ./request/request.gyp ./rewriter/calculator/calculator.gyp ./rewriter/rewriter.gyp ./rewriter/rewriter_base.gyp ./rewriter/rewriter_test.gyp ./server/server.gyp ./session/session.gyp ./session/session_base.gyp ./session/session_test.gyp ./storage/storage.gyp ./storage/storage_test.gyp ./testing/testing.gyp ./transliteration/transliteration.gyp ./transliteration/transliteration_test.gyp ./usage_stats/usage_stats.gyp ./usage_stats/usage_stats_base.gyp ./usage_stats/usage_stats_test.gyp -D branding=Mozc -D use_qt=NO -D qt_dir= -D use_wix=NO -D android_home=/home/mozc_builder/work/android-sdk-linux -D android_arch=arm -D android_stl=libcxx -D android_compiler=gcc -D android_ndk_home=/home/mozc_builder/work/android-ndk-r16b -D android_application_id=com.mozc.android.inputmethod.japanese -D build_base=out_android -D build_short_base=out_android -D enable_unittest=0 -D warn_as_error=0 -D channel_dev=1 -D enable_cloud_handwriting=0 -D target_platform=Android -D use_dynamically_linked_qt=0 -D dictionary=small -D use_separate_collocation_data=0 -D use_separate_connection_data=1 -D use_separate_dictionary=1 -D use_1byte_cost_for_connection_data=1 -D use_packed_dictionary=0 -D pkg_config_command=pkg-config --generator-output=. -G output_dir=out_android
> gyp: Call to 'bash /home/mozc_builder/work/android-ndk-r16b/build/tools/make-standalone-toolchain.sh "--toolchain=arm-linux-androideabi-4.9" "--stl=libcxx" "--install-dir=/home/mozc_builder/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm" "--platform=android-14"' returned exit status 1 while in android/android.gyp.
> Traceback (most recent call last):
>   File "build_mozc.py", line 1371, in <module>
>     main()
>   File "build_mozc.py", line 1367, in main
>     procedure[1](cmd_opts, cmd_args, original_directory_name)
>   File "build_mozc.py", line 892, in GypMain
>     RunOrDie(gyp_command + gyp_options)
>   File "/home/mozc_builder/mozc/src/build_tools/util.py", line 99, in RunOrDie
>     '==========']))
> build_tools.util.RunOrDieError: 
> ==========
>  ERROR: /usr/bin/python /home/mozc_builder/mozc/src/third_party/gyp/gyp_main.py --depth=. --include=./gyp/common.gypi -D abs_depth=/home/mozc_builder/mozc/src -D additional_third_party_dir=/home/mozc_builder/mozc/src/third_party -D python_executable=/usr/bin/python ./android/android.gyp ./android/genproto_java.gyp ./android/protobuf/protobuf.gyp ./android/resources/resources.gyp ./android/userfeedback/userfeedback.gyp ./base/base.gyp ./base/base_test.gyp ./client/client.gyp ./client/client_test.gyp ./composer/composer.gyp ./composer/composer_test.gyp ./config/config.gyp ./config/config_test.gyp ./converter/converter.gyp ./converter/converter_base.gyp ./converter/converter_main.gyp ./converter/converter_test.gyp ./data/test/session/scenario/scenario.gyp ./data/test/session/scenario/usage_stats/usage_stats.gyp ./data_manager/chromeos/chromeos_data_manager.gyp ./data_manager/chromeos/chromeos_data_manager_base.gyp ./data_manager/chromeos/chromeos_data_manager_test.gyp ./data_manager/data_manager.gyp ./data_manager/data_manager_test.gyp ./data_manager/oss/oss_data_manager.gyp ./data_manager/oss/oss_data_manager_base.gyp ./data_manager/oss/oss_data_manager_test.gyp ./data_manager/packed/packed_data_manager.gyp ./data_manager/packed/packed_data_manager_base.gyp ./data_manager/testing/mock_data_manager.gyp ./data_manager/testing/mock_data_manager_base.gyp ./data_manager/testing/mock_data_manager_test.gyp ./dictionary/dictionary.gyp ./dictionary/dictionary_base.gyp ./dictionary/dictionary_test.gyp ./dictionary/file/dictionary_file.gyp ./dictionary/file/dictionary_file_test.gyp ./dictionary/system/system_dictionary.gyp ./dictionary/system/system_dictionary_test.gyp ./engine/engine.gyp ./gui/gui.gyp ./gyp/tests.gyp ./handwriting/handwriting.gyp ./handwriting/handwriting_test.gyp ./handwriting/zinnia.gyp ./ipc/ipc.gyp ./net/jsoncpp.gyp ./net/net.gyp ./net/net_test.gyp ./prediction/prediction.gyp ./prediction/prediction_base.gyp ./prediction/prediction_test.gyp ./protobuf/protobuf.gyp ./protocol/protocol.gyp ./renderer/renderer.gyp ./request/request.gyp ./rewriter/calculator/calculator.gyp ./rewriter/rewriter.gyp ./rewriter/rewriter_base.gyp ./rewriter/rewriter_test.gyp ./server/server.gyp ./session/session.gyp ./session/session_base.gyp ./session/session_test.gyp ./storage/storage.gyp ./storage/storage_test.gyp ./testing/testing.gyp ./transliteration/transliteration.gyp ./transliteration/transliteration_test.gyp ./usage_stats/usage_stats.gyp ./usage_stats/usage_stats_base.gyp ./usage_stats/usage_stats_test.gyp -D branding=Mozc -D use_qt=NO -D qt_dir= -D use_wix=NO -D android_home=/home/mozc_builder/work/android-sdk-linux -D android_arch=arm -D android_stl=libcxx -D android_compiler=gcc -D android_ndk_home=/home/mozc_builder/work/android-ndk-r16b -D android_application_id=com.mozc.android.inputmethod.japanese -D build_base=out_android -D build_short_base=out_android -D enable_unittest=0 -D warn_as_error=0 -D channel_dev=1 -D enable_cloud_handwriting=0 -D target_platform=Android -D use_dynamically_linked_qt=0 -D dictionary=small -D use_separate_collocation_data=0 -D use_separate_connection_data=1 -D use_separate_dictionary=1 -D use_1byte_cost_for_connection_data=1 -D use_packed_dictionary=0 -D pkg_config_command=pkg-config --generator-output=. -G output_dir=out_android
>

**Comment by hiroyuki-komatsu** [comment]
Since the build system for Android library has been changed to Bazel, and CIs for Android was resumed.
