### ISSUE TITLE
Handwriting support

### ISSUE THREAD

**Issue by madmalkav** [google/mozc#477]
Currently Mozc seems to only support handwriting input to recognize a kanji and copy to the clipboard.

With the amount of computers including tactile screens, it would be great to have handwriting input support similar to Android.

**Comment by hiroyuki-komatsu** [comment]
Hi, thank you for the feature request.

I'm sorry, but we have stopped supporting the handwriting feature following the upstream project's change to focus on the core typing features.

Mozc's source code for handwriting is available at:
https://github.com/google/mozc/tree/2018-02-26

Thank you,
