### ISSUE TITLE
Keyboard shortcut to switch from direct input to hiragana?

### ISSUE THREAD

**Issue by Krack1n** [google/mozc#480]
What is the default keyboard shortcut to switch from direct mode to hiragana and katakana mode? I have tried changing it in the preferences but no combination I put seems to be working at all. 
Thank you.

**Comment by lifelabocorp** [comment]
Are you using mozc for linux in linux?
If so, I think you should set the default keyboard shortcut to switch from direct mode to hiragana and katakana mode in your IM like fcitx and ibus.
Here's a copy of my web page in Japanese at
 https://eee-life.com/kb/setting/linux
Fcitx設定の変更
「設定」、「Fcitx設定」、「全体の設定」タブで、「Show Advanced Options」にチェックします。そして、「入力メソッドをオンに」に「変換（Henkanmode）」キーを、「入力メソッドをオフに」に「英数（Eisutoggle）」キーを指定します。
