### ISSUE TITLE
Switch between Hiragana and Katakan and Direct Input modes via c/c++ program 

### ISSUE THREAD

**Issue by shreejitpaul** [google/mozc#481]
Please let me know, is there a way to Switch between "Hiragana" and "Katakana" and "Direct Input" modes via c/c++ program 
or any command line tool.
Thank you.

**Comment by hiroyuki-komatsu** [comment]
[SWITCH_INPUT_MODE](https://github.com/google/mozc/blob/master/src/protocol/commands.proto#L343) is the protocol to change the mode.

So technically speaking, you can send it with the proper session ID to change the mode. However please understand this is not our expected usage and this is out of our focus.

Thank you,
