### ISSUE TITLE
Please improve the conversion candidates.今日⇒YYYYMMDD(20201101)

### ISSUE THREAD

**Issue by chesscommands** [google/mozc#483]
I want you to be able to convert "today" to YYYYMMDD format.
I would be happy if there was a format similar to ATOK if possible.

The ATOK format is not limited to "today", but ... First of all, I would like to ask for YYYYMMDD alone.

**Comment by hiroyuki-komatsu** [comment]
Hi, thank you for the request.

To understand the request correctly, would you tell me how you use this YYYYMMDD format?
I'd like to know why the available formats (e.g. YYYY/MM/DD, YYYY-MM-DD, etc.) do not work well?

**Comment by chesscommands** [comment]
Because no symbols are needed.
I wanted 8 digits.

The following has been resolved.
http://techu1999.sakura.ne.jp/python/2019/02/09/mozcのwindowsでのビルド（コンパイル）/

It's not a legitimate solution, but I'm happy with it, so it's okay.
Thank you for your reply.
