### ISSUE TITLE
How to add descriptions to new words

### ISSUE THREAD

**Issue by ekaunt** [google/mozc#485]
I would like to add custom descriptions to words that I add to my user dictionary. 

By custom descriptions I mean the bracketed items in the pictures below (like `[ひらがな]`, and `[従の旧字体]`).

![image](https://user-images.githubusercontent.com/71127209/100412356-72fba000-3042-11eb-999b-ed43e5306bbc.png) ![image](https://user-images.githubusercontent.com/71127209/100412888-e05c0080-3043-11eb-8986-aa78ed63b8d8.png)

These descriptions show up by default. When I select these candidates it inserts the entry without inserting the text in the brackets.

Example:
I type `shita`, and select the option that says `した [ひらがな]`, mozc will then insert `した` into my document, and *not* the full `した [ひらがな]`.

How can I replicate this behavior for my own custom user dictionary entries?

**Comment by hiroyuki-komatsu** [comment]
Hi,

The descriptions are not designed to be customizable with the user dictionary.

Instead, the `comment` of the user dictionary entry (4th field) is used as the usage (用例).

The comments of the user dictionary is filled in `Candidates.usages` as well as other default usages.
https://github.com/google/mozc/blob/master/src/protocol/candidates.proto#L195

**Comment by ekaunt** [comment]
Is there a way to always keep the comment window open?

Its very cumbersome to press ctrl+shift+i every time I want to check the definition/comment…

**Comment by hiroyuki-komatsu** [comment]
Because that is a feature of Fcitx, please talk with the Fcitx team.
