### ISSUE TITLE
Mozc-2.25+ can't convert amount of money (10まんえん=>10蔓延)

### ISSUE THREAD

**Issue by utuhiro78** [google/mozc#487]
Mozc-2.25+ can't convert amount of money.
I tested them on Mozc-2.26.4206.102 with Fcitx.
10まんえん=>10蔓延 (10万円)
10おくえん=>10奥園 (10億円)
10ちょうえん=>10腸炎 (10兆円)
10まん=>10マン
10おく=>10奥
10ちょう=>10丁

Thank you for maintaining the essential software.

**Comment by hiroyuki-komatsu** [comment]
Hi, thank you for the report.

I have also confirmed the same behavior. I will try to make time to check this issue.

> Thank you for maintaining the essential software.

I appreciate your recognition. Thank you.

**Comment by hiroyuki-komatsu** [comment]
The commit ebfca8c96a7bd6887efe303f6b8c5c745b27e093 tweaks the conversion logic and fixes this issue.

**Comment by utuhiro78** [comment]
Thanks! I tested it and it works fine. :-)
