### ISSUE TITLE
如何切换英文与假名？Which keys can switch english to hiragana ?

### ISSUE THREAD

**Issue by xiangdongping999** [google/mozc#488]
请问如何能够在输入的时候切换英文和假名？

Which keys can switch english to hiragana?

**Comment by hiroyuki-komatsu** [comment]
If this means switching the input mode from `direct input` (i.e. English and alphabet characters) to `Hiragana`, it is defined in the TSV files under [src/data/keymap](https://github.com/google/mozc/tree/master/src/data/keymap). The default for Linux build is [ms-ime.tsv](https://github.com/google/mozc/blob/master/src/data/keymap/ms-ime.tsv#L133).

![image](https://user-images.githubusercontent.com/11634377/101275283-d1b1de00-37e7-11eb-90ef-d51007f8ef8d.png)

You can modify them with Mozc settings GUI. [Mozc Settings] > [Keymap style] > [Customize...]

![image](https://user-images.githubusercontent.com/11634377/101275332-2f462a80-37e8-11eb-8bc8-0957925db447.png)

**Comment by xiangdongping999** [comment]
Thank you very much.
