### ISSUE TITLE
Support using system versions of abseil-cpp, gtest, jsoncpp

### ISSUE THREAD

**Issue by Arfrever** [google/mozc#490]
Usage of bundled libraries is discouraged in GNU/Linux distributions.
Build system of Mozc should provide options for using system versions of abseil-cpp, gtest and jsoncpp.

These patches add `use_system_abseil_cpp`, `use_system_gtest` and `use_system_jsoncpp` options to GYP build system of Mozc.
Default values are `0`, and default behavior is unchanged.

Patches for Mozc 2.26.4220 (9ba59b64d53365c1fe93c1c245b4ec3e35bdadf0):
* Patch 1 (abseil-cpp): [mozc-2.26.4220-system_abseil-cpp.patch.txt](https://github.com/google/mozc/files/5720940/mozc-2.26.4220-system_abseil-cpp.patch.txt)
* Patch 2 (gtest): [mozc-2.26.4220-system_gtest.patch.txt](https://github.com/google/mozc/files/5720941/mozc-2.26.4220-system_gtest.patch.txt)
* Patch 3 (jsoncpp): [mozc-2.26.4220-system_jsoncpp.patch.txt](https://github.com/google/mozc/files/5720942/mozc-2.26.4220-system_jsoncpp.patch.txt)

**Comment by hiroyuki-komatsu** [comment]
Thank you for the feedback,

At this moment, we do not have a plan to support the shared libraries for them.
IIUC, gtest or jsoncpp is not used for the Linux application binaries.
For abseil, it's frequently updated, so we'd like to use the specific version.

We have been migrating the build system from GYP to Bazel.
I hope the `--override_repository` flag mitigates the problem.
https://docs.bazel.build/versions/master/external.html

**Comment by Arfrever** [comment]
Using Bazel is very bad idea.
* Bazel itself is very heavy. Size of Bazel tarball is about 300 MiB. (299 MiB for latest Bazel 3.7.2.)
* Bazel is written in Java, which is slow, heavy and available only for few architectures.
* GYP is small. Size of GYP tarball is less than 1 MiB.
* GYP is written in Python, which is relatively lightweight, available for wide range of architectures and likely already installed on systems of users wanting to build Mozc.
