### ISSUE TITLE
Tangle of source files and targets in src/base/absl.gyp

### ISSUE THREAD

**Issue by Arfrever** [google/mozc#491]
`src/base/absl.gyp` currently (9ba59b64d53365c1fe93c1c245b4ec3e35bdadf0) contains tangle of source files and targets.
Many source files belong to different upstream abseil-cpp *.so libraries than implied by names of targets defined in `src/base/absl.gyp`.

*
```
    {
      'target_name': 'absl_base',
      'type': 'static_library',
      'toolsets': ['host', 'target'],
      'sources': [
        '<(absl_srcdir)/base/internal/cycleclock.cc',
        '<(absl_srcdir)/base/internal/low_level_alloc.cc',
        '<(absl_srcdir)/base/internal/raw_logging.cc',
        '<(absl_srcdir)/base/internal/spinlock.cc',
        '<(absl_srcdir)/base/internal/spinlock_wait.cc',
        '<(absl_srcdir)/base/internal/sysinfo.cc',
        '<(absl_srcdir)/base/internal/thread_identity.cc',
        '<(absl_srcdir)/base/internal/throw_delegate.cc',
        '<(absl_srcdir)/base/internal/unscaledcycleclock.cc',
        '<(absl_srcdir)/container/internal/raw_hash_set.cc',
        '<(absl_srcdir)/hash/internal/city.cc',
        '<(absl_srcdir)/hash/internal/hash.cc',
      ],
...
    },
```
Amongst these source files:
* * `libabsl_base.so` is created from:
* * * `base/internal/cycleclock.cc`
* * * `base/internal/spinlock.cc`
* * * `base/internal/sysinfo.cc`
* * * `base/internal/thread_identity.cc`
* * * `base/internal/unscaledcycleclock.cc`
* * `libabsl_city.so` is created from:
* * * `hash/internal/city.cc`
* * `libabsl_hash.so` is created from:
* * * `hash/internal/hash.cc`
* * `libabsl_malloc_internal.so` is created from:
* * * `base/internal/low_level_alloc.cc`
* * `libabsl_raw_hash_set.so` is created from:
* * * `container/internal/raw_hash_set.cc`
* * `libabsl_raw_logging_internal.so` is created from:
* * * `base/internal/raw_logging.cc`
* * `libabsl_spinlock_wait.so` is created from:
* * * `base/internal/spinlock_wait.cc`
* * `libabsl_throw_delegate.so` is created from:
* * * `base/internal/throw_delegate.cc`

---

*
```
    {
      'target_name': 'absl_numeric',
      'type': 'static_library',
      'toolsets': ['host', 'target'],
      'sources': [
        '<(absl_srcdir)/numeric/int128.cc',
      ],
...
    },
```
Amongst these source files:
* * `libabsl_int128.so` is created from:
* * * `numeric/int128.cc`

---

*
```
    {
      'target_name': 'absl_strings_internal',
      'type': 'static_library',
      'toolsets': ['host', 'target'],
      'sources': [
        '<(absl_srcdir)/strings/internal/charconv_bigint.cc',
        '<(absl_srcdir)/strings/internal/charconv_parse.cc',
        '<(absl_srcdir)/strings/internal/escaping.cc',
        '<(absl_srcdir)/strings/internal/memutil.cc',
        '<(absl_srcdir)/strings/internal/str_format/arg.cc',
        '<(absl_srcdir)/strings/internal/str_format/bind.cc',
        '<(absl_srcdir)/strings/internal/str_format/extension.cc',
        '<(absl_srcdir)/strings/internal/str_format/float_conversion.cc',
        '<(absl_srcdir)/strings/internal/str_format/output.cc',
        '<(absl_srcdir)/strings/internal/str_format/parser.cc',
        '<(absl_srcdir)/strings/internal/utf8.cc',
      ],
...
    },
```
Amongst these source files:
* * `libabsl_str_format_internal.so` is created from:
* * * `strings/internal/str_format/arg.cc`
* * * `strings/internal/str_format/bind.cc`
* * * `strings/internal/str_format/extension.cc`
* * * `strings/internal/str_format/float_conversion.cc`
* * * `strings/internal/str_format/output.cc`
* * * `strings/internal/str_format/parser.cc`
* * `libabsl_strings.so` is created from:
* * * `strings/internal/charconv_bigint.cc`
* * * `strings/internal/charconv_parse.cc`
* * * `strings/internal/memutil.cc`
* * `libabsl_strings_internal.so` is created from:
* * * `strings/internal/escaping.cc`
* * * `strings/internal/utf8.cc`

---

*
```
    {
      'target_name': 'absl_strings',
      'type': 'static_library',
      'toolsets': ['host', 'target'],
      'sources': [
        '<(absl_srcdir)/strings/ascii.cc',
        '<(absl_srcdir)/strings/charconv.cc',
        '<(absl_srcdir)/strings/escaping.cc',
        '<(absl_srcdir)/strings/match.cc',
        '<(absl_srcdir)/strings/numbers.cc',
        '<(absl_srcdir)/strings/str_cat.cc',
        '<(absl_srcdir)/strings/str_replace.cc',
        '<(absl_srcdir)/strings/str_split.cc',
        '<(absl_srcdir)/strings/string_view.cc',
        '<(absl_srcdir)/strings/substitute.cc',
      ],
...
    },
```
All these .cc files actually belong to `libabsl_strings.so`, but as noted above, some files belonging to `libabsl_strings.so` are mistakenly added to `absl_strings_internal` target in `src/base/absl.gyp`.

---

*
```
    {
      'target_name': 'absl_time',
      'type': 'static_library',
      'toolsets': ['host', 'target'],
      'sources': [
        '<(absl_srcdir)/time/civil_time.cc',
        '<(absl_srcdir)/time/clock.cc',
        '<(absl_srcdir)/time/duration.cc',
        '<(absl_srcdir)/time/format.cc',
        '<(absl_srcdir)/time/time.cc',
        '<(absl_srcdir)/time/internal/cctz/src/civil_time_detail.cc',
        '<(absl_srcdir)/time/internal/cctz/src/time_zone_fixed.cc',
        '<(absl_srcdir)/time/internal/cctz/src/time_zone_format.cc',
        '<(absl_srcdir)/time/internal/cctz/src/time_zone_if.cc',
        '<(absl_srcdir)/time/internal/cctz/src/time_zone_impl.cc',
        '<(absl_srcdir)/time/internal/cctz/src/time_zone_info.cc',
        '<(absl_srcdir)/time/internal/cctz/src/time_zone_libc.cc',
        '<(absl_srcdir)/time/internal/cctz/src/time_zone_lookup.cc',
        '<(absl_srcdir)/time/internal/cctz/src/time_zone_posix.cc',
        '<(absl_srcdir)/time/internal/cctz/src/zone_info_source.cc',
      ],
...
    },
```
Amongst these source files:
* * `libabsl_civil_time.so` is created from:
* * * `time/internal/cctz/src/civil_time_detail.cc`
* * `libabsl_time.so` is created from:
* * * `time/civil_time.cc`
* * * `time/clock.cc`
* * * `time/duration.cc`
* * * `time/format.cc`
* * * `time/time.cc`
* * `libabsl_time_zone.so` is created from:
* * * `time/internal/cctz/src/time_zone_fixed.cc`
* * * `time/internal/cctz/src/time_zone_format.cc`
* * * `time/internal/cctz/src/time_zone_if.cc`
* * * `time/internal/cctz/src/time_zone_impl.cc`
* * * `time/internal/cctz/src/time_zone_info.cc`
* * * `time/internal/cctz/src/time_zone_libc.cc`
* * * `time/internal/cctz/src/time_zone_lookup.cc`
* * * `time/internal/cctz/src/time_zone_posix.cc`
* * * `time/internal/cctz/src/zone_info_source.cc`

---

Suggested solution is to create targets matching upstream abseil-cpp *.so libraries.

**Comment by hiroyuki-komatsu** [comment]
Hi, thank you for the feedback,

We do not have a plan to support shared libraries for Abseil at this moment.

If you want to use shared libraries of Abseil, using the Bazel build with the `--override_repository` flag and modifying the WORKSPACE file is also a good option.
https://docs.bazel.build/versions/master/external.html

Thanks,
