### ISSUE TITLE
Port mozc_renderer to GTK 4

### ISSUE THREAD

**Issue by Arfrever** [google/mozc#492]
`mozc_renderer` currently still uses GTK+ 2.

[GTK 4.0 was released on 2020-12-16](https://blog.gtk.org/2020/12/16/gtk-4-0/):
> What’s old
> --
>
> GTK 4 is now stable, and we consider it ready for consumption. That does not mean GTK 3 is dead – we will continue to support and update it for the foreseeable future (the latest release, 3.24.24, quietly went out a few days ago). It does mean, however, that **GTK 2 has reached the end of its life**. We will do one final 2.x release in the coming days, and we encourage everybody to port their GTK 2 applications to GTK 3 or 4.

(That library can be called `GTK+` for versions `1.*`, `2.*` and `3.*`, but it was [renamed to `GTK` (without `+`)](https://mail.gnome.org/archives/gtk-devel-list/2019-February/msg00000.html) for versions `4.*`.)

`mozc_renderer` should be ported ideally to GTK 4, or intermediately to GTK+ 3.

**Comment by hiroyuki-komatsu** [comment]
Hi Arfrever,

We understand the announce that GTK 2 has reached the end of its life.
We consider how to deal with it including to port it to GTK 4 and other options.

Thanks,

**Comment by Arfrever** [comment]
Commit 3b3068e924e17f8820a35899f105f2ef838d0535 started introducing Qt-based renderer.
Currently support in `src/renderer/renderer.gyp` is missing.

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/a191e8219c823b232093ab2824da85446112eb7a added colors and the usage information window.

It's still experimental.

![image](https://user-images.githubusercontent.com/11634377/120072869-c4a7e480-c0d0-11eb-8ab8-3d4dbb696642.png)

**Comment by hiroyuki-komatsu** [comment]
We have changed this Qt based candidate window to the default renderer for Bazel build.
* Gtk based candidate window is also able to be built with Bazel.
  + `bazel build renderer:gtk_mozc_renderer --config oss_linux -c opt`
* We don't have a plan to support it for GYP build. GYP build is under [maintenance mode](https://github.com/google/mozc/blob/master/docs/build_mozc_in_docker.md#build-mozc-for-linux-desktop-with-gyp-maintenance-mode)

![image](https://user-images.githubusercontent.com/11634377/123511096-5ef04d80-d6ba-11eb-958f-1a5c835df4ef.png)

We close this issue. If there are bugs on the Qt-based candidate window, please create new issues.
Thank you,
