### ISSUE TITLE
Unable to compile mozc 1459bab with bazel.

### ISSUE THREAD

**Issue by coooooooozy** [google/mozc#493]
Unable to compile mozc 1459bab with bazel.

Error message 
ERROR: /home/mozc_builder/work/mozc/src/BUILD:147:10: error loading package 'server': Label '//third_party/bazel_rules/rules_apple/apple:macos.bzl' is invalid because 'third_party/bazel_rules/rules_apple/apple' is not a package; perhaps you meant to put the colon here: '//:third_party/bazel_rules/rules_apple/apple/macos.bzl'? and referenced by '//:package'

**Comment by hiroyuki-komatsu** [comment]
Thank you for the report.

It seems 1459bab304d9c2cfd9a00d6bccaae687a3616abd contains that build issue with Bazel.

The latest commit (6463e71605e2c6c2e1fcc67117a1c351ffa4a794) should fix the issue.
