### ISSUE TITLE
"--server_dir" is not passed to gen_mozc_xml.py when it is called for main.h

### ISSUE THREAD

**Issue by ftake** [google/mozc#494]
`--server_dir` is not passed to gen_mozc_xml.py when it is called for "main.h". So it does not append the value of `server_dir` (e.g., /usr/lib64/mozc) to `setup_arg` .

This problem exists in both src/unix/ibus/BUILD and src/unix/ibus/ibus.gyp.

**Comment by hiroyuki-komatsu** [comment]
Thank you for the report.

b356dfe4df518b0f2bfbd6f3efe6c4b04a61a630 fixed this issue.

It seems --server_dir was added only for the XML generation but not for the C++ generation, when it was introduced.
