### ISSUE TITLE
Feature proposal: Exporting layout_variant and rank to ibus_config.textproto

### ISSUE THREAD

**Issue by ftake** [google/mozc#495]
Thank you for implementing the new feature, configuration using ibus_config.textproto.

Now I propose exporting two more attribute to message Engine.

```
optional string layout_variant = 4;
optional int32 rank = 5:
```

`layout_variant` is used to set a variant of kayboard layout, such as Dvorak.

`rank` is used when IBus is reset. If rank is not 0, IBus pick that engine to its preload engine list.

openSUSE have been provided additional engines with non-default layout below so that users can use Mozc with a popular layout without a text editor. And the rank of these engine have been 0 (the rank of Mozc with a default layout is 80). So I wonder if we can export `rank` to the configuration file to keep Mozc engines with rank = 0.

- Mozc - JP layout (layout = "jp", rank=0)   --- useful when a machine have a JP and an US layout keyboard
- Mozc - US layout (layout = "us", rank=0)
- Mozc - US Dvorak layout (layout = "us", layout_variant = "dvorak", rank=0)

**Comment by hiroyuki-komatsu** [comment]
Hi, thank you for the feedback. It sounds good.

b356dfe4df518b0f2bfbd6f3efe6c4b04a61a630 added `layout_variant`, `layout_option` and `rank` to ibus_config.textproto.

**Comment by hiroyuki-komatsu** [comment]
Closing this issue.

Please feel free to reopen this issue for further discussions.
