### ISSUE TITLE
Emacs autoloads are useless

### ISSUE THREAD

**Issue by VojtechStep** [google/mozc#497]
The point of the `;;;###autoload` cookies in Emacs lisp code is to extract the annotated pieces of code into a separate file as a build step, so that the user can `(require 'mozc-autoloads)`, which informs the system about the existence of the declared variables and functions, without really loading the entire package. The package itself is only loaded when the declared function are called.

As it's currently written, the exported autoloads immediately trigger loading of the full package: the variables `mozc-keymap-kana-{106jp,101us}` are defined in the autoload, and their initialization calls `mozc-keymap-make-keymap-from-flat-list`, which is itself autoloaded, and therefore loads mozc.

I propose these changes to make the autoloads usefull:

1. Remove autoloads cookies from the helper functions `mozc-keymap-make-keymap`, `mozc-keymap-fill-entries-from-flat-list`, `mozc-keymap-get-entry`, `mozc-keymap-put-entry` and `mozc-keymap-remove-entry` - internal helper functions should not be autoloaded
2. Put the functions from point 1. into an autoloaded progn form, like so:
```elisp
;;;###autoload
(progn
  (defun mozc-keymap-make-keymap ...)
  ...)
```
This copies those functions into the generated mozc-autoloads.el, so that they can be used from the `defvar`'s

3) Put the autoload cookie on `mozc-leim-activate`

4) At the end of the file, put the `(defun mozc-leim-register-input-method ...)`, `(add-hook ...)` and `(mozc-leim-register-input-method)` forms into an autoloaded progn form

Steps 3 and 4 make Emacs register the existence of the input method without loading the entire package, but automatically loads it when the input method is selected.

These changes should allow for lazy-loading mozc without compromising the user experience. I would submit a pull request, but it seems you don't accept those at the moment.

**Comment by hiroyuki-komatsu** [comment]
Thank you for the report.

b8dc3b6 fixes this issue.
