### ISSUE TITLE
Menu icons in Linux are low-resolution

### ISSUE THREAD

**Issue by tanshoku** [google/mozc#498]
As the title says, the icons provided here are only 16x16, which is probably unsuitable for high-dpi displays. Not only this, but some of the icons, such as dictionary and configuration, look really outdated and thus out of place on a modern desktop. I propose some sort of redesign or an adaptation so the menu icons can be sourced from an user's preferred icon pack (ie, using freedesktop standards for sourcing the menu icons if not already), not only the configurator icon, as addressed at #440.

I have made an [icon set](https://github.com/tanshoku/mozc-flat/tree/main) for my own personal usage that suits my preferences and system theme, and which could be used as a starting point for the dictionary and tool icons. The icons under `/src/data/images/mac/` on this repo are also of better quality and could be used as a starting point for a new icon set.

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/185491de8f8ad6ccb0ea44f4ebb425776ab1d861 added mode icons (e.g. Hiragana, Fullwidth Katakana, etc) in 48x48 PNG format and SVG format.

Note, the new design is not exactly same with the previous design under the unix/ directory, but same with the mac/ directory.

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/f4c82a51cddd0f38a31b90c2bff8b3cd1509e2e0 added Bazel rules to combine Material Icons for tool icons.

% bazel build unix:icons
