### ISSUE TITLE
high DP monitors cause preference windows to be too cramped

### ISSUE THREAD

**Issue by E1337Kat** [google/mozc#499]
After installing mozc onto Linux Mint 20.1, I went to set some preferred settings, but I found the settings window to be far too cramped to find anything and no way to resize it. Attached figure 1 shows the default size of a few of the menus. Some of the menus can be resized and made easier to view, but not the main settings menu (labeled config_dialog under the gui src).

 I'm not familiar with C++ GUI applications so I can't say for a definitive fact that this is the problem, but I found this `.ui` file which locks the window [width and height to a really small size](https://github.com/google/mozc/blob/master/src/gui/config_dialog/config_dialog.ui#L55). Realistically, there should be either a scroll or allow the windows to resize as needed. 

The biggest cause, I think for this to happen is having a high resolution monitor set up which requires a certain UI scale factor which mozc does not take into account. (see figures 3 and 4 for display settings)

![fig. 1 - Primary monitor with the various GUI windows open](https://user-images.githubusercontent.com/2062516/111492028-b7ef3380-8712-11eb-8370-17d0c46a5c47.png)
**fig. 1 - Primary monitor with the various GUI windows open**

![fig. 2 - System Information](https://user-images.githubusercontent.com/2062516/111491940-a73ebd80-8712-11eb-863c-9eff0f8c3b8b.png)
**fig. 2 - System Information**

![fig. 3 - Main monitor display settings](https://user-images.githubusercontent.com/2062516/111495231-89268c80-8715-11eb-9d13-c612636ed04a.png)
**fig. 3 - Main monitor display settings**

![fig. 4 - Secondary monitor display settings](https://user-images.githubusercontent.com/2062516/111495288-96dc1200-8715-11eb-85da-59694b60bbcb.png)
**fig. 4 - Secondary monitor display settings**

**Comment by danielzgtg** [comment]
This bug used to affect me, but it was fixed for me in an update.

After the update, the look and feel of the window changed to the following and the buttons were no longer squished together:

![](https://user-images.githubusercontent.com/11634377/101275332-2f462a80-37e8-11eb-8bc8-0957925db447.png)

I am on Ubuntu 21.04. I tried Googling for the development branch for Linux Mint, but couldn't find one. You could report this to downstream Linux Mint maintainers and ask them to backport the fix, or wait for the LTS in April 2022.

I think a workaround I used a few months ago (only tested on one monitor with 200% scaling) was to do `ibus restart` before opening the preferences. Running `/usr/lib/mozc/mozc_tool --mode=config_dialog` to open the window directly from the terminal might also work

**Comment by hiroyuki-komatsu** [comment]
It seems your version is 2.23.2815.102, which does not contain the following fix yet.

https://github.com/google/mozc/blame/master/src/gui/base/util.cc#L94

Would you try an updated version as Daniel also suggested?
Thank you,

**Comment by E1337Kat** [comment]
OK. After fighting with the docker build and the existing apt-package for ibus-mozc, I think I was able to get the latest source for the tool which fixed the scaling. I will also try and find where to submit a bug ticket with Linux Mint to backport a fresher version of mozc for HiDPI support. HiDPI setups are becoming more and more common already, and I don't see any major issues with the newer version so far. Thanks for the help.

ありがとうございます　＾＿＾
