### ISSUE TITLE
Highlighted region is unreadable when using dark color themes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#5]
```
What steps will reproduce the problem?
1. Open gedit text editor
2. Set color scheme to 'Oblivion', which have dark background color
3. Start preediting with ibus-mozc

What is the expected output? What do you see instead?

Highlighted region in preedit text should be displayed with a dark 
foreground color because the background color is a light color (#0xD1EAFF), 
but both foreground and background color become light (See screenshot). For 
highlighted region, mozc engine seems to specify only background color.

What version of the product are you using? On what operating system?

I use rev. 23 in Ubuntu 10.04.

Please provide any additional information below.


```

Original issue reported on code.google.com by `irieshin...@gmail.com` on 25 May 2010 at 7:14

Attachments:
- [Screenshot-*編集中のドキュメント 1 - gedit.png](https://storage.googleapis.com/google-code-attachments/mozc/issue-5/comment-0/Screenshot-*編集中のドキュメント 1 - gedit.png)

**Comment by Archibalde** [comment]
Hello,

Has the issue really be fixed? I got the same problem on Firefox, that is to say background color which makes the text unreadable.
![mozc3](https://user-images.githubusercontent.com/9808326/48294661-f4952b00-e485-11e8-9a1d-19f1597c3aa4.png)

I use Debian 9, and ibus-mozc and fcitx-mozcwith the version 2.19.2623.102.

Do you have any idea how I could fix that?

Thank you.

Sylve
