### ISSUE TITLE
Keyboard layout requires clearing IBus cache

### ISSUE THREAD

**Issue by danielzgtg** [google/mozc#500]
It was very frustrating debugging a caching issue with the keyboard layout today.

I upgraded two of my computers to the new Mozc with the non-root keyboard layout change. On one of them, I noticed the update before restarting, and edited the `~/.mozc/ibus_config.textproto` before shutting down, and everything worked perfectly fine the next reboot. 

On the other one, I didn't notice it until everything stopped working the next reboot. I tried editing the `~/.config/mozc/ibus_config.textproto` file, deleting `~/.mozc`, `killall ibus-engine-mozc`, `killall mozc_server`, `ibus restart`, logging out and back in but nothing worked. Then I compared the `ibus read-cache` and `read-config` outputs between the two computers. Only here did I find the problem. No matter what I did to `ibus_config.textproto`, my new keyboard layout did not show up in the cache. I had to do `ibus write-cache` to make my new keyboard layout show up there. It also needed a `ibus restart` after.

It would be less painful if Mozc updated the cache automatically, or at least documented somewhere that `ibus write-cache && ibus restart` was necessary

**Comment by hiroyuki-komatsu** [comment]
Hi Daniel,

As long as I tried, I needed to run `ibus restart` but not `ibus write-cache` on my environment. Would you please confirm it? If it still happens, I'd like to know reproducible steps.

I will add a comment that `ibus restart` is required to ibus_config.textproto. Thanks,

**Comment by danielzgtg** [comment]
I retested on both of my computers. Editing and saving the layout, then using `ibus restart` does not cause the layout to update. It still remembers whatever the layout was last time. Only by putting `ibus write-cache` before `ibus-restart` can I get the layout to update. I am using Ubuntu 21.04

**Comment by hiroyuki-komatsu** [comment]
OK. So we will note both `ibus write-cache` and `ibus restart`.

**Comment by hiroyuki-komatsu** [comment]
2d434cb added notes for `ibus write-cache` and ibus-restart`.

https://github.com/google/mozc/commit/2d434cb612b680cdc1bdaf4b036be606ef3856f0#diff-1b933fee3ee6a37169fa9f18aa382c41859d27168f55a6a2ff5055371ec60b3e 

Thanks,
