### ISSUE TITLE
Instruction to build mozc for macOS is not valid

### ISSUE THREAD

**Issue by lazylynx** [google/mozc#502]
I tried build mozc on macOS with gyp and build_mozc.py according to the [instruction](https://github.com/google/mozc/blob/master/docs/build_mozc_in_osx.md), but couldn't.

Command `python3 build_mozc.py build -c Release mac/mac.gyp:GoogleJapaneseInput mac/mac.gyp:gen_launchd_confs` raised following error.
```
Traceback (most recent call last):
  File "./gyp-mac-tool", line 722, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 30, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 45, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 178, in ExecCopyInfoPlist
    plist = plistlib.readPlistFromString(lines)
AttributeError: module 'plistlib' has no attribute 'readPlistFromString'
```

According to plistlib's docs, it doesn't have function `readPlistFromString` for Python 3.5 or above.

**Comment by hiroyuki-komatsu** [comment]
It sounds a problem of GYP, which is out of our code base.

third_party/gyp/pylib/gyp/mac_tool.py:177

By the way, I haven't had that problem even though I use Python 3.6.8 on my Mac environment. The `plistlib` on my environment neither have `readPlistFromString`.
Would you try the recent versions? (e.g. 473a26ccd17304f6c64eaac8c61090659bcdb936)


Note, `mac/mac.gyp:gen_launchd_confs` is no longer necessary. So only `mac/mac.gyp:GoogleJapaneseInput` is required.

```
ptyhon3 build_mozc.py gyp --noqt
python3 build_mozc.py build -c Release mac/mac.gyp:GoogleJapaneseInput
```

 I will remove `mac/mac.gyp:gen_launchd_confs` from the document. Thank you.

**Comment by lazylynx** [comment]
Sorry, I should have made a note of my environment.
I ran command with 473a26c on MacbookAir(Apple M1)
```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
```
```
$ python -V
Python 3.8.2
```

**Comment by hiroyuki-komatsu** [comment]
I tried the build on M1 mac too, and the build succeeded as expected.

```
% sw_vers
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
```
```
% python3 -V
Python 3.8.2
```

Command lines I used are here.
```
% GYP_DEFINES="mac_sdk=11.1 mac_deployment_target=10.9" python3 build_mozc.py gyp --noqt  
% python3 build_mozc.py build -c Release mac/mac.gyp:GoogleJapaneseInput 
```

Would you make sure to build it without any changes?

**Comment by lazylynx** [comment]
Thank you for investigation.
I succeed to build mozc with the commands you commented when using pre-installed python like `/usr/bin/python3`
And when using post-installed python, e.g. ones installed with pyenv, build failed with the same error as I commented before.

Would you use `/usr/bin/python3` when building?

**Comment by hiroyuki-komatsu** [comment]
I added the note about the path to Python3.

https://github.com/google/mozc/blob/master/docs/build_mozc_in_osx.md#path-to-python3

Thanks,

**Comment by lazylynx** [comment]
Thanks, @hiroyuki-komatsu
