### ISSUE TITLE
Can't build abseil-cpp-20200923.2 with gcc-11.1.0

### ISSUE THREAD

**Issue by utuhiro78** [google/mozc#506]
I can't build abseil-cpp-20200923.2 with gcc-11.1.0.
I tried [abseil-cpp-20210324.1](https://github.com/abseil/abseil-cpp/releases/tag/20210324.1) and I could build it, 
but I couldn't build mozc-2.26.4374.102 with abseil-cpp-20210324.1.
Maybe mozc doesn't support abseil-cpp-20210324.1.

```
FAILED: gen_usage_rewriter_dictionary_main 
/usr/bin/ld: obj.host/base/../third_party/abseil-cpp/absl/hash/internal/absl_hash_internal.hash.o: in function `absl::lts_20210324::hash_internal::HashState::CombineLargeContiguousImpl64(unsigned long, unsigned char const*, unsigned long)':
hash.cc:(.text+0x143): undefined reference to `absl::lts_20210324::hash_internal::Wyhash(void const*, unsigned long, unsigned long, unsigned long const*)'
/usr/bin/ld: hash.cc:(.text+0x185): undefined reference to `absl::lts_20210324::hash_internal::Wyhash(void const*, unsigned long, unsigned long, unsigned long const*)'
/usr/bin/ld: obj.host/base/../third_party/abseil-cpp/absl/hash/internal/absl_hash_internal.hash.o: in function `absl::lts_20210324::hash_internal::HashState::WyhashImpl(unsigned char const*, unsigned long)':
hash.cc:(.text+0x244): undefined reference to `absl::lts_20210324::hash_internal::Wyhash(void const*, unsigned long, unsigned long, unsigned long const*)'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
[668/806] CXX obj/prediction/prediction.user_history_predictor.o
ninja: build stopped: subcommand failed.
```

**Comment by utuhiro78** [comment]
I applied the patch and I could build mozc with gcc11.
https://yanqiyu.fedorapeople.org/fcitx5-mozc/fix-build-gcc11.patch
Thanks [Qiyu Yan](https://fedoraproject.org/wiki/User:Yanqiyu)!

**Comment by hiroyuki-komatsu** [comment]
Thank you for sharing the information.

It looks an issue of Abseil with gcc11.
So please let me close this issue.

When we update the Abseil version, we will keep it in mind. Thanks.

**Comment by hiroyuki-komatsu** [comment]
We updated the Abseil version to 20210324.1 (eba0e64efc6ead4fd36a95fa18fc35b5c5b2521d).

The latest commit (a7919864eb6d93f36bff1e12b3d5afb889b9c8be) requires this version (20210324.1) or later.
