### ISSUE TITLE
Hiragana input throws uncaught exception in anki "add card" window

### ISSUE THREAD

**Issue by fuzzyBSc** [google/mozc#510]
c.f https://bugs.launchpad.net/ubuntu/+source/anki/+bug/1931554
When I start typing hiragana into an "add card" window in the anki flashcard app on Ubuntu an uncaught C++ exception is thrown from mozc_engine.cc:207.

Steps to reproduce are:
1. Open anki and start adding a card to a deck
2. Type aimasu
Expected behaviour: あいます appears, and other options such as 会います are presented as a dropdown
Actual behaviour: あmasu appears ("i" is dropped), the dropdown freezes until I switch to english and back to japanese, and ubuntu records a crash of the ibus-engine-mozc process

Anki is essentially a python program using a QT widget set. I'm still not 100% sure whether the problem is fundamentically in the widget providing wrong information to the input method or whether the input method is failing on its own. I haven't found any other cases of the input method malfunctioning outside of this text entry field. This happens both with the standard ubuntu packaged version of anki and the version available for download directly from https://apps.ankiweb.net/

The code is attempting to assign the text from the end of the current selection to the end of the string to the info->following_text variable. Based on my debugging I think that the surrounding_text string is empty, but the selection region appears to be starting at 1 instead of 0. Not knowing much about how this code is supposed to work I've not been successful yet in identifying the root cause, but this used to work correctly before I upgraded recently to Ubuntu 21.04, so it seems likely that this is due to a change that has happened some time in the last 12 months either in anki, QT, or mozc.

Stack trace snippet from gdb:
10 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, void>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)Python Exception <class 'gdb.error'> value has been optimised out:
Python Exception <class 'gdb.error'> value has been optimised out:
 (__last=, __first=, this=0x7ffc45391578)
    at /usr/include/c++/10/bits/basic_string.h:1471
#11 mozc::ibus::(anonymous namespace)::GetSurroundingText(_IBusEngine*, mozc::ibus::SelectionMonitorInterface*, mozc::ibus::(anonymous namespace)::SurroundingTextInfo*) [clone .part.0] [clone .constprop.0]
    (engine=<optimised out>, selection_monitor=<optimised out>, info=0x7ffc45391530) at ../../unix/ibus/mozc_engine.cc:207
#12 0x000056510ef5e7c8 in mozc::ibus::(anonymous namespace)::GetSurroundingText
    (info=0x7ffc45391530, selection_monitor=<optimised out>, engine=0x56510fc2c410) at ../../unix/ibus/mozc_engine.cc:170
#13 mozc::ibus::MozcEngine::ProcessKeyEvent(_IBusEngine*, unsigned int, unsigned int, unsigned int)
    (this=<optimised out>, engine=<optimised out>, keyval=<optimised out>, keycode=<optimised out>, modifiers=<optimised out>)
    at ../../unix/ibus/mozc_engine.cc:377

**Comment by hiroyuki-komatsu** [comment]
Hi Benjamin,

Thank you for the repro steps and stack trace snippet. They are very helpful.

I was able to reproduce this problem.

![image](https://user-images.githubusercontent.com/11634377/123549397-cc2bdd80-d7a3-11eb-98ef-23ecd60aad4c.png)

Even if the information from apps is invalid, Mozc should not crash.
We'll fix this problem.

Thank you,

**Comment by hiroyuki-komatsu** [comment]
7654223979067e3c5ae52ea238d43880c5508f85 fixes this problem.

Thank you for reporting.
