### ISSUE TITLE
A couple of nitpicks (bundled together so as to not flood the tracker with minor issues)

### ISSUE THREAD

**Issue by Nocifer** [google/mozc#511]
1) The material icons that were recently added to the mix (as mentioned [here](https://github.com/google/mozc/issues/498#issuecomment-803286736)) are not really fit for dark themed toolbars, because they're very dark themselves. It would be best if they were remade into something more theme-agnostic, like the input mode icons currently are (which fit in both light and dark themes due to their opaque orange background).

2) In the list of includes for IBus provided in src/BUILD.ibus, the directory "lib/glib-2.0/include/**" should be added as it is used by the GLib package on Arch Linux (and possibly in other distros as well) for the glibconfig.h header.

**Comment by hiroyuki-komatsu** [comment]
Hi Alexander,
Thank you for the feedback. Please feel free to file an issue per topic. We also prefer one issue per one topic.

#### 1. font
7654223979067e3c5ae52ea238d43880c5508f85 adds variant icons under white/ and outlined/.
If they don't work, please add screenshots of your environment.

#### 2. iBus build
We only support the Docker environment, so it is probably necessary to modify some build files for other environments as you mentioned.

We updated the document with a list of files to be probably modified.
https://github.com/google/mozc/blob/master/docs/build_mozc_in_docker.md#build-mozc-on-other-linux-environment

**Comment by Nocifer** [comment]
To be honest, I didn't expect such a quick response to such minor issues so I didn't treat this as a proper "bug" report but rather as a kind of a to-do memo. My fault, I know, so I'll refrain from doing it in the future.

1. font
The new icons are usable in a dark environment, and especially the outlined ones can fit nicely with both light and dark backgrounds, so they can serve as the default. Thanks. For future reference, here's a a screenshot of how they look like on my system:
![20210707_101653](https://user-images.githubusercontent.com/6195422/124716215-7cb88080-df0c-11eb-9a5c-e07a83316ab7.png)


2. iBus build
Ah, I wasn't aware that the supported way of building Mozc is in a Docker container. OK, I understand. For the record though, the only modifications needed for building on an Arch system was the Qt path in config.bzl and the glib path in BUILD.ibus. The former was explicitly mentioned in a comment as being configured "for Debian" and thus in need of manual configuration on other systems, while the latter was not, so I thought it was an omission. The new documentation piece looks perfectly adequate.

**Comment by hiroyuki-komatsu** [comment]
2. iBus build

Thanks for the background. I added comments to BUILD.ibus and other BUILD files for third party libraries. I hope it helps too.
