### ISSUE TITLE
no symbols 

### ISSUE THREAD

**Issue by montanpi** [google/mozc#513]
I'm not getting any of the [symbol](https://raw.githubusercontent.com/google/mozc/master/src/data/symbol/symbol.tsv) candidates when typing the corresponding hiragana words with mozc.
For example when typing こめ I only get 米 as candidate, I don't get the symbol ※.
This is happening both on Arch linux (installed with sudo pacman -S [fcitx-mozc](https://github.com/google/mozc/issues/new)) and on macOS Catalina (installed with brew install --cask [google-japanese-ime](https://formulae.brew.sh/cask/google-japanese-ime)).
Supposedly it should suggest symbols without the need of any particular configuration or am I missing something?

**Comment by hiroyuki-komatsu** [comment]
Space key triggers showing more candidates including symbols.

![image](https://user-images.githubusercontent.com/11634377/125151068-71b95680-e17f-11eb-9522-4e1e148b5e2b.png)

Would you make sure whether symbols are displayed when the space key is pressed?

**Comment by montanpi** [comment]
It's working as expected by pressing space (at least 2 times)!
I was erroneously using tab instead of space. In facts I remember using tab will also show the symbols in past versions of mozc.
Thanks for pointing that out, issue can be closed.

**Comment by hiroyuki-komatsu** [comment]
Thanks for the confirmation.
