### ISSUE TITLE
Follow XDG Base Directory Specification in Linux

### ISSUE THREAD

**Issue by erlisdhima** [google/mozc#515]
It seems like mozc creates a directory in home directory ~/.mozc for adding state/data files. 

mozc should follow the [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and move these files to their specific directories.

**Comment by hiroyuki-komatsu** [comment]
Hi Erlis,

This is a duplication with https://github.com/google/mozc/issues/474
Mozc already supports XDG base directory specification since 91cc1e1. (BUILD=4206).

Thanks,

**Comment by erlisdhima** [comment]
Hi @hiroyuki-komatsu ,

Apologies! It seems Ubuntu is using an old version. I will probably try to build from source.

Thanks for your reply!
