### ISSUE TITLE
The rid of suffix.txt is not used correctly.

### ISSUE THREAD

**Issue by justoneplanet** [google/mozc#516]
Hi, thanks for the great project as always!😇
When I debug a conversion, I found a strange behavior in which lid and rid on suffix.txt is always same.

The part of writing a binary file in [src/dictionary/gen_suffix_data.py](https://github.com/google/mozc/blob/master/src/dictionary/gen_suffix_data.py#L88) should be the following to be exact, should it?

```diff
   with open(opts.output_token_array, 'wb') as f:
     for _, _, lid, rid, cost in result:
       f.write(struct.pack('<I', lid))
-      f.write(struct.pack('<I', lid))
+      f.write(struct.pack('<I', rid))
       f.write(struct.pack('<I', cost))
```

**Comment by hiroyuki-komatsu** [comment]
Hi, thank you for reporting it.

Yes, it is likely a bug.
Please let me double check it this week, then I will update it hopefully next week.

**Comment by hiroyuki-komatsu** [comment]
7e8beed3ddad4f8d1065cbab52f24c16d31f5898 fixed this issue.
Thank you for your report.
