### ISSUE TITLE
Support period separated format for rewriting date

### ISSUE THREAD

**Issue by SnO2WMaN** [google/mozc#518]
According to the test case,  mozc may support **20XX-XX-XX** and **20XX/XX/XX** for date rewriting currently. 

https://github.com/google/mozc/blob/7e8beed3ddad4f8d1065cbab52f24c16d31f5898/src/rewriter/date_rewriter_test.cc#L209-L217

How about adding period separated formatting like **20XX.XX.XX**?

**Comment by hiroyuki-komatsu** [comment]
Hi SnO2WMaN,
Thank you for your feedback.

Would you tell us how you use the period separated format (YYYY.MM.DD)?
Doesn't it work with YYYY-MM-DD or YYYY/MM/DD ?

The reasons of why we have YYYY-MM-DD and YYYY/MM/DD are:
* YYYY-MM-DD is the format of ISO 8601 standard.
* YYYY/MM/DD is the most popular format in Japan (we believe so).

Thank you,

**Comment by SnO2WMaN** [comment]
The main motivation for posting this issue is simply period-separated format would be just helpful for me personally. And I think it is also a common practice to write dates separated by periods in Japan, although it is minor.

**Comment by hiroyuki-komatsu** [comment]
Thanks. Because we have had similar requests but different formats each other, it might be worth making the format a little customizable.

I will investigate a good way when I have time.

**Comment by hiroyuki-komatsu** [comment]
a2d2b577993afb65d698f3ac936d9f13573109ef added a customizable feature.

Here's a quote from https://github.com/google/mozc/blob/master/docs/configurations.md

## Date format converted from "きょう"

This is an EXPERIMENTAL feature. This feature may be changed or removed in
future.

The conversion from "きょう" returns the current date in some formats like
"2021年10月1日" and "2021-10-01".

You can add an extra format by adding an entry of "DATA_FORMAT" to the user
dictionary.

| Reading     | Word                  | Category |
| ----------- | --------------------- | -------- |
| DATE_FORMAT | {YEAR}.{MONTH}.{DATE} | 名詞      |

Any category is OK so far.

| key     | value                |
| ------- | -------------------- |
| {YEAR}  | 4 digits year (2021) |
| {MONTH} | 2 digits month (10)  |
| {DATE}  | 2 digits date (01)   |
| {{}     | sinle { character    |

----

I'm going to close this issue next week, if it works or no issues are reported.
Thanks,

**Comment by SnO2WMaN** [comment]
Wow it sounds great to me, thanks!
