### ISSUE TITLE
Strange Conversions in 0.13.499.102: とっぷちーむ → Jong

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#52]
```
とっぷちーむ → Jong　(トップチーム)
かんせいどがたかいのでおどろいた → 
肝精度が嵩いので驚いた (完成度が高い)
あけましておめでとうございます → 
開けましておめでとうございます (明けまして)
奏しないのには　そうしない
抗しないのには　こうしない
工法にあるのが　後方

```

Original issue reported on code.google.com by `heathros...@gmail.com` on 10 Oct 2010 at 11:49

**Comment by hiroyuki-komatsu** [comment]
I added conversion test cases and the results based on reports in this issue.

https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv

We track the status of conversion results.
