### ISSUE TITLE
実在しない固有名詞が辞書に含まれている

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#527]
- 「三井住友**銀行**カード」なる事物は存在しません。三井住友カードであれば存在します（[Wikipedia](https://ja.wikipedia.org/wiki/%E4%B8%89%E4%BA%95%E4%BD%8F%E5%8F%8B%E3%82%AB%E3%83%BC%E3%83%89)）。
https://github.com/google/mozc/blob/01306d0c67c5faa203994bab281c515b9d1248fa/src/data/dictionary_oss/dictionary02.txt#L80582
修正お願いいたします。

**Comment by tomatojuicengc5195** [comment]
「満州鉄道」は削除すべきではないでしょうか。「南満州鉄道」という法人が過去に実在しましたが、満州鉄道という法人や鉄道路線は実在しません。「満州の鉄道」という一般名詞と受け取れなくもないですが、Mozcによる造語と考えます。
https://github.com/google/mozc/blob/01306d0c67c5faa203994bab281c515b9d1248fa/src/data/dictionary_oss/dictionary02.txt#L80527

**Comment by tomatojuicengc5195** [comment]
- 「東山動物」東山動物園という動物園は実在しますが、「園」を付加せずに用いる用例が確認できません。
https://github.com/google/mozc/blob/01306d0c67c5faa203994bab281c515b9d1248fa/src/data/dictionary_oss/dictionary02.txt#L79730

- 「東山動植物」こちらも同様。「東山動植物園」であれば実在します。
https://github.com/google/mozc/blob/01306d0c67c5faa203994bab281c515b9d1248fa/src/data/dictionary_oss/dictionary02.txt#L79729

**Comment by tomatojuicengc5195** [comment]
- 「ドイツ戦車」"ドイツの戦車"のように文章で言及することはあっても、このように一つの語を用いることは皆無では？造語と考えます。固有名詞(軍需産業企業の社名など)として実在しないか調査しましたが、見当たりませんでした。
https://github.com/google/mozc/blob/01306d0c67c5faa203994bab281c515b9d1248fa/src/data/dictionary_oss/dictionary02.txt#L78933

**Comment by hiroyuki-komatsu** [comment]
Hi tomatojuicengc5195,

Basically, these entries are not a problem for text input.
If the query is "ひがしやまどうぶつ", the expected result is probably "東山動物", regardless the result is an existing thing or not.

If there is an entry like "にしやま → 東山", it is a problem for text input. Then, we consider to fix it.
Thank you,
