### ISSUE TITLE
「突厥」が変換できない

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#528]
`とっけつ`→`突厥`が変換できません。
なお、`突厥文字`であれば変換できます。

**Comment by tomatojuicengc5195** [comment]
せっかくですので、
`とっくつ`→`突厥`
も変換できるようになるとなお良いかと存じます。
とっけつと比べると広く使われている読みではありませんが、デジタル大辞泉に載っています。

**Comment by hiroyuki-komatsu** [comment]
Thank you for the report.

I will update the following files to address this issue:
* [aux_dictionary.txt](https://github.com/google/mozc/blob/master/src/data/oss/aux_dictionary.tsv) 
* [quality_regression_test/oss.tsv](https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv)
* [evaluation.tsv](https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv)

**Comment by hiroyuki-komatsu** [comment]
c539217f59b5e36b6fd67ff6e185ecb18a7ff8fd added the words and test cases.
