### ISSUE TITLE
「回回」が変換できない

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#529]
`かいかい`→`回回`および`ふいふい`→`回回`が変換できません。
後者の読みは比較的近年の中国語の発音に由来すると思われますが、漢和辞典（和中・日中辞典ではない）にも掲載されており、日本語の発音として定着したものと考えます。

**Comment by hiroyuki-komatsu** [comment]
Thank you for the report.

I will update the following files to address this issue:
* [aux_dictionary.txt](https://github.com/google/mozc/blob/master/src/data/oss/aux_dictionary.tsv) 
* [quality_regression_test/oss.tsv](https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv)
* [evaluation.tsv](https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv)

**Comment by hiroyuki-komatsu** [comment]
c539217f59b5e36b6fd67ff6e185ecb18a7ff8fd added the words and the test cases.
