### ISSUE TITLE
今の Mozc も LibChewing をサポートしていますか。

### ISSUE THREAD

**Issue by ShikiSuen** [google/mozc#530]
今の Mozc のコード倉庫を見て src/chewing/unix/ibus/mozc-chewing.xml は無くなりました。
Mozc にあんまり詳しくありませんので、ここでお尋ねに来ました。
よろしくお願い致します。

**Comment by hiroyuki-komatsu** [comment]
Hi ShikiSuen,

The current Mozc doesn't support LibChewing.
Thank you,

今の Mozc は LibChewing をサポートしていません。
よろしくお願いします。

**Comment by ShikiSuen** [comment]
@hiroyuki-komatsu お返事ありがとうございます。
この事実を知って少し残念な気分。
これからも 日本語入力としての Mozc お頑張りください。
