### ISSUE TITLE
"れいわがんねん" is converted to "0話元年"

### ISSUE THREAD

**Issue by utuhiro78** [google/mozc#531]
dictionary0*.txt doesn't have "令和", so "れいわがんねん" is converted to "0話元年".
(Correct: 令和元年)

```
# Install ripgrep first.
cd src/data/dictionary_oss
rg 令和

# dictionary04.txt
# 20225:かわぎしのりかず	1837	1837	9538	川岸令和
```

**Comment by hiroyuki-komatsu** [comment]
Thank you for the report.

I will update the following files to address this issue:
* [aux_dictionary.txt](https://github.com/google/mozc/blob/master/src/data/oss/aux_dictionary.tsv) 
* [quality_regression_test/oss.tsv](https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv)
* [evaluation.tsv](https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv)

**Comment by hiroyuki-komatsu** [comment]
c539217f59b5e36b6fd67ff6e185ecb18a7ff8fd added the word and the test case.
