### ISSUE TITLE
ユーザー辞書の「動詞ザ変」について

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#534]
一般的には、濁ったサ行変格活用のことをザ行変格活用とは言いません。濁ろうが(例: 焙ずる)、濁らなかろうが(例: 愛する)、サ行変格活用といいます。
ユーザー辞書の「動詞ザ変」というのは言語学的におかしな言葉遣いなので、「動詞サ変濁音(仮称)」といった適切な名称に改めるべきです。

**Comment by tomatojuicengc5195** [comment]
追記
仮称は一例に過ぎないので、もっと適切な名称があればコメントください。

**Comment by hiroyuki-komatsu** [comment]
Thank you for the feedback.

We understand the point, however we don't have a plan to change it for the following reasons:

* Backward compatibility
* It seems there is no standard word to represent it

Thank you,

**Comment by tomatojuicengc5195** [comment]
いくら標準的な言葉がないからといって、英語を公用語とする企業が日本語のIMEにおいて造語を使うのは文化に対する侵略ではないでしょうか？日本語学に対して経緯を払うべきです。

**Comment by tomatojuicengc5195** [comment]
「動詞サ変濁音」というのは、「濁音のサ行変格活用の動詞」という文章をMozcの先例に習ってそれっぽく一語にしたものであり、造語とは考えておりません。文化に対する敬意という観点からは、ザ変よりかはマシな表現でしょう。
