### ISSUE TITLE
要望: CJK互換漢字を候補に表示しないモードが欲しい

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#541]
CJK互換漢字を含む語を候補に一切表示しないモードが欲しいです。
具体的には下記のどちらかです。

- 案1: CJK互換漢字を含む語を候補から排除するだけ(候補一覧に表示される語は減る)
- 案2: CJK互換漢字を含む語を、CJK統合漢字+異体字セレクタに置き換える(候補一覧に表示される語の数は減らない)

----
これに関連して質問なのですが、現在のMozcの方針として、異体字セレクタの扱いはどうなっているのでしょうか。「異体字セレクタはシステム辞書に含めない」といった方針は存在するのでしょうか。

**Comment by hiroyuki-komatsu** [comment]
As long as I checked, '﨑' (U+FA11) is the only character of CJK Compatibility Ideographs (CJK互換漢字) in the dictionary.
There is no corresponsing variation sequece for '﨑'.

* https://www.unicode.org/Public/UCD/latest/ucd/StandardizedVariants.txt

So, we don't have either of CJK Compatibility Ideographs or variation sequences at this moment.
When we introduce those characters, we will also consider this point. Thanks,

**Comment by hiroyuki-komatsu** [comment]
I close this issue, as there is no actual problem at this moment. 
Thanks,
