### ISSUE TITLE
mozc is giving errors of Android NDK when building with bazel 5.0

### ISSUE THREAD

**Issue by silverhikari** [google/mozc#544]
after running "bazel build package --config oss_linux -c opt" the error

`mozc-ut-united/src/mozc/src/WORKSPACE.bazel:12:23: fetching android_ndk_repository rule //external:androidndk: java.io.IOException: Expected directory at /opt/android-ndk/platforms but it is not a directory or it does not exist. Unable to read the Android NDK at /opt/android-ndk, the path may be invalid. Is the path in android_ndk_repository() or ANDROID_NDK_HOME set correctly? If the path is correct, the contents in the Android NDK directory may have been modified.`

which should not be happening as this is being build and run on linux, so i do not know why is trying to build android

**Comment by hiroyuki-komatsu** [comment]
Hi Ethan,

Please try either of:

* install Android NDK
* comment out the setting for Android NDK in WORKSPACE.bazel

```
# Android NDK version should be r11c+ for Abseil.
# This rule reffers $ANDROID_NDK_HOME
# android_ndk_repository(name = "androidndk")  # ← here
```

Did it work with the previous Bazel versions before Bazel 5.0?

**Comment by silverhikari** [comment]
yes, the last version tested that built successfully was 4.2.2

**Comment by hiroyuki-komatsu** [comment]
Here is the discussion in the Bazel project.

https://github.com/bazelbuild/bazel/issues/14260

**Comment by hiroyuki-komatsu** [comment]
[e05888b](https://github.com/google/mozc/commit/e05888b1e46cbdb340ee5582cb8f871e04650ff5) is a workaround of this issue.

If ANDROID_NDK_HOME env var is not specified, Android NDK is not initialized.
Then this error doesn't happen.

Thanks,
