### ISSUE TITLE
Qt candidate window: Candidate window blinks by a key type

### ISSUE THREAD

**Issue by ftake** [google/mozc#548]
The current implementation seems to hide/show its candidate window every key type. Especially when window show/hide animation is enabled by a desktop environment, this hide/show is slow, and the window blinks.

I'm not sure there is suitable Qt flags to disable this type of animation.

**Comment by ftake** [comment]
Under KDE Plasma 5, the animation is enabled by default if graphic acceleration is available. You can configure it by using KDE System Setting > Workspace Behavior

- Desktop Effects
![Screenshot_20220213_213707](https://user-images.githubusercontent.com/160235/153753630-5c237470-582b-4e2d-828a-c7cee1a091b5.png)

- General Behavior (for animation speed)
![Screenshot_20220213_213326](https://user-images.githubusercontent.com/160235/153753236-9dce60cd-d980-4de7-9132-6f2b9fd488d8.png)


It seems that window animation is not applied to the candidate window under GNOME environment (which also have window show/hide animation). I will test with other desktop environments.

**Comment by hiroyuki-komatsu** [comment]
Thank you for the instruction.
I was able to reproduce this issue on my KDE Plasma.

I'm investigating the issue.

**Comment by hiroyuki-komatsu** [comment]
I performed the whole refactoring. 

7d0959e1d27fc79c2e8cef88431f460eae3b31aa fixed this issue on my environment.

Feel free to reopen this issue, if the problem is not fixed yet on your environment.
Thanks for your report.
