### ISSUE TITLE
The server tries to create a directory for abstract socket of Unix IPC

### ISSUE THREAD

**Issue by akihikodaki** [google/mozc#551]
A possible fix: https://github.com/akihikodaki/mozc/tree/check-the-server-address-before-using-it-as-a-path

**Comment by hiroyuki-komatsu** [comment]
Hi Akihiko,

Thank you for your report.
To understand the issue correctly, would you please describe the following items for the issue?

* What the expected behavior is.
* What the current actual behavior is.
* Steps to reproduce the current actual behavior.

Thank you,

**Comment by akihikodaki** [comment]
> Hi Akihiko,
> 
> Thank you for your report. To understand the issue correctly, would you please describe the following items for the issue?
> 
>     * What the expected behavior is.

It does not try to call `mkdir` with an abstract socket address.

> 
>     * What the current actual behavior is.

It calls `mkdir` with an abstract socket address.

> 
>     * Steps to reproduce the current actual behavior.

Use ibus_mozc and inspect `.mozc/mozc_server.log` to find it says `ipc/unix_ipc.cc(365) LOG(ERROR) NOT_FOUND: mkdir failed: errno=2: Cannot create \0tmp`.

> 
> 
> Thank you,

**Comment by hiroyuki-komatsu** [comment]
Let me take time to understand it and make a change.

**Comment by hiroyuki-komatsu** [comment]
[1b95057](https://github.com/google/mozc/commit/1b950579e8a422ef3aaaa1e183db330a448f18e5) fixed it.
Thank you,
