### ISSUE TITLE
ON and OFF keys are not supported on Unix/IBus

### ISSUE THREAD

**Issue by akihikodaki** [google/mozc#552]
A possible fix: https://github.com/akihikodaki/mozc/commit/f56693f5da2f0f0014e048696045b53923fd6a96

**Comment by hiroyuki-komatsu** [comment]
Hi Akihiko,

Thank you for your report.
To understand the issue correctly, would you please describe the following items for the issue?

* What the expected behavior is.
* What the current actual behavior is.
* Steps to reproduce the current actual behavior.

Thank you,

**Comment by akihikodaki** [comment]
^ 

> Hi Akihiko,
> 
> Thank you for your report. To understand the issue correctly, would you please describe the following items for the issue?
> 
>     * What the expected behavior is.

- ON and OFF keys can be set in key binding editor and they can be used to e.g. toggle the conversion state.

> 
>     * What the current actual behavior is.

- Mozc does not respond to ON and OFF keys.

> 
>     * Steps to reproduce the current actual behavior.

1. Start ibus_mozc.
2. Press ON key to find it does not enable conversion. The ON key is present on Macs, some of Microsoft Surfaces and other keyboards.

> 
> 
> Thank you,

**Comment by hiroyuki-komatsu** [comment]
Let me take time to understand it and make a change.

**Comment by hiroyuki-komatsu** [comment]
Here's my understanding of this issue.

Word definitions
* ON key: Kana key on the macOS keyboard. keycode=130, HID usage=LANG1
* OFF key: Eisu key on the macOS keyboard. keycode=131, HID usage=LANG2

Problem on your environment
* ON key and OFF key on the macOS keyboard do not work.
* ON key is recognized as Hangul, and OFF key is recognized as Hangul_Hanja.


If I understand correctly, I think this is a configuration issue of the keyboard.

Looking at some XKB configuration files (e.g. /usr/share/X11/xkb/symbols in Debian),
expected settings could be configured as follows:

```shell
xmodmap -e "keycode 130 = Hiragana_Katakana"
xmodmap -e "keycode 131 = Eisu_toggle"
```

----

Having said that, there are two related issues:
* Mozc does not recognize Hangul and Hanja keys.
* XKB configuration recognizes both keycode 130 (Kana key on macOS) and keycode keycode 208 (Hiragana/Katakana key) as Hiragana_Katakana.

Enabling Mozc to recognize more keys might be a good thing. I will consider it.

XKB configuration is out of focus of this project, but it would be great if it has new keysyms for Ime_on and Ime_off for keycodes 130 and 131.

Thanks,

**Comment by akihikodaki** [comment]
@hiroyuki-komatsu 

> Looking at some XKB configuration files (e.g. /usr/share/X11/xkb/symbols in Debian),
> expected settings could be configured as follows:
>
> ```
> xmodmap -e "keycode 130 = Hiragana_Katakana"
> xmodmap -e "keycode 131 = Eisu_toggle"
> ```

`Hiragana_Katakana` key and `Eisu_toggle` are not semantically equivalent with ON and OFF keys albeit the similarities of their names. As such, it requires handling distinct from those keys everywhere including Mozc. USB HID specification and Mozc are prepared for that by preparing distinct key codes. (Mozc actually already have those key codes for macOS and Windows.)

First, we need to understand there is two distinct states: IME ON/OFF state and input character type. IME ON/OFF state represents whether IME should transform the input. The input character type determines what characters should input: hiragana, katakana, or Latin.

`Hiragana_Katakana` and `Eisu_toggle` are to change input character type.

`Hiragana_Katakana` is used to choose hiragana or katakana as input character type. It is mapped to `commands::KeyEvent::KANA` or `commands::KeyEvent::KATAKANA`, depending on the shift state.

`Eisu_toggle`  is used to choose latin as input character type. Note that IME can be still active even when inputting Latin characters e.g. to use its dictionary.

ON and OFF keys are, on the other hand, used to toggle IME ON/OFF state. It is much more similar to `Hankaku_Zenkaku` than `Hiragana_Katakana` and `Eisu_toggle`. The difference with `Hankaku_Zenkaku` is that they do not depend on the current IME ON/OFF state and always makes the state `ON` or `OFF` while `Hankaku_Zenkaku` negates the state. They are corresponding to `commands::KeyEvent::ON` and `commands::KeyEvent::OFF`.

> XKB configuration recognizes both keycode 130 (Kana key on macOS) and keycode keycode 208 (Hiragana/Katakana key) as Hiragana_Katakana.

You meant keycode 131 instead of keycode 208? Anyway, it is not quite a true. Keycode 130 and 131 are mapped to `HNGL` and `HJCV`, respectively:
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/72a596dff3405ba9410d81044928400c323a7e83/keycodes/evdev#L160-163
```
	// Keys that are generated on Korean keyboards

	<HNGL> = 130;	// Hangul Latin toggle
	<HJCV> = 131;	// Hangul to Hanja conversion
```

`HNGL` and `HJCV` generates `Hangul` and `Hangul_Hanja`, respectively:
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/72a596dff3405ba9410d81044928400c323a7e83/symbols/inet#L113-114
```
    key <HNGL>   {      [ Hangul                ]       };
    key <HJCV>   {      [ Hangul_Hanja          ]       };
```

**Comment by hiroyuki-komatsu** [comment]
Here are the files of why I thought Eisu_toggle and Hiragana_Katakana are mapped for Eisu and Kana keys on macOS.  

* https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/72a596dff3405ba9410d81044928400c323a7e83/keycodes/xfree86#L153-154

```
    <EISU> =   210;		// Alphanumeric mode on macintosh
    <KANA> =   209;		// Kana mode on macintosh
```

* https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/72a596dff3405ba9410d81044928400c323a7e83/symbols/jp#L87-95

```
   key <EISU> {
	type[Group1]="PC_ALT_LEVEL2",
	symbols[Group1]= [ Eisu_toggle ]
    };

    key <KANA> {
	type[Group1]="PC_ALT_LEVEL2",
	symbols[Group1]= [ Hiragana_Katakana ]
    };
```

The keycodes are 209 and 210, but not 130 and 131. So the first point is the gap between the keycodes (209, 210 vs 130, 131).


I agree it is not an ideal mapping. Hiragana_Katakana is also mapped to `<HKTG>` (keycode 208, Hiragana Katakana toggle key).
* https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/72a596dff3405ba9410d81044928400c323a7e83/symbols/jp#L82-85
* https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/72a596dff3405ba9410d81044928400c323a7e83/keycodes/xfree86#L148

As you mentioned, `<HKTG>` is usually used to change the input character type, and `<KANA>` is usually used to turn ON the IME.

So, I mentioned the following as an issue. (correctly speaking the keycode 130 should be 209).
> * XKB configuration recognizes both keycode 130 (Kana key on macOS) and keycode keycode 208 (Hiragana/Katakana key) as Hiragana_Katakana.

Thus, the second point is the lack of keysyms for Ime_on and Ime_off on the Linux environment. On Windows, they introduced two new virtual keycodes for those keys (VK_IME_ON and OFF).
* https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/keyboard-japan-ime

If the Linux environment has distinguishable keycodes for Ime_on and Ime_off like Windows, Mozc would apply them.



Anyway, I'm considering supporting Hangul and Hanja as customizable keys beside ON/OFF keys.

**Comment by akihikodaki** [comment]
@hiroyuki-komatsu
> The keycodes are 209 and 210, but not 130 and 131. So the first point is the gap between the keycodes (209, 210 vs 130, 131).

I guess 209 and 210 actually represent `Eisu_toggle` and `Hiragana_Katakana`. The key codes were added in 2006 so we have to look for an old Mac keyboard to understand the intention. I found a picture of an old Mac keyboard which has "カナ/かな" key instead of "かな" as you can find in a recent keyboard:
https://item.rakuten.co.jp/auc-puran/wp1824/?scid=af_pc_etc&sc2id=af_113_0_10001868&iasid=wem_icbs_&icm_agid=135083843412&gclid=CjwKCAjwoduRBhA4EiwACL5RPygueCJk_lI-YvXXrJw2aCjJabVVPa1GSHH9N-6ZZH138b3y7xhG4xoCXlMQAvD_BwE&icm_cid=15280804517&icm_acid=255-776-8501

In this sense, the mappings are probably right. The keys represented by code 209 and 210 are simply different from ones represented by 130 and 131.

> If the Linux environment has distinguishable keycodes for Ime_on and Ime_off like Windows, Mozc would apply them.

What is motivation for distinguishable key codes? In fact, macOS shares key codes for those keys.
https://gitlab.com/qemu-project/keycodemapdb/-/commit/8e54850d800e4697a2798fb82ac740e760f8530b
I don't think anything prevents from following the convention of respective platforms (i.e. use distinguishable codes on Windows and use the unified codes on macOS and systems with XKB.)

**Comment by hiroyuki-komatsu** [comment]
> I guess 209 and 210 actually represent Eisu_toggle and Hiragana_Katakana. The key codes were added in 2006 so we have to look for an old Mac keyboard to understand the intention. I found a picture of an old Mac keyboard which has "カナ/かな" key instead of "かな" as you can find in a recent keyboard:

If I remember correctly, the keys on the sides of the spacebar are always ImeON and ImeOFF on macOS. So the usage on macOS has not been changed.

The following page was written in 2002. It says HID usage IDs of "カナ/かな" and "英数" are 0x90 and 0x91. They are the same numbers as the current ones.

http://www2d.biglobe.ne.jp/~msyk/keyboard/layout/usbkeycode.html

So I think `<EISU>` and `<KANA>` were introduced as macOS's ImeOn and ImeOFF keys.


> I don't think anything prevents from following the convention of respective platforms (i.e. use distinguishable codes on Windows and use the unified codes on macOS and systems with XKB.)

That is the point. Indeed, I'm wondering what the official convention with XKB is. I'm still not sure if Hangul_hanja and Hangul are official keysyms for ImeON and ImeOFF, or if it's the behavior of the current implementation, since I think `<EISU>` and `<KANA>` are keys for ImeOn and ImeOff on macOS.

**Comment by akihikodaki** [comment]
> The following page was written in 2002. It says HID usage IDs of "カナ/かな" and "英数" are 0x90 and 0x91. They are the same numbers as the current ones.
> 
> http://www2d.biglobe.ne.jp/~msyk/keyboard/layout/usbkeycode.html
> 
> So I think `<EISU>` and `<KANA>` were introduced as macOS's ImeOn and ImeOFF keys.

That makes sense. I also found some code of xf86-input-keyboard refers to USB HID usage Lang1 and Lang2.

> > I don't think anything prevents from following the convention of respective platforms (i.e. use distinguishable codes on Windows and use the unified codes on macOS and systems with XKB.)
> 
> That is the point. Indeed, I'm wondering what the official convention with XKB is. I'm still not sure if Hangul_hanja and Hangul are official keysyms for ImeON and ImeOFF, or if it's the behavior of the current implementation, since I think `<EISU>` and `<KANA>` are keys for ImeOn and ImeOff on macOS.

I opened a merge request to unify with `HNGL` and `HJCV`. It also has an extensive explanation of the situation.
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/311
Let's see how it goes first...

**Comment by akihikodaki** [comment]
@hiroyuki-komatsu xkeyboard-config-2.36 is released, and now Lang1/Lang2 keycodes are unified to `HNGL` and `HJCV`.
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/tags/xkeyboard-config-2.36

That, however, made Mozc unable to detect the keys.
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/326

Can you make the suggested change to fix the key detection and make` IME_On` and `IME_Off` work by default on X.org/Wayland?

**Comment by hiroyuki-komatsu** [comment]
Acknowledged. I will work on it.
Thanks for confirming the specs.

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/80bc73f06dcd4e1a52a03f46c2ae308f3e1bddb6 is the change.
If it doesn't work, please feel free to reopen this issue or make a new issue.

Thank you,

**Comment by oech3** [comment]
I tried  register ON and OFF keys at mozc 2.28.5105.102-1.
But It was ignored at end of keymap editor (see screenshot).
![mozcONOFF](https://github.com/google/mozc/assets/79379754/59b093b4-a37e-4b6a-8afd-fc7ad009182f)

Sorry for lating to report (due to delaying of update of repository).

**Comment by hiroyuki-komatsu** [comment]
Hi oech3,

Since ON and OFF are predefined, you don't need to redefine them.

**Comment by oech3** [comment]
@hiroyuki-komatsu Do you mean that I can enable IME by `ON` without registering `ON` as `IMEOn`?
I can't do it. And I can't see that `On` is already registered at my keymap.

**Comment by hiroyuki-komatsu** [comment]
> Do you mean that I can enable IME by ON without registering ON as IMEOn?

Yes.

ON/OFF keys are predefined, and not configurable. So they are invisible from the GUI.
However, it should work without any configurations.

Would you try some predefined keymaps (e.g. MS-IME, Kotoeri, ATOK) to make sure if ON/OFF key works?

**Comment by oech3** [comment]
`ON/OFF` not worked with `MS-IME, Kotoeri, ATOK`.
I'm using mozc with `fcitx5 5.0.23`.

**Comment by hiroyuki-komatsu** [comment]
I see. Then, that's a behavior of Fcitx.
I'd suggest you to file a feature request to the Fcitx project.

Thank you,
