### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by shitamo** [google/mozc#554]
I hope switch to Github Actions
example:
https://github.com/shitamo/mozc/commit/43f9dcfa9231fee05606f6ce5fc9b145f70619f5

**Comment by hiroyuki-komatsu** [comment]
Thank you for the suggestion.

I try to make time to update CIs.

**Comment by shitamo** [comment]
Thanks, you be able to close related issues.
https://github.com/google/mozc/pull/482
https://github.com/google/mozc/issues/446

**Comment by hiroyuki-komatsu** [comment]
Thank you for your suggestion about CIs.

"CI for macOS" is currently failing, but we already have a fix.
It will be applied soon.

**Comment by shitamo** [comment]
https://github.com/shitamo/mozc/commit/cb396995b48ec521410a8fb91b1b76ec05ab2ef3
It seems that relative links can be used

**Comment by shitamo** [comment]
https://github.com/shitamo/mozc/commit/1a52621e072c2a61e9b4c2b471a8a82823ab6951
Requires apt-get update

**Comment by hiroyuki-komatsu** [comment]
97caef3 fixed it.
Thank you!
