### ISSUE TITLE
「役立たず」が変換できない

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#559]
`やくたたず`と入力して変換すると`約立たず`となります。
`役立たず`と変換されるようにできないものでしょうか。

**Comment by hiroyuki-komatsu** [comment]
Thank you for the report.

I confirmed this issue with the build 4666.
I will try to make time to address it.

Because I am busy this month, my responses for the issues including this one might be slow.
Thank you,

**Comment by hiroyuki-komatsu** [comment]
[f123b3f](https://github.com/google/mozc/commit/f123b3f3729564c172c694f1d3a7dba5ab542286) added the test case and [e8ea65d](https://github.com/google/mozc/commit/e8ea65d327a9d04822123ce5b353ccd645678156) fixed it.

Thanks,
