### ISSUE TITLE
Mozc icon is jaggy

### ISSUE THREAD

**Issue by goreboothero** [google/mozc#560]
Compared to other applications, only the mozc icons are low-resolution and look old.
I would be very happy if you could remove the jaggies.

I know this is a minor point, but I would appreciate your consideration 🙏.

If you give me a high-resolution SVG, I will create the image.

The screenshot is Ubuntu 20.04 (GNOME3.X).

![Screenshot from 2022-03-14 22-56-12](https://user-images.githubusercontent.com/42995313/158190476-d361de25-833e-4a4a-927c-c8e7da86dc1e.png)

**Comment by hiroyuki-komatsu** [comment]
Hi, thank you for letting us know that.

We apparently forgot adding the SVG product icon, when we added other SVG icons.
* https://github.com/google/mozc/issues/498

We will add the SVG product icon too.
Thanks,

**Comment by hiroyuki-komatsu** [comment]
61dd343 added the product icon in SVG.

`bazel build unix:icons --config linux` now generates a zip file of icons with the SVG product icon.
Thank you,
