### ISSUE TITLE
辞書登録の読みに小書きゐ・ゑが使用できない

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#561]
`ぐ𛅑つ`→`月`と変換されるように辞書登録がしたいのですが、よみ欄に𛅑（小書きゑ、 U+1B151）が含まれると追加できません。𛅐（小書きゐ、U+1B150）でも同様の問題が発生します。

字音仮名遣表記の合拗音の辞書登録に支障をきたすため修正いただけますと幸いです。

**Comment by tomatojuicengc5195** [comment]
余談ではありますが、ローマ字変換テーブルに小書きゐ・ゑを使用することは可能です。

**Comment by hiroyuki-komatsu** [comment]
Hi, thank you for the feedback.
I confirmed this problem.

At first, we need to make sure the background of this limitation, whether it comes from some technical limitations or design decision.

I will try to make time for the investigation the background.

**Comment by hiroyuki-komatsu** [comment]
[4eba2e8](https://github.com/google/mozc/commit/4eba2e818ef3cc6034bada14761de95d40104e57) will accept any valid UTF-8 characters as key. The GUI tool still shows warning about the character form, but it can be dismissed.

Thanks,
