### ISSUE TITLE
GYP build will stop supporting IBus client.

### ISSUE THREAD

**Issue by hiroyuki-komatsu** [google/mozc#567]
We are going to have following changes

* Gtk2 based candidate window for IBus will be removed.
  + Qt based candidate window is the alternative.
* GYP build will stop supporting the build of IBus client.
  + Bazel build is the alternative. 
* Then, pull requests for IBus client and Qt based candidate window will be acceptable.
 
We need to stop supporting GYP build to accept pull requests because of the limitation of the upstream.
We believe accepting pull requests is more beneficial than keeping the GYP build under the maintenance mode.

We will start this change on 2022-05 at the earliest.

**Comment by stalkerg** [comment]
Sorry, but Bazel it's pain in the ass for Linux distro maintainers and source-based distro users. Just to build a C++ project for i18n we should somehow install JVM and Bazel - it's very heavy requirements. 
We should consider adding Meson build and add fcitx5 support. 
I know - Google can do what they want, but this is what is needed for the community. 
Google is not too poor a company to not support the whole Linux ecosystem in the right way. 
Can we start any negotiations about that?

**Comment by hiroyuki-komatsu** [comment]
Hi, thank you for the feedback.

Because GYP is not updated well, we need to make patches to keep supporting builds of Mozc.
Bazel is the default tool used by the upstream of the Mozc project and the number of people keep improving Bazel as full time commitments. Bazel improves our productivity.

So we would like you to encourage us to focus our engineering resource on the core functionalities of Japanese input rather than build systems.

Thank you,

**Comment by stalkerg** [comment]
> Because GYP is not updated well, we need to make patches to keep supporting builds of Mozc.

yes, GYP is outdated but on Linux desktop, Meson and CMake are dominated now and very easily integrated. 

> Bazel is the default tool used by the upstream 

I suppose it's a mistake. 

> So we would like you to encourage us to focus our engineering resource on the core functionalities of Japanese input rather than build systems.

because of this, I can't use mozc at all!!!! Please, read my original message again, I asked and point to a completely different issue.

**Comment by akihikodaki** [comment]
In my opinion, having a JDK dependency at build time can be tolerated. It is understandable that the upstream uses the best tool for core productivity. As far as I know, having JDK as a build time dependency is not a problem for APT or RPM packages anyway. 

However, I have another concern: `src/config.bzl` has hardcoded configurations. Particularly, Fedora places Qt to a different path. I have just skimmed the code and Bazel documentation but it looks like there is no straightforward method to make it configurable.

I wonder GN could be an alternative build method. I have used it for ANGLE, Chromium and WebRTC distribution and it seems to have sufficient configurability. It is not widely adopted by Linux distributions and that may be unfavorable though.

**Comment by hiroyuki-komatsu** [comment]
Thank you for the comments.

Bazel is Google's (i.e. upstream's) default build system for all projects under the internal code repository. Mozc is one of them. So Mozc should be built with Bazel. Here is one of the reasons why we use Bazel as the build system.
(Note, Chromium is in another code repository).

> However, I have another concern: src/config.bzl has hardcoded configurations. Particularly, Fedora places Qt to a different path. I have just skimmed the code and Bazel documentation but it looks like there is no straightforward method to make it configurable.

IIUC, in theory, it is possible to use the command line flag or environment variables to modify variables.
However the implementation might not be so simple.
(You can generate a .bzl file with user specified values in WORKSPACE.bazel and replace config.bzl with that .bzl file).

I hope patching `src/config.bzl` is a reasonable solution for development and packaging.

If you need to modify hardcoded variables in other files, please let us know.
Thank you,

**Comment by akihikodaki** [comment]
Then I propose two changes to generate `src/config.bzl`:
- Add it to `.gitignore`.
  It would be hard to use Git features without this change.
- Add a script like `src/build_mozc.py` to generate `src/config.bzl`.
  Ideally this should handle e.g. escaping strings.

With these changes, Bazel would be feature-parity with GYP.

Besides the configuration problem, I found Bazel cannot be used for non-x86_64 platforms due to the dependency on Android NDK.

**Comment by hiroyuki-komatsu** [comment]
For Git, the following command treats `src/config.bzl` unchanged. I hope it works.

```
git update-index --assume-unchanged src/config.bzl
```
* https://stackoverflow.com/questions/655243/ignore-modified-but-not-committed-files-in-git

For Android NDK, https://github.com/google/mozc/issues/544 is about this issue.

**Comment by stalkerg** [comment]
>  I found Bazel cannot be used for non-x86_64 platforms due to the dependency on Android NDK.

is it means I can't build mozc for Raspberry Pi or any RISC-V/OpenPower desktop? This is a huge limitation. 

> In my opinion, having a JDK dependency at build time can be tolerated.

I am a Gentoo user and for us, it's not tolerated because it means JDK dependencies for users. I don't want to have JDK build mozc which usually has 0 sense for Linux desktops. 

> Bazel is Google's (i.e. upstream's) default build system for all projects under the internal code repository. Mozc is one of them. So Mozc should be built with Bazel. Here is one of the reasons why we use Bazel as the build system.

yes, it's understandable but I asked to change it because it's inconvenient for people who use it outside Google. Basically, if I will made PR is it will be accepted?

**Comment by akihikodaki** [comment]
> For Git, the following command treats `src/config.bzl` unchanged. I hope it works.
> 
> ```
> git update-index --assume-unchanged src/config.bzl
> ```

Thanks, that would help. It is still better if you don't have to type it after cloning the repository each time though.

> 
>     * https://stackoverflow.com/questions/655243/ignore-modified-but-not-committed-files-in-git
> 
> 
> For Android NDK, #544 is about this issue.

Good to know Bazel maintainers are aware of the problem at least.

By the way, I checked if modifying `src/config.bzl` would be enough, but apparently it is not. `BUILD.gtk2.bazel` and `BUILD.ibus.bazel` hardcodes references to `lib/x86_64-linux-gnu`, which do not exist on Fedora and non-x86_64 systems. The files also mention that they are based on the outputs of pkg-config on Ubuntu 20.04.

It would be nice if it has a script to generate them as well.

**Comment by stalkerg** [comment]
> It would be nice if it has a script to generate them as well.

if you need an extra script to generate configs for the build system I suppose such a system is failed. Meson or CMake will be much better. 
I hope I will have enough time to make the Meson version.

**Comment by hiroyuki-komatsu** [comment]
I added several changes to Bazel:

* 48a99e7 adds comments for tips of Git to ignore the changes of `src/config.bzl`.
* e05888b addresses the Android NDK issue.
* ea23a38 uses pkg-config for Gtk2 and IBus instead of the manual BUILD.bazel files.
* 0a595ee uses pkg-config for Qt instead of the manual BUILD.bazel file.
* 5dbde5e is a change for Qt for macOS to align with the above changes.

Thanks,

**Comment by hiroyuki-komatsu** [comment]
* 1063358361f81b333dbe6bc7a3634524198f5594 updated the document. 
* f133df0fd92c82945259bb588ea227d6738b1d06 added src/unix/ibus/ as one of directories we accept PRs.

If you have technical problems with Bazel, please feel free to file new issues or discussions.
Thank you,
