### ISSUE TITLE
「深圳」が変換できない

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#568]
`しんせん`→`深圳`が変換できません。

「圳」の日本語としての本来の読み方には諸説あり、シュウだとかシュンだとかシンといったものがありますが、マスコミにおける用例を見る限り、少なくとも地名の「深圳」の読み方は「しんせん」で定着しているものと考えます。

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/847cae7326783e7fdc8154ef4db5331d90a90a7f addressed it.

Thanks,
