### ISSUE TITLE
Mozc randomly stopped accepting romaji input

### ISSUE THREAD

**Issue by MikeTango** [google/mozc#569]
Hi,
i am using mozc/ibus on two machines. On both i can't use direct input anymore. When tabbing to a text field, the IME icon flickers to the red mozc icon for a second and then reverts to A. clicking on hiragana input, it then uses romaji as the input method as if using direct. 

please advise.

**Comment by hiroyuki-komatsu** [comment]
Hi,

To understand the issue correctly, would you provide a video of the behavior?
If it's difficult to create a video, a series of screenshots is also helpful.

Thanks,

**Comment by hiroyuki-komatsu** [comment]
Please let me close this issue until receiving additional information.
Please feel free to reopen it with them.

Thank you,
