### ISSUE TITLE
ハ行四段活用の動詞の連用形促音便が変換できない

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#571]
以下の内容で辞書登録をしました。

- よみ: うた
- 単語: 𧦅
- 品詞: 動詞ハ行四段

`うたふ`→`𧦅ふ`は変換できます。しかし、`うたった`→`𧦅った`は候補に現れません。バグと思われます。

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/200dbdae42db37b57d17116082485f68ccd93b35 supports つ and っ as conjugations of 動詞ハ行四段.

Thanks,
