### ISSUE TITLE
「空焚き」が変換できない

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#574]
`からだき`で`空焚き`が変換できません。辞書追加お願いします。

Googleの検索結果によると、「空炊き」という異表記も存在するようですが、『デジタル大辞泉』『広辞苑 第六版』のいずれにも掲載されておらず、「[Aozorasearch](https://myokoym.net/aozorasearch/)」でもヒットしないことからこちらの提案は見送ります。

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/f2a0b3e5d4885fa038cb5643ed143900de165461 added the entry and test.
Thanks,
