### ISSUE TITLE
誤表記の可能性が高い語「惚気け」「惚気ける」が候補に表示される

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#580]
`のろけ`と入力してスペースバーを押すと`惚気け`が候補に現れます。
同様に、`のろける`で`惚気ける`も現れます。
しかし、この語は誤表記ではないでしょうか。正しい表記は「惚気」「惚気る」かと思いますが、いかがでしょうか。

『デジタル大辞泉』『広辞苑 第六版』(978-4-00-080121-8)『岩波国語辞典 第三版』には、「惚気(名詞)」「惚気る(動詞)」のいずれも掲載されていますが、「惚気け」「惚気ける」といった表記の記載はありません。
また、[Aozorasearch](https://myokoym.net/aozorasearch/)でも、「惚気」は73件ヒットしますが、「惚気け」は1件もヒットしません。

辞書から削除するか、もしくは「『もしかして』変換」へ移す必要があるかと思います。

**Comment by hiroyuki-komatsu** [comment]
[20006e8](https://github.com/google/mozc/commit/20006e85514336c255bbebe39fbb0934db9c99e6) removed the entries of "惚気け(る)".

Note, this change is only applied to the Bazel build, but not the GYP build.

Thank you,
