### ISSUE TITLE
[Feature request] GODAN input with Kana instead of Romaji on the Keys

### ISSUE THREAD

**Issue by FrostKiwi** [google/mozc#581]
Huge fan of the GODAN input method, been using for almost 3 years now.
One thing that annoys me though, is a visual detail. I would prefer to have Kana displayed on the keys, instead of Romaji. Digging through settings I was surprised to find, that there is no option to switch this. Using the GODAN input method forces the keys to display Romaji. Would it be possible to have them displayed with Kana instead?
The promotional material on the release page ( https://support.google.com/ime/japanese/answer/2700298?hl=ja ) shows a Kana version existing, but I have been not able to find it.

**Comment by hiroyuki-komatsu** [comment]
Hi, thank you for your feedback. I'm very glad to hear that Godan is useful for you.

We don't have that option for Mozc or Gboard.
The current version of Mozc provides the conversion engine only. If you want to add your own change to the code, you might want to check out the commit tagged `2018-02-16`. Please let me inform that we no longer support that version though.

For Gboard, please provide your feedback via the Gboard application settings.

Thank you,

**Comment by FrostKiwi** [comment]
> The current version of Mozc provides the conversion engine only. 

Ohh, how does the [F-Droid app 'Mozc for Android'](https://f-droid.org/packages/org.mozc.android.inputmethod.japanese/) auto-build itself then? The source-code button links to this repo.

> If you want to add your own change to the code, you might want to check out the commit tagged `2018-02-16`.

This repo only lists tag '2018-02-26'. I assume that's the one you are referring to.

**Comment by hiroyuki-komatsu** [comment]
> Ohh, how does the [F-Droid app 'Mozc for Android'](https://f-droid.org/packages/org.mozc.android.inputmethod.japanese/) auto-build itself then? The source-code button links to this repo.

Because that is not our site, we don't have the answer for it.

> This repo only lists tag '2018-02-26'. I assume that's the one you are referring to.

Ah yes, I meant `2018-02-26`.
