### ISSUE TITLE
「出だす」「見出だす」が変換できない

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#583]
`いだす`→`出だす`および`みいだす`→`見出だす`が変換できません。

後者については`見出す`という表記であれば候補に表示され、実際にそのような表記も用例が実在しますが、2022年現在としては「だす」との誤読を避けるためおよび「出づ」と送り仮名を揃えるために「出だす」と表記することが一般的かと思われます。
根拠として、デジタル大辞泉では「出だす」で立項しています。

辞書追加おねがいいたします。

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/5e3542b98adb743553e672f34caee6d5d8021b85 added the words.
Thanks,
