### ISSUE TITLE
括弧の呼称を改めてはどうか

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#586]
キーボードの`「`キー（JISキーボードのEnterの左隣のキー）を押してスペースバーを押すと、下記の候補が現れます。
```
（前略）
（[[全]始め丸括弧]
（中略）
［[[全]始め大括弧]
（中略）
｛[[全]始め中括弧]
（後略）
```

この括弧の呼称には3つの問題点があります。
1. 1つめの記号は「丸括弧」と呼称しているのに、2つ目3つ目は「大括弧」「中括弧」と統一性がない。
2. `{}`と`[]`のどちらが大括弧でどちらが中括弧かは数学の普遍的なルールではない。その場その場におけるルールであり、ローカルルールを押し付けている。
4. そもそも、JIS Z 8201-1981に反している。

以上の点からJISに則り「丸括弧」「角括弧」「波括弧」に改めることを提案します。

**Comment by hiroyuki-komatsu** [comment]
Using 角括弧 and 波括弧 makes sense, although I'm not sure your meaning of "ローカルルールを押し付けている".

c3b1c19 is the update.
