### ISSUE TITLE
「〇〇をしたにも拘らず」が誤変換される

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#590]
「(名詞)をしたにも」「(名詞)をしたにも拘らず」が誤変換されます。
具体的には、
- `しょくじをしたにも`→`食事を下にも`
- `さぎょうをしたにも`→`作業を下にも`

となってしまい、サ変動詞の「した」が下と誤変換されてしまいます。
修正のほどお願いいたします。

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/671
