### ISSUE TITLE
「ご感想」が「ご乾燥」と誤変換される

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#593]
`ごかんそう`でスペースキーを押すと`ご乾燥`が一番最初に表示されます。
しかし、乾燥という語に「ご」をつけて用いる状況が思い当たりません。一般的には用いないものではないでしょうか。
そのため、辞書からの削除を提案します。

Aozorasearchで「ご乾燥」「御乾燥」と検索しましたがヒットせず、Googleでも有意義な結果はありませんでした（「制御乾燥方式」がヒットするなど）。

**Comment by hiroyuki-komatsu** [comment]
Thanks for the suggestion.

"ご乾燥ください" sounds a valid phrase, and there are number of web pages with this phrase.

https://www.google.com/search?q=%22%E3%81%94%E4%B9%BE%E7%87%A5%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84%22

On the other hand, it makes sense to rank "ご感想" higher than "ご乾燥".

**Comment by tomatojuicengc5195** [comment]
確かに、「ご乾燥ください」という言い回しであれば文法上成り立ちますね。ご教示ありがとうございます。

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/671
