### ISSUE TITLE
Messed up commit history?

### ISSUE THREAD

**Issue by Nocifer** [google/mozc#597]
Hello,

I was trying to build the latest Mozc version and I found that while building directly against the latest master is fine, trying to build against the latest commit 490cffc7fb08023d07758104bdad1f23e6da2dff was problematic due to some missing files/folders:
- src/data/hentaigana/
- src/rewriter/a11y_description_rewriter{.cc,.h,_test.cc}
- src/rewriter/gen_single_hentaigana_rewriter_data.py

After looking some more into it, it turns out that the issue apparently goes deeper:

1) The single change committed with 490cffc7fb08023d07758104bdad1f23e6da2dff ["Update BUILD_OSS to 4830"] (August 27th) is also present in the history of previous commits, going as far back as 8705e47261826cef691006ec9fb127619880d252 (August 22nd).
2) 490cffc7fb08023d07758104bdad1f23e6da2dff is missing not only the previously mentioned files but (as far as I checked) all changes from previous commits, up to and including 8705e47261826cef691006ec9fb127619880d252.
3) The latest master reports bf5e3ce232f3afd6c807d9c3d75d41fea08befc5 (August 26th) as the latest commit, which is second-to-last in the commit history, instead of the actual latest 490cffc7fb08023d07758104bdad1f23e6da2dff.

It's almost as if 490cffc7fb08023d07758104bdad1f23e6da2dff kind-of-rebased itself against 72f91f31936afa9b8f0bece819bb767915a7f14d (August 18th) and then applied itself to all subsequent commits, but was not recorded as a distinct commit to the latest master (which is based off bf5e3ce232f3afd6c807d9c3d75d41fea08befc5, and that's why it builds fine). So either I'm hallucinating and/or I'm more clueless about how git works than I ever thought I could be, or there's something seriously weird going on.

**Comment by hiroyuki-komatsu** [comment]
Hi, we haven't had similar issues on our environments or GitHub Actions.
Would you try the latest commit?

It might not be a GIt issue, but a cache issue on the build system.
So error logs would be helpful.

Thanks,

**Comment by hiroyuki-komatsu** [comment]
Closing this issue.
Please feel free to reopen it if the problem still remains.
