### ISSUE TITLE
「解説」と「開設」の変換候補の順位について

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#601]
`ぎんこうこうざをかいせつ`でスペースキーを押すと`銀行口座を解説`と誤変換されます。
前後の文に合わせて候補の順位を変え、解説と開設を使い分けられないものでしょうか。

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/671
