### ISSUE TITLE
「蚊に嚙まれる/噛まれる」が誤って変換される

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#605]
`かにかまれる`と入力してスペースキーを押すと、`カニカマれる`と誤って変換されます。「`蚊に嚙まれる`（印刷標準字体）」「`蚊に噛まれる`（略字）」と変換できるよう、辞書追加お願いいたします。

なお「嚙まれる」という語の典拠ですが、『日本方言大辞典』 (ISBN: 978-4-09-508201-1) に収録されています。

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/671
