### ISSUE TITLE
「高印象」という語について

### ISSUE THREAD

**Issue by ghost** [google/mozc#606]
`こういんしょう`でスペースキーを押すと、変換候補の1番目に「`高印象`」が、2番目に「`好印象`」が表示されます。

この「高印象」という語は、どのような根拠によるものなのでしょうか。Aozorasearchでのヒットは0件、Google検索での完全一致は「好印象」の誤記と思われるものしかヒットしませんでした。
『日本国語大辞典』『大漢和辞典』でも「高」という語について調べてみたところ、「立派である」という意味が載っており非常に難しいところではありますが、「よい」「このましい」といった意味の掲載はありませんでした。

「立派である」という用法を考慮すれば現時点で誤りと断定することはできないものの、文法上は正しくとも使用例が無い語である可能性が高いと考えています。

辞書から削除をするべきなのでしょうか。仮に削除しない場合、`好印象`と順位を入れ替える必要があるかと存じます。

**Comment by hiroyuki-komatsu** [comment]
"好印象" has been ranked the top candidate since 2.29.5111.
Thanks,
