### ISSUE TITLE
Can't use Alt key in keybinds.

### ISSUE THREAD

**Issue by Maesamine** [google/mozc#607]
I want to copy the default setup for the Microsoft IME, where I use alt+` to shift between kana and alphanumeric. This isn't possible in mozc for some reason. Even if I manually edit the configuration file, options containing alt as part of the command are removed.

This seems like an obvious use-case.

**Comment by hiroyuki-komatsu** [comment]
Hi, we think Alt is a key for GUI frameworks but not applications.
So we'd suggest to configure your IMF (e.g. Ibus, Fcitx, etc.) or remap alt+` to another key supported by Mozc (e.g. Henkan).
