### ISSUE TITLE
「妄語」「飲酒」が変換できない

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#624]
`もうご`で`妄語`が、`おんじゅ`で`飲酒`が変換できません。
殺生、偸盗、邪淫は変換候補に現れます。辞書追加お願いいたします。

**Comment by tomatojuicengc5195** [comment]
「`不妄語`」と「`不飲酒`」も辞書追加お願いいたします。

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/668
