### ISSUE TITLE
Failure to build on Windows, including large size dictionaries (Mozc UT Dictionary)

### ISSUE THREAD

**Issue by mikunimaru** [google/mozc#625]
The build for Windows fails when including large size dictionaries like the Mozc UT dictionary.
Just to be sure, the build for Windows with the regular dictionary was successful, and I tried building Mozc on Ubuntu 20.04 on WSL with the code including the large dictionary that failed on Windows, and this also succeeded.

Environment: Windows 11, Visual Studio 2022.

Mozc UT Dictionary
http://linuxplayers.g1.xrea.com/mozc-ut.html
If it is difficult to investigate this issue because of lack of access to the Windows 11 environment, there is a virtual environment provided by Microsoft.
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

**Comment by hiroyuki-komatsu** [comment]
Hi mikunimaru,

Would you provide error logs on your environment?

Since Mozc UT dictionary is not our own project, we are not sure how much we can contribute this issue.
Thanks,

**Comment by mikunimaru** [comment]
I tried again and couldn't reproduce.
It may be due to file operations on WSL on the way, but I can't remember the exact procedure when the issue occurred.
I will report back when a reproducible procedure is discovered.
