### ISSUE TITLE
「全財産」が変換できない

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#628]
`ぜんざいさん`で`全財産`が変換できません。辞書追加お願いいたします。

**Comment by tomatojuicengc5195** [comment]
多くの辞書には載っていないので、言葉の用例を挙げておきます。

> 遺言に「全財産を妻に相続させる」…子どもが遺留分侵害額請求権で遺産を得る方法

朝日新聞 https://souzoku.asahi.com/article/13651747

> 「全財産を妹に」父の遺言書の真意は？64歳姉の疑問

毎日新聞 https://mainichi.jp/premier/business/articles/20221027/biz/00m/020/012000c

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/668
