### ISSUE TITLE
「向上」と「工場」の変換候補の順位について

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#629]
`あんぜんせいのこうじょうにはつながらない`で変換すると、`安全性の工場にはつながらない`と変換されます。
前後の文に合わせて「`工場`」と「`向上`」の優先順位を変えることはできないものでしょうか。
よろしくお願いいたします。

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/671
