### ISSUE TITLE
漢字「瓣」の変換候補における注釈について

### ISSUE THREAD

**Issue by ghost** [google/mozc#633]
「`べん`」で変換候補を表示した際、「辯」と「辨」には「[弁の旧字体]」という注釈が表示されますが、「瓣」には表示されません。
追加お願いいたします。

**Comment by hiroyuki-komatsu** [comment]
[d6491ae](https://github.com/google/mozc/commit/d6491aeaeb8af318f4e8b02ecd8d366edfbc1c04) added the description of 瓣 based on your feedback.

Thank you,
