### ISSUE TITLE
変換候補「順」について

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#634]
`すなほ`で変換すると、「`順`」と変換されます。この「すなほ」という語は、「すなお（≒素直）」の歴史的仮名遣い表記と推察されます。
しかしながら、現在のMozcは、歴史的仮名遣いの語は辞書に収録しない方針かと存じます。仮に収録するにしても、「現代仮名遣いのみの候補を出すモード」「歴史的仮名遣いの候補のみを出すモード」「どちらも変換できるようにするモード」といった大掛かりな実装をしない限り、利便性は向上しないのではないでしょうか。

そこで、提案です。
- 案1: 「`すなほ`→`順`」を辞書から削除する。
- 案2: ATOKの「文語モード」に類似した、歴史的仮名遣いの変換ができるモードを追加し、「`すなほ`→`順`」の語を当該モード時のみ変換できるようにする。

以上どちらかの方策を取ることを提案します。個人的には、案2は実装がかなり大変かと存じますので、どちらかといえば案1を推しますが、案2に反対するものではありません。

**Comment by hiroyuki-komatsu** [comment]
This is a person name like 太郎(たろう).
https://www.google.com/search?q=%E9%A0%86+%E3%81%99%E3%81%AA%E3%81%BB

Thanks,

**Comment by tomatojuicengc5195** [comment]
人名で使用例があれば、歴史的仮名遣の語も収録するということでしょうか？
歴史的仮名遣の変換候補と、現代仮名遣いの変換候補は分離したほうが利便性が向上すると思います。

**Comment by tomatojuicengc5195** [comment]
「人名で使用例があるから」なんて理由で歴史的仮名遣いの語を収録していたらきりがないと思います。いくらご本人が自署で「順」に「すなほ」とルビを振ろうと、現代仮名遣いでは「すなお」です。これを認めたら、「『大原』を『おほはら』と書く人がインターネットで観測されたから、『おほはら→大原』も辞書に追加しよう」となりかねず、きりがありません。歴史的仮名遣いの語を辞書に追加するのは大いに結構ですが、ATOKの「文語モード」のように設定で表示する・しないを制御できるようにすべきだと思います。

**Comment by tomatojuicengc5195** [comment]
> This is a person name like 太郎(たろう). https://www.google.com/search?q=%E9%A0%86+%E3%81%99%E3%81%AA%E3%81%BB
> 
> Thanks,

この回答はあまりにもこのIssueを単純化・矮小化しています。本質に触れていません。

**Comment by tomatojuicengc5195** [comment]
別の言い方をすると、漢字表記される語であれば、歴史的仮名遣いの語を人名だからといって特別扱いすべきではない、ということです。
「おもひでぽろぽろ」や「眞鍋かをり」を辞書から排除すべきと主張しているわけではありません。仮名書きの語であれば、固有名詞として表記は尊重されるべきです。しかし、漢字表記の語では、あくまでも補助的な「ルビ」にすぎないのですから、人名であっても尊重すべきだとは思いません。

**Comment by tomatojuicengc5195** [comment]
以上の事情により、Issueの再オープンを求めます。 @hiroyuki-komatsu

**Comment by tomatojuicengc5195** [comment]
> This is a person name like 太郎(たろう). https://www.google.com/search?q=%E9%A0%86+%E3%81%99%E3%81%AA%E3%81%BB

これは例えとして不適切です。例えを出すなら、「たろう」ではなく「たらう」です。

**Comment by tomatojuicengc5195** [comment]
同様の問題は「`いさを`→`勲`」にもあります。
