### ISSUE TITLE
「優先」と「有線」の変換候補の順位について

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#635]
前後の文に合わせて、優先と有線の候補の順位を変えられないものでしょうか。

| 変換前文字列 | 変換後文字列 | 期待した結果 |
| --- | --- | --- |
| ゆうせんでもむせんでもいい | 優先でも無線でもいい | 有線でも無線でもいい| 
| むせんとゆうせんからせんたくする | 無線と優先から選択する | 無線と有線から選択する |

よろしくお願いいたします。

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/671
