### ISSUE TITLE
「信書開封罪」が誤って変換される

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#645]
`しんしょかいふうざい`でスペースキーを押すと`新書開封剤`と変換されます。`信書開封罪`と変換できるよう、辞書追加お願いいたします。

**Comment by hiroyuki-komatsu** [comment]
Hi tomatojuicengc5195,

Thank you for your feedback. We are going to update words not in the dictionary in a lump.

Best regards,

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/668
