### ISSUE TITLE
「愛新覚羅」が変換できない

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#646]
`あいしんかくら`でスペースキーを押しても`愛新覚羅`と変換できません。「`愛新覚羅溥儀`」「`愛新覚羅溥傑`」であれば変換できます。辞書追加お願いいたします。

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/668
