### ISSUE TITLE
Parenthesis symbols with no defined reading.

### ISSUE THREAD

**Issue by mikunimaru** [google/mozc#650]
It seems that pull requests are not accepted, so I will post it as an issue.

The symbols are read as "だぶるみにゅーと", "ののかぎ" or "つめかっこ".
https://github.com/google/mozc/blob/db37db71b53c9accc9ad66d12ad8196b25c771b3/src/data/symbol/symbol.tsv#L535-L536

Perhaps the following places also need to be changed.
https://github.com/google/mozc/blob/db37db71b53c9accc9ad66d12ad8196b25c771b3/src/data/symbol/symbol.tsv#L55-L99
https://github.com/google/mozc/blob/db37db71b53c9accc9ad66d12ad8196b25c771b3/src/data/symbol/categorized.tsv#L166-L167
https://github.com/google/mozc/blob/db37db71b53c9accc9ad66d12ad8196b25c771b3/src/data/symbol/ordering_rule.txt#L39-L59
https://github.com/google/mozc/blob/db37db71b53c9accc9ad66d12ad8196b25c771b3/src/base/util.cc#L1012-L1023
https://github.com/google/mozc/blob/db37db71b53c9accc9ad66d12ad8196b25c771b3/src/base/util_test.cc#L913-L932

Sorry if there are any omissions.

**Comment by hiroyuki-komatsu** [comment]
Hi mikunimaru,

Thank you for your suggestion and sorry for our late response.
We are going to update the entries based on your suggestions.

Thank you for your feedback.

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/4610acaa4b7292efc43566d3f2567cf48473c946 added data for 〝〟 based on your suggestions.

Thank you!

**Comment by mikunimaru** [comment]
Thanks for the great solution.
Conversion from brackets is also possible and has become very convenient.


https://github.com/google/mozc/blob/4610acaa4b7292efc43566d3f2567cf48473c946/src/base/util.cc#L932-L941

I have a feeling that this part of the code also needs a symbol.

**Comment by mikunimaru** [comment]
> Thanks for the great solution. Conversion from brackets is also possible and has become very convenient.
> 
> https://github.com/google/mozc/blob/4610acaa4b7292efc43566d3f2567cf48473c946/src/base/util.cc#L932-L941
> 
> I have a feeling that this part of the code also needs a symbol.

Very sorry. I tried to fix that part, but it didn't solve the issue.
