### ISSUE TITLE
「慎重に○○」が誤って変換される

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#654]
「`慎重に運ぶ`」「`慎重に選ぶ`」などの「慎重に」の直後に動詞をつけたものが、「身長に運ぶ」「身長に選ぶ」と誤って変換されます。
「慎重」は形容動詞ですが、「身長」はそうではなく、「身長に」という形で使用することはほぼないのではないでしょうか。

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/671
