### ISSUE TITLE
「〜〜難色を示す」が誤って変換される

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#655]
「その場合難色を示す」「先生が難色を示す」のように、「難色を」の直前に何らかの文言が付加されていると、「その場合何色を示す」「先生が何色を示す」のように「何色」と誤って変換されます。
余談ですが、「その場合難色を示される」「先生が難色を示される」であれば正常に変換ができます。

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/671
