### ISSUE TITLE
「○○しとう存じます」が誤って変換される

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#658]
「改善しとう存じます」「更新しとう存じます」といった「○○しとう存じます」の形の文が「改善し等存じます」のように誤って変換されます。
正しく変換できるよう、辞書追加お願いいたします。

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/671
