### ISSUE TITLE
「漢字かな交じり文」「漢字仮名交じり文」が誤って変換される

### ISSUE THREAD

**Issue by tomatojuicengc5195** [google/mozc#667]
`かんじかなまじりぶん`で変換すると、`漢字かな交じり分`と変換されます。  「`漢字かな交じり文`」「`漢字仮名交じり文`」と変換できるよう、辞書追加お願いいたします。

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.

This issue was merged to https://github.com/google/mozc/issues/671
