### ISSUE TITLE
Typing issue: OOV words

### ISSUE THREAD

**Issue by hiroyuki-komatsu** [google/mozc#668]
List of OOV (out-of-vocabulary) words, which are not in the word dictionary yet.

key | value | source
-- | -- | --
こうじょ | 扣除 | https://github.com/google/mozc/issues/620
りゅうこうごたいしょう | 流行語大賞 | https://github.com/google/mozc/issues/622
たんろくでんち | 単6電池 | https://github.com/google/mozc/issues/623
もうご | 妄語 | https://github.com/google/mozc/issues/624
おんじゅ | 飲酒 | https://github.com/google/mozc/issues/624
ふもうご | 不妄語 | https://github.com/google/mozc/issues/624
ふおんじゅ | 不飲酒 | https://github.com/google/mozc/issues/624
ぜんざいさん | 全財産 | https://github.com/google/mozc/issues/628
きこう | 貴行 | https://github.com/google/mozc/issues/631
さぶすく | サブスク | https://github.com/google/mozc/issues/640
ばうんしゃ | 馬運車 | https://github.com/google/mozc/issues/642
しんしょかいふうざい | 信書開封罪 | https://github.com/google/mozc/issues/645
あいしんかくら | 愛新覚羅 | https://github.com/google/mozc/issues/646
らのべ | ラノベ | https://github.com/google/mozc/issues/647
こんせ | 今世 | https://github.com/google/mozc/issues/651
こんぜ | 今世 | https://github.com/google/mozc/issues/651
こんせい | 今世 | https://github.com/google/mozc/issues/651
ふくじょし | 副助詞 | https://github.com/google/mozc/issues/660
らっぷ | 乱舞 | https://github.com/google/mozc/issues/661
こきゅう | 枯朽 | https://github.com/google/mozc/issues/662
にっこうさ | 日較差 | https://github.com/google/mozc/issues/663
にちこうさ | 日較差 | https://github.com/google/mozc/issues/663
にちかくさ | 日較差 | https://github.com/google/mozc/issues/663
こうばいりょくへいか | 購買力平価 | https://github.com/google/mozc/issues/664

**Comment by tomatojuicengc5195** [comment]
「にちこうさ」という語は少々疑問があります。日本語のルールとして、（少なくとも現代の発音・現代仮名遣いでは）促音化して「にっこうさ」になるのが自然ではないでしょうか。「すいぞくかん/すいぞっかん、ちょさくけん/ちょさっけん問題」のように、 「にちこうさ」が国語辞典に載っているのなら「現代語においてどちらも許容される」としてMozcの辞書に収録するのもありだとは思いますが、少なくとも『日本国語大辞典』には載っていません。似た例として、歴史的仮名遣では「白金」に「はくきん」、「国旗」に「コクキ」とルビを振りますが、現代仮名遣いならふつうは「はっきん」「こっき」のはずです。

**Comment by tomatojuicengc5195** [comment]
Mozcが歴史的仮名遣に対応するならば話は別ですが、そうなるとかなりスケールが大きな話になってくると思います。

**Comment by tomatojuicengc5195** [comment]
申し訳ございません。誤解していました。
現代仮名遣いであっても歴史的仮名遣であっても、「日較差」を「にちこうさ」と表記するのは一般的ではないと思います。
「日本」に「にちほん」、「日課」に「にちか」とルビをふるようなものです。
国語辞典でも、 「日較差」の歴史的仮名遣表記は「にっかうさ」とされており、「にちかうさ」とはされていません。

**Comment by hiroyuki-komatsu** [comment]
There are multiple articles of "日較差" read as "にちこうさ".
https://www.google.com/search?q=%E6%97%A5%E8%BC%83%E5%B7%AE+%22%E3%81%AB%E3%81%A1%E3%81%93%E3%81%86%E3%81%95%22

It's actually more than "にっこうさ"
https://www.google.com/search?q=%E6%97%A5%E8%BC%83%E5%B7%AE+%22%E3%81%AB%E3%81%A3%E3%81%93%E3%81%86%E3%81%95%22

So some people expect to type "日較差" from "にちこうさ".

**Comment by tomatojuicengc5195** [comment]
うーむ、使用例が複数あるという理由だけで、国語辞典に載っていない読み方をMozcに収録してしまうのは少々勇み足な気がします。本来誤読であっても、定着すれば国語辞典には載ります。しかし、「にっこうさ」は「誤読である」という注釈付きですら国語辞典には載っていません。

**Comment by hiroyuki-komatsu** [comment]
Here are several articles about "日較差" that is read as "にちこうさ".

* https://kotobank.jp/word/%E8%BC%83%E5%B7%AE%28%E3%81%93%E3%81%86%E3%81%95%29-1532612
* http://www.jamie-group.jp/yougoshu/word/ni
* https://aikoen.shop/glossary/setubi/22ni/054.html
* http://www.life-science-dictionary.com/weblsd/c/begin/%E6%97%A5%E8%BC%83%E5%B7%AE
* https://news.yahoo.co.jp/byline/nyomurayo/20221130-00326173

So, our decision is that people think "にちこうさ" is one of valid inputs to type "日較差".

By the way, this is data for software.
Even if the data is invalid in terms of linguistics, it is still OK for our software implementation.
When the user inputs "にちこうさ", I guess the user wants to type "日較差" and
I also think this conversion "にちこうさ→日較差" is a reasonable pair.

The point is "にちこうさ→日較差", but not "日較差→にちこうさ".
We need those data for our implementation, though I understand it is not so neat for you.

Thank you,

**Comment by tomatojuicengc5195** [comment]
> By the way, this is data for software.
> Even if the data is invalid in terms of linguistics, it is still OK for our software implementation.
> When the user inputs "にちこうさ", I guess the user wants to type "日較差" and
> I also think this conversion "にちこうさ→日較差" is a reasonable pair.

だったら通常の変換候補用の辞書には追加せず、「もしかして変換」用の辞書に追加すれば済む話だと思います。せっかく「もしかして変換」なる機能がすでに実装されているのですから、それを有効活用してはどうでしょうか。

「動詞ザ変」の件といい、Mozcの開発方針は日本語や日本語学への敬意が足りないと思います。IMEなのですから、プログラムとしての正確さだけでなく、日本語として妥当であるかどうかも考慮すべきです。**論文や国語辞典ですらない日本語入力システムが造語に走るのは慎むべきです。**

**Comment by tomatojuicengc5195** [comment]
IMEを作る上では、言語への敬意が必要です。他のプログラムと同じような感覚で臨まないでください。日本国外の企業に所属する、非日本語話者によって作られたMozcが日本語の文化を破壊しないことを願ってやみません。

**Comment by hiroyuki-komatsu** [comment]
Hi tomatojuicengc5195,

Your comment in https://github.com/google/mozc/issues/668#issuecomment-1382886317 is inappropriate for our constructive discussion.
Belongings or primary languages are not related to this topic.

Please withdraw your comment. Otherwise my commitments for your comments will be very limited.

----

You think "にちこうさ" is  a wrong reading of "日較差", because you haven't found dictionaries with that entry.
Is my understanding correct?

On the other hand, I think "にちこうさ" is a valid reading of "日較差", because there are several articles with that entry
as I mentioned in the previous comment (https://github.com/google/mozc/issues/668#issuecomment-1382828345). Some of them are dictionaries or glossaries.

I think both opinions are reasonable options with respect to the language and the users.

Talking about ザ変, other major IMEs (e.g. MS-IME, ATOK) also use it.

**Comment by tomatojuicengc5195** [comment]
まず最初に申し上げておきますと、現時点では発言を撤回するつもりはございません。脅迫じみた言い回しは控えていただけますと幸いです。

---
要点を整理しますね。
まず、私は何が何でも「にちこうさ」を辞書に追加すべきではないと主張しているわけではないのです。「勇み足」という表現を用いたように、現時点では時期尚早（これも変換できませんね）であると言っているだけなのです。将来的には、「にちこうさ」の辞書追加に賛成する可能性は十二分にあります。

こんにちのコンピューター中心の社会では、日本語入力システムが日本語話者の言葉に与える影響はとても強いと考えています。だからこそ、日本語入力システムは日本語話者の数歩後を追いかけて、文化を邪魔しないようにすべきであると考えています。
例えば、「洗滌」という言葉がありますね。これは、本来は「せんでき」と読むとされているようです。しかし、2023年現在では「せんじょう」と読むのが主流ではないでしょうか。私は、誤った読み方を全面的にIMEの辞書から排斥すべきと主張しているわけではありません。そんなことをしたら、「洗滌（せんじょう）」も「攪乱（かくらん）」も「消耗（しょうもう
）」も変換できなくなります。私はMozcがそんな不便なIMEになることを望んでいません。

でも、これら「せんじょう」「かくらん」「しょうもう」と、「にちこうさ」は異なります。前3つは国語辞典や漢和辞典に載っていますが、「にちこうさ」は載っていないのです。
国語辞典や漢和辞典に言葉を載せるかどうかは、学者が深く考えて決めることでしょう。それに比べると、IMEの辞書への収録基準は短くて浅い議論で決められてしまいがちです。
IMEの場合は議論が浅くなりがちだからこそ、学者が作る辞書の後追いをすべきと主張しているのです。「なお、これはことばの誤読に限った話です。流行語対象にノミネートされたばかりの新語を、IMEに入れるなとは言いません。」

正直言って、百科事典や英和辞典の編纂者は日本語のプロとは言い難い面があります。出典として提示されたコトバンクには、「正しくは較差(かくさ)という。」という記述がありますね。果たしてこれは本当でしょうか？まず、「較」という漢字は、意味によって二つの音読みがあります。意味によって読みが異なるわけですね。そして、「くらべる」という意味の場合は、「コウ」が本来の読みで、「カク」は別の意味の場合の際に使う読みと取り違えたことによる誤読が定着したものではないか、と思います。つまり、「較差」 の本来の読みは「こうさ」である可能性が高いのです。このように、百科事典や英和辞典は日本語の学術的な正しさという点では国語辞典より劣ると考えています。

**Comment by tomatojuicengc5195** [comment]
もっとも、「誤読も変換できる便利なIME」と、「学術的に正しいIME」のどちらを取るか、というのはグラデーションのようなものなので、はっきり決めるのは難しいでしょう。その隙間を埋めるための機能が「もしかして変換」なのだと思います。私は「もしかして変換」を無効にしていますが、「せんじょう」も「しょうもう」も変換できます。これらの語彙も、時代が違えば「もしかして変換」行きだったことでしょう。

**Comment by tomatojuicengc5195** [comment]
最後に、あえて愚かな疑問を投げさせてください。

なぜ、Mozcの議論に英語を用いるのでしょうか。
MozcのIssueを投げるのは、基本的にMozcの利用者です。Mozcの利用者は、母語か非母語かは別として、日本語話者であることが確実でしょう。

> You think "にちこうさ" is a wrong reading of "日較差", because you haven't found dictionaries with that entry.
Is my understanding correct?

この文章だって、英文の中に漢字やひらがなをブロックのごとく挿入しているではありませんか。日本語の中に、ラテンアルファベットの単語を挿入することは（江戸時代以前ならともかく）今では一般的に行われています。では、逆に英語ではどうでしょうか？英文の中に、漢字や仮名の単語を挿入することは、一般的ではないと思います。Mozcの議論を英語で行うことは、デメリットの方が多いのではないでしょうか。なぜかたくなに英語を用いるのか、ずっと疑問でした。

> 日本国外の企業に所属する、非日本語話者によって作られたMozcが日本語の文化を破壊しないことを願ってやみません。

この文は、Mozcの議論が英語によって行われていることに対する疑問の現れです。

**Comment by tomatojuicengc5195** [comment]
「なぜ、Mozcの議論は英語で行われるのか。」自問自答したことがあるのです。
非日本語話者からのIssueを受け入れやすくするため？利用者の大半が日本語話者なのに、そんなわずかな人のためにするより、日本語学の専門用語を訳さねばならず、漢字やかなが混在した不自然な英文を使ってまで英語で議論する必要があるのでしょうか？メリットとデメリットが釣り合っているのだろうか？

私なりに出した結論が、「Googleの社内公用語が英語だから」でした。それしか思い浮かびませんでした。先程の文で「日本国外の企業」なる言い回しをしたのは、これによるものです。

**Comment by ShikiSuen** [comment]
データとプログラムを別々のレポジトリにすれば良いかもしれません。
少なくとも、このような議論はプログラムのレポジトリに差し支えなくなると思います。
さらに、データのレポジトリのISSUEは日本語とし、プログラムのISSUEを主には英語とすれば、いかがなさいましょうか？

**Comment by ShikiSuen** [comment]
@tomatojuicengc5195 横から失礼致します。

市販の入力アプリに、アプリの不足点をクレームするのは良いけど、MOZCはあくまで無料で、オープンソースで、「BSDライセンス」で提供したものであり、少なくとも「公式的保証・義務など」は一切ありません。

上記のことを心得てからご言動お願いいたします。少なくとも、貴殿の上記のコメントに含まれていた空気はどう見ても微妙過ぎだと拙者はそう感じられます。

**Comment by hiroyuki-komatsu** [comment]
ShikiSuen さん

お心遣いありがとうございます。感謝いたします。

ご指摘の通り、プロジェクトやレポジトリを分割することによる利点はいくつかあると思います。その一方で、管理の作業量が増えてしまいますので、プロジェクトの中身に集中するためにも、現時点ではこのままのレポジトリで運用する予定です。



tomatojuicengc5195 さん

「にちこうさ」は「日較差」の読みのひとつであるかという議論に対して、私はいくつかの使用例を示したうえで意見を述べました。

たとえ異なる見解であったとしても、妥当な意見のひとつではあるはずです。

それに対して「日本語の文化を破壊する」という表現をされますと、私への心理的負荷はとても高く、私にとっては建設的な議論を続けることが難しいです。

そして、その論拠が所属や使用言語であるならば、私には受け入れられません。


これまでにいただいた有益なご助言から tomatojuicengc5195 さんは日本語に対する造詣がとても深く、また高い志をお持ちであると思います。ならばこのプロジェクトを通じてではなく、ご自身によって変更や制作をされる方が、ご自身の目指す理想の日本語入力を実現できるのではないでしょうか。


Mozc プロジェクトは他のプロジェクトと同様に、使用言語によらず多くの方々によって支えられています。また日本語入力ソフトウェアではありますが、ディストリビューションの制作などを含め、必ずしも日本語話者のみが使うわけではありません。そのために、このプロジェクトではソースコードや文書を含め英語を使用しています。その延長で、 私は issue に対しても英語での記述をするようにしています。


私からは以上です。

表題と離れた議論が続いていますので、この issue の複製を作成したのち発言をロックいたします。

----

Hi ShikiSuen,

Thank you for your suggestions. I appreciate it.

As you mentioned, there are some advantages to using multiple projects or repositories. On the other hand, it requires additional maintenance resources. So, we'd like to keep the current repository structure to focus on our main contributions at this moment.


Hi tomatojuicengc5195,

For the discussion whether "にちこうさ" is one of reading of "日較差", I mentioned my opinions with several use cases.

It should be a reasonable option, even though it is a different opinion from yours.

The counter statement "It destroys Japanese culture" makes me quite nervous. It is hard for me to keep constructive discussions.

If the reason for the statement comes from organizations or primary languages, I cannot accept it.


Through your previous helpful comments, I think you have deep knowledge and strong will of the Japanese language. I suppose that you will be able to create your own ideal Japanese input by yourself rather than using this project.


Regardless of the language, this project is supported by many contributors. Although this is a Japanese input software, like distribution creators, the users may not necessarily speak Japanese. So, this project uses English for source code and documents. I use English for issues too for this reason.


That is all from me.

As this issue contains a number of comments apart from the main topic, I'm going to make a copy of this issue then lock this issue.


Best regards,
