### ISSUE TITLE
Missing "こと***" entries

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#67]
```
I've got them automatically and fixed them manually.
Maybe there are some mistakes and you need to calculate the scores.
Check "tmp.koto" please.

e.g.
======================================================
すごいこと 2665    2235    5782    凄いこと
そういうこと  3006    2235    4853    そういうこと
======================================================

```

Original issue reported on code.google.com by `heathros...@gmail.com` on 9 Nov 2010 at 7:26

Attachments:
- [tmp.koto](https://storage.googleapis.com/google-code-attachments/mozc/issue-67/comment-0/tmp.koto)

**Comment by hiroyuki-komatsu** [comment]
Added evaluation test cases in this issue.

* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv
