### ISSUE TITLE
default install path for mozc.xml

### ISSUE THREAD

**Issue by tomcat14d** [google/mozc#674]
**Description**
build_mozc_in_docker.md says the default install path for mozc.xml is /usr/share/ibus/component/mozc.xml.
But in the generated mozc.zip the mozc.xml is installed in /usr/lib/ibus/component/mozc.xml.

**Version or commit-id**
Mozc-2.28.4960.102+24.11.oss (9f4c39694eccf0862dc38fbab12311a347470ecb)

**Environment**
 OS: Mageia 8

**Comment by hiroyuki-komatsu** [comment]
Hi tomcat14d,

Right, it should be `/usr/share/ibus/component/mozc.xml` and it should be configurable.
I'm going to fix it.

Thank you for your report.

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/6764de06d108e2195384fd39ef5403de473acb10 fixes the path and makes it configurable by modifying `config.bzl`.

Thank you,

**Comment by tomcat14d** [comment]
Thank you
