### ISSUE TITLE
雪関係単語

### ISSUE THREAD

**Issue by Hokkosha** [google/mozc#675]
**Category of the typing issue**
Choose one of them
1. Out-of-vocabulary (e.g. "堆雪" "排雪" is not in the candidate list at all).

**Issues**
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ---- | ---- | ---- |
| たいせつ | 堆雪 | 大切,大雪 |
| はいせつ | 排雪 | 排泄 |

**Version or commit-id**
Mozc-2.28.4715.102+24.11.oss

**Additional context**

**Comment by hiroyuki-komatsu** [comment]
Hi Hokkosha,
Thank you for your feedback.

We are going to add entries based on your feedback.
It seems "排雪(はいせつ)" is already in the dictionary (ver. 2.28.4960).

**Comment by Hokkosha** [comment]
Thank you for your response.
I'm looking forward to update.

**Comment by hiroyuki-komatsu** [comment]
Hi Hokkosha,

We fixed this issue based on your feedback as https://github.com/google/mozc/commit/9bcc6dd63d23ccaec5930e31ffd50c670a0fcee7

Thank you,
