### ISSUE TITLE
Typing Issue Report: リネーム (rename)

### ISSUE THREAD

**Issue by siketyan** [google/mozc#676]
**Category of the typing issue**

1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

**Issues**

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| りねーむ | リネーム | 理ネーム |

**Version or commit-id**
Mozc-2.28.4960.101+24.11.oss

**Additional context**
Tested on macOS Ventura 13.1 arm64 (Self built package)

**Comment by hiroyuki-komatsu** [comment]
Hi siketyan,

We fixed this issue based on your feedback as [06a506b](https://github.com/google/mozc/commit/06a506bd2d3f3e1ba12bcf368d43a6215c6a2f9a).

Thank you,

**Comment by siketyan** [comment]
@hiroyuki-komatsu 
Thank you a lot for the quick fix!
