### ISSUE TITLE
誤変換　はいたしょり→履いた処理

### ISSUE THREAD

**Issue by orgue** [google/mozc#677]
**Category of the typing issue**
Choose one of them
1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).
2. Word ranking issue (e.g. "夕日" is in the list, but ranking is lower than expected).
3. Conversion issue (e.g. "夕日がきれい" is not converted as expected).
4. Others

**Issues**
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| はいたしょり |排他処理 |履いた処理 |

**Version or commit-id**
[e.g. Mozc-2.28.4960.100+24.11.oss or d50a8b9ae28c4fba265f734b38bc5ae392fe4d25]
You can get the version string by converting "Version" or "ばーじょん".

**Additional context**

**Comment by hiroyuki-komatsu** [comment]
Hi orgue,

We fixed this issue based on your feedback as https://github.com/google/mozc/commit/7fd98633ac151203912bd37e3153e343cd5ae547

Thank you,
