### ISSUE TITLE
Typing issue: 時期尚早

### ISSUE THREAD

**Issue by hkiku482** [google/mozc#678]
**Category of the typing issue**
Conversion issue (e.g. "夕日がきれい" is not converted as expected).

**Issues**
| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| じきしょうそう | 時期尚早 | 時期焦燥 |

**Version or commit-id**
Mozc-2.26.4632.102+24.10.oss

**Comment by hiroyuki-komatsu** [comment]
Hi hkiku482,
Thank you for your feedback.

We are going to add entries based on your feedback.

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/ebd1ce24bcd7b3d496cb3ae40f1009929b812e0c added words based on your feedback.

Thank you,
