### ISSUE TITLE
unable to parse default ibus config

### ISSUE THREAD

**Issue by jrmaingo** [google/mozc#685]
**Description**
The `composition_mode` in the freshly-generated `ibus_config.textproto` has double quotes (`"`) when it should not according to the [example config in the docs](https://github.com/google/mozc/blob/db37db71b53c9accc9ad66d12ad8196b25c771b3/docs/configurations.md).

**Reproduce steps**
1. Delete the ibus config file
2. Restart ibus (eg `ibus write-cache; ibus restart`)
3. See that a new config was created.
4. See the following error message

```
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:335] Error parsing text-format mozc.ibus.Config: 19:22: Expected integer or identifier, got: "HIRAGANA"
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:335] Error parsing text-format mozc.ibus.Config: 19:22: Expected integer or identifier, got: "HIRAGANA"
```

**Expected behavior**
Default config would work and mozc input method would be available.

**Actual behavior**
mozc input method is not available.

**Version or commit-id**
mozc 2.28.4960.102

**Environment**
 - OS: Arch Linux 6.1.8-arch1-1
 - IMF: Ibus

**Investigations**
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + N/A
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + N/A
 - What applications this issue happens on (e.g. Chromium, gedit).
   + N/A
 - What applications this issue does not happen on (e.g. Chromium, gedit).
   + N/A
 - (optional) What versions or commit-ids this issue did not happen on
   (e.g. Mozc-2.28.4960.100+24.11.oss).
   + no-investigation.

**Additional context**
I believe this line is inserting `"` into the newly generated config: https://github.com/google/mozc/blob/96e8c8782bfe2cce96d775b525909d9202e120d7/src/unix/ibus/gen_mozc_xml.py#L70

**Comment by hiroyuki-komatsu** [comment]
Hi jrmaingo,

Thank you for the report.
That's right. Values of `composition_mode` should be enums but not strings.

I am going to fix it.
Best,

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/4fb1fc9dfc791baaa3550b7b10ca240a1146b5a7 fixed this issue.

Thank you,
