### ISSUE TITLE
キーマップの変更が再起動後に反映されない

### ISSUE THREAD

**Issue by tomcat14d** [google/mozc#686]
**Description**
ibus-mozc を使用しています。
ツールの「Mozc プロパティ」の「キー設定」でキーマップに変更を加えて適用した直後にはその変更内容が反映されますが、ibus の再起動後（or 再ログイン後 or システムの再起動後）には変更内容が反映されません。

**Reproduce steps**
1. ツールの「Mozc プロパティ」を開き、「一般」タブの「キー設定」で「キー設定の選択」の [編集] ボタンを押して「Mozc キー設定」を開く
2. Shift+Space で Mozc の入力モードの [直接入力] と [ひらがな] を切り替えるようにするために、次のエントリーの追加 or 既存のエントリーの変更を行う
　　直接入力 : Shift Space : IME を有効化
　　変換前入力中 : Shift Space : キャンセル後 IME を無効化
　　変換中 : Shift Space : キャンセル後 IME を無効化
　　入力文字なし : Shift Space : IME を無効化
3. [OK] を押して「Mozc キー設定」を閉じる
4. [適用] を押した後に [OK] を押して「Mozc プロパティ」を閉じる
5. テキストエディタ上などで 2. で行った変更が反映されていることを確認する
6. ibus の再起動 or 再ログイン or システムの再起動を行う
7. テキストエディタ上などで 2. で行った変更が反映されていないことを確認する

**Expected behavior**
ibus の再起動後（or 再ログイン後 or システムの再起動後）にもキー設定の変更内容が反映される

**Actual behavior**
ibus の再起動後（or 再ログイン後 or システムの再起動後）にはキー設定の変更内容が反映されない

**Version or commit-id**
Mozc-2.28.5000.100+24.11.oss [ebd1ce24bcd7b3d496cb3ae40f1009929b812e0c]

**Environment**
 - OS: Mageia 8
 - IMF (for Linux): ibus-1.5.27
 - DE: KDE Plasma5 5.20.4

**Investigations**
 - What versions or commit-ids this issue did not happen on
   Mozc-2.28.4990.100+24.11.oss [811cb8c7606a4732a83abb89752664eb23728623]

**Comment by hiroyuki-komatsu** [comment]
Hi tomcat14d,

Thank you for your report with reproduce steps and investigations.

Shift+Space might be taken by Ibus as a hotkey. To confirm it, would you please check the behavior with other shortcuts (e.g. Ctrl+j, F3, etc.)?

Since it works with https://github.com/google/mozc/commit/811cb8c7606a4732a83abb89752664eb23728623, the following two changes are probably related changes:
* Fix format errors of `composition_mode`. · google/mozc@4fb1fc9 
* Get rid of KeyMapFactory and make KeyMapManager immutable · google/mozc@7668dac 

Would you also confirm whether it works with https://github.com/google/mozc/commit/e18a3a72c060db4f7b80254f065e2a69f27b5221 or not?
If it works, https://github.com/google/mozc/commit/4fb1fc9dfc791baaa3550b7b10ca240a1146b5a7 is the problematic change, and if it doesn't work, https://github.com/google/mozc/commit/7668dacc05277c52d1a332a18dce98a047c0ef05 is the one.

Thank you,

**Comment by tomcat14d** [comment]
対応ありがとうございます。

Ctrl+j, F3, Ctrl+Space で試してみましたが、いずれも状況は同じでした。
また e18a3a72c060db4f7b80254f065e2a69f27b5221 でも確認してみましたが、同じ問題が発生しました。

**Comment by hiroyuki-komatsu** [comment]
Thank you for the investigations.

Then, I guess https://github.com/google/mozc/commit/7668dac is the problematic change. I'm checking it now. 

In parallel, would you please double check the following things?
* it doesn't work well on https://github.com/google/mozc/commit/7668dac, and
* it works well on the previous comment https://github.com/google/mozc/commit/48452d76353acd5b2507ae01e16fb44e53f7f846

Thank you,

**Comment by tomcat14d** [comment]
確認してみたところ、7668dac では問題が発生しましたが、48452d7 では問題は発生せず、ibus の再起動を行ってもキーマップの変更が正常に反映されました。

**Comment by hiroyuki-komatsu** [comment]
Thank you for the confirmation.
So, https://github.com/google/mozc/commit/7668dac should be the problematic change.

We will fix the issue, but it may take several days.
Sorry for your inconvinience.

Best,

**Comment by hiroyuki-komatsu** [comment]
Hi tomcat14d,
Would you check whether the following change fixes the problem or not?

```
diff --git a/src/session/session_handler.cc b/src/session/session_handler.cc
index c0c0122b..36f5e8e0 100644
--- a/src/session/session_handler.cc
+++ b/src/session/session_handler.cc
@@ -582,6 +582,7 @@ bool SessionHandler::CreateSession(commands::Command *command) {
   if (command->input().has_application_info()) {
     session->set_application_info(command->input().application_info());
   }
+  session->SetKeyMapManager(key_map_manager_.get());

   // Ensure the onmemory config is same as the locally stored one
   // because the local data could be changed by sync.
```

**Comment by tomcat14d** [comment]
7668dacc05277c52d1a332a18dce98a047c0ef05 にパッチを当てて確認してみました。

ビルドした mozc をインストールしてシステムの再起動をしたところ、変更していたキーマップの設定は反映されていませんでした。
その状態で「Mozc キー設定」を開いた後にそのまま閉じて適用ボタンを押すと、変更していた内容が反映されました。
ただ今までと違うのは、一度反映されれば、ibus を再起動しても変更内容が反映された状態を維持しています。また、再ログイン後にも反映状態が維持されています。
しかし、システムを再起動してしまうと反映されません。

念のために ebd1ce24bcd7b3d496cb3ae40f1009929b812e0c にもパッチを当ててビルドしてみましたが、結果は同じでした。

**Comment by tomcat14d** [comment]
54ce3e1f196c2624c2d972cddb3db21ec1ac8768 をビルドして確認してみましたが、
残念ながら前回のコメントの状況と同じでした。

**Comment by hiroyuki-komatsu** [comment]
Thank you so much for checking it again.

Then, I hope https://github.com/google/mozc/commit/04ff66252ca0782b8f380bfb4fa39fae344da33a will finally fix it.

**Comment by tomcat14d** [comment]
04ff66252ca0782b8f380bfb4fa39fae344da33a で問題が修正されていることを確認しました。
システムの再起動後にも、設定変更したキーマップが反映されています。
対応に感謝いたします。ありがとうございました。
