### ISSUE TITLE
Pair conversion doesn't work for some brackets.

### ISSUE THREAD

**Issue by mikunimaru** [google/mozc#688]
**Description**
〝　«　‹ do not work pair conversion.

**Reproduce steps**
1. Convert「xxx」

**Expected behavior**
It can be converted to 【xxx】『xxx』《xxx》 〝xxx〟 «xxx» ‹xxx›.

**Actual behavior**
It can be converted to 【xxx】『xxx』《xxx》, but not to 〝xxx〟 «xxx» ‹xxx›.

**Version or commit-id**
Mozc-2.28.5000.100+24.11.oss

**Environment**
 - OS: Windows 11

**Comment by hiroyuki-komatsu** [comment]
Hi mikunimaru,

[ae665f4](https://github.com/google/mozc/commit/ae665f403c99997ab0e22af7377ee07247ffb9de) added the feature based on your feedback.

Thank you,
