### ISSUE TITLE
Typing issue: Number of people

### ISSUE THREAD

**Issue by hkiku482** [google/mozc#689]
**Category of the typing issue**
2. Word ranking issue (e.g. "夕日" is in the list, but ranking is lower than expected).

**Issues**
The following contents are out of the ranking.
| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
|ひとり| 1人 | (optional, write here) |
|ふたり| 2人 | (optional, write here) |
|...| ... | (optional, write here) |

**Version or commit-id**
Mozc-2.26.4632.102+24.10.oss

**Additional context**
Other units may have same issue. "いっこ", "いっぽん" and so on.

**Comment by hiroyuki-komatsu** [comment]
Hi hkiku482,

Thank you for the feedback.
The latest version (2.28.5017) can already covert 1人, 2人, 1個.

We are investigating the case of 1本.

**Comment by hkiku482** [comment]
@hiroyuki-komatsu 
Thank you for your reply.
But, I noticed that this issue was a duplication with #672. Please close this if needed.

**Comment by hiroyuki-komatsu** [comment]
cf3e496 and 3c4d484 fix the case of 1本.

If the base form in Kanji (e.g. 一本) has proper POS IDs (e.g. lid: number, rid: counter suffix), it can be converted to variant forms (e.g. 1本).

In the previous implementation, if the base form has multiple entries with different POS IDs (e.g. [lid: number, rid: counter suffix], [lid: noun, rid: noun]), the variant conversion may not be performed.

Thank you for your feedback.
