### ISSUE TITLE
「速乾」の変換

### ISSUE THREAD

**Issue by Hokkosha** [google/mozc#690]
**Category of the typing issue**
3. Conversion issue (e.g. "夕日がきれい" is not converted as expected).

**Issues**
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
|そっかん| 速乾| 速乾性;足下ん |

**Version or commit-id**
Mozc-2.28.4715.102+24.11.oss

**Additional context**
「そっかん」と入力すると1位に予測変換で「速乾性」が出てきますが、変換したい「速乾」は下位にも出てこないので、一旦「速乾性」で確定後に「性」を削除しています。

**Comment by hiroyuki-komatsu** [comment]
[f396cde](https://github.com/google/mozc/commit/f396cdec2844d9532c57657e4910f57a16256b05) added words based on your feedback.

Thank you,
