### ISSUE TITLE
Mozc crashes on opening ConfigDialog.app or DictionaryTool.app on macOS

### ISSUE THREAD

**Issue by siketyan** [google/mozc#692]
**Description**
ConfigDialog.app and DictionaryTool.app always crash and can not be open on macOS.
As an IME, Mozc works fine.

I can remember the apps could be opened after just installed a few weeks ago, so the issue may depends on my environment.

macOS Crash Report:

<details>
<pre>
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               DictionaryTool [40058]
Path:                  /Library/Input Methods/Mozc.app/Contents/Resources/DictionaryTool.app/Contents/MacOS/DictionaryTool
Identifier:            org.mozc.inputmethod.Japanese.Tool.DictionaryTool
Version:               2.28.4960 (2.28.4960.101)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-02-24 10:38:54.1355 +0900
OS Version:            macOS 13.2.1 (22D68)
Report Version:        12
Anonymous UUID:        AF147A7A-C6C5-A270-D833-7A4CD8A7E744

Time Awake Since Boot: 670000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1acb52868 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1acb89cec pthread_kill + 288
2   libsystem_c.dylib             	       0x1acac22c8 abort + 180
3   QtCore                        	       0x10106ebb8 0x101054000 + 109496
4   QtCore                        	       0x10132f5c4 QMessageLogger::fatal(char const*, ...) const + 116
5   QtGui                         	       0x101b92bfc QGuiApplicationPrivate::createPlatformIntegration() + 7400
6   QtGui                         	       0x101b92c20 QGuiApplicationPrivate::createEventDispatcher() + 36
7   QtCore                        	       0x101237678 QCoreApplicationPrivate::init() + 1164
8   QtGui                         	       0x101b8cf68 QGuiApplicationPrivate::init() + 68
9   QtWidgets                     	       0x102695518 QApplicationPrivate::init() + 36
10  QtWidgets                     	       0x102695658 QApplication::QApplication(int&, char**, int) + 164
11  DictionaryTool                	       0x10081ff60 mozc::gui::GuiUtil::InitQt(int&, char**) + 160
12  DictionaryTool                	       0x1006f18bc RunDictionaryTool(int, char**) + 48
13  DictionaryTool                	       0x1006e2ff0 main + 48
14  dyld                          	       0x1ac85fe50 start + 2544

Thread 1:
0   libsystem_pthread.dylib       	       0x1acb84e18 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1acb84e18 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000230   x5: 0x0000000135305420   x6: 0x0000000000000023   x7: 0x0000000000000153
    x8: 0x966da03d919d08f0   x9: 0x966da03f998c49b0  x10: 0x0000000000000002  x11: 0x00000000fffffffd
   x12: 0x0000010000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x000000020cf776d8  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000208114140  x21: 0x0000000000000103  x22: 0x0000000208114220  x23: 0x000000013500f898
   x24: 0x0000000135104d00  x25: 0x00000000ffffffff  x26: 0x0000000000000001  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016f7230d0   lr: 0x00000001acb89cec
    sp: 0x000000016f7230b0   pc: 0x00000001acb52868 cpsr: 0x40001000
   far: 0x0000000101297284  esr: 0x56000080  Address size fault

Binary Images:
       0x1acb49000 -        0x1acb82feb libsystem_kernel.dylib (*) <3dcd49b9-b3c5-3d90-be40-a3b807cb9cd7> /usr/lib/system/libsystem_kernel.dylib
       0x1acb83000 -        0x1acb8fffb libsystem_pthread.dylib (*) <9f3b729a-ed04-3e65-adac-d75ad06ebbdc> /usr/lib/system/libsystem_pthread.dylib
       0x1aca49000 -        0x1acac9ffb libsystem_c.dylib (*) <14cd841b-0c7b-34a2-a342-cc6796ef9259> /usr/lib/system/libsystem_c.dylib
       0x101054000 -        0x1014f7fff org.qt-project.QtCore (5.15) <76ae5967-adb7-3210-9ee2-241f50a56a2e> /opt/homebrew/*/QtCore.framework/Versions/5/QtCore
       0x101b64000 -        0x101fcffff org.qt-project.QtGui (5.15) <90fc3777-ebdc-3512-b509-987988876d53> /opt/homebrew/*/QtGui.framework/Versions/5/QtGui
       0x102688000 -        0x102aa3fff org.qt-project.QtWidgets (5.15) <6af4673e-ed2a-3c9c-974c-d4fa05794b49> /opt/homebrew/*/QtWidgets.framework/Versions/5/QtWidgets
       0x1006dc000 -        0x100907fff org.mozc.inputmethod.Japanese.Tool.DictionaryTool (2.28.4960) <9b62fe6c-5081-3750-b0f5-18773595c5aa> /Library/Input Methods/Mozc.app/Contents/Resources/DictionaryTool.app/Contents/MacOS/DictionaryTool
       0x1ac85a000 -        0x1ac8e4ba3 dyld (*) <191e84f1-4b95-39c8-b253-1c1ef56c0fa8> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=990.1M resident=0K(0%) swapped_out_or_unallocated=990.1M(100%)
Writable regions: Total=271.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=271.5M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Dispatch continuations            80.0M        1 
Kernel Alloc Once                   32K        1 
MALLOC                            62.1M       19 
MALLOC guard page                   96K        5 
MALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        3 
Stack                             9264K        3 
VM_ALLOCATE                         16K        1 
__AUTH                             572K      132 
__AUTH_CONST                      10.3M      276 
__DATA                            3052K      276 
__DATA_CONST                      13.9M      289 
__DATA_DIRTY                       678K       97 
__FONT_DATA                        2352        1 
__LINKEDIT                       772.3M       13 
__OBJC_CONST                      1161K      107 
__OBJC_RO                         65.5M        1 
__OBJC_RW                         1988K        1 
__TEXT                           217.8M      304 
dyld private memory                256K        1 
mapped file                       29.3M        4 
shared memory                     1136K        7 
===========                     =======  ======= 
TOTAL                              1.4G     1544 
TOTAL, minus reserved VM space     1.3G     1544 

-----------
Full Report
-----------

{"app_name":"DictionaryTool","timestamp":"2023-02-24 10:38:54.00 +0900","app_version":"2.28.4960","slice_uuid":"9b62fe6c-5081-3750-b0f5-18773595c5aa","build_version":"2.28.4960.101","platform":1,"bundleID":"org.mozc.inputmethod.Japanese.Tool.DictionaryTool","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.2.1 (22D68)","roots_installed":0,"name":"DictionaryTool","incident_id":"423A1FA7-EA41-4A50-AA96-42EEC4BD7D7A"}
{
  "uptime" : 670000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac13,1",
  "coalitionID" : 70508,
  "osVersion" : {
    "train" : "macOS 13.2.1",
    "build" : "22D68",
    "releaseType" : "User"
  },
  "captureTime" : "2023-02-24 10:38:54.1355 +0900",
  "incident" : "423A1FA7-EA41-4A50-AA96-42EEC4BD7D7A",
  "pid" : 40058,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-02-24 10:38:53.9861 +0900",
  "procStartAbsTime" : 16302109286960,
  "procExitAbsTime" : 16302112341938,
  "procName" : "DictionaryTool",
  "procPath" : "\/Library\/Input Methods\/Mozc.app\/Contents\/Resources\/DictionaryTool.app\/Contents\/MacOS\/DictionaryTool",
  "bundleInfo" : {"CFBundleShortVersionString":"2.28.4960","CFBundleVersion":"2.28.4960.101","CFBundleIdentifier":"org.mozc.inputmethod.Japanese.Tool.DictionaryTool"},
  "storeInfo" : {"deviceIdentifierForVendor":"53C3568C-B64F-5C4A-A4B5-486E95BE752B","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.mozc.inputmethod.Japanese.Tool.DictionaryTool",
  "crashReporterKey" : "AF147A7A-C6C5-A270-D833-7A4CD8A7E744",
  "throttleTimeout" : 2147483647,
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":9198098,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":560},{"value":5187327008},{"value":35},{"value":339},{"value":10839496064447088880},{"value":10839496073170143664},{"value":2},{"value":4294967293},{"value":1099511627776},{"value":0},{"value":0},{"value":0},{"value":328},{"value":8807479000},{"value":0},{"value":6},{"value":8725283136,"symbolLocation":0,"symbol":"_main_thread"},{"value":259},{"value":8725283360,"symbolLocation":224,"symbol":"_main_thread"},{"value":5184223384},{"value":5185228032},{"value":4294967295},{"value":1},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":7192747244},"cpsr":{"value":1073745920},"fp":{"value":6164721872},"sp":{"value":6164721840},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7192520808,"matchesCrashFrame":1},"far":{"value":4314460804}},"queue":"com.apple.main-thread","frames":[{"imageOffset":39016,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":0},{"imageOffset":27884,"symbol":"pthread_kill","symbolLocation":288,"imageIndex":1},{"imageOffset":496328,"symbol":"abort","symbolLocation":180,"imageIndex":2},{"imageOffset":109496,"imageIndex":3},{"imageOffset":2995652,"symbol":"QMessageLogger::fatal(char const*, ...) const","symbolLocation":116,"imageIndex":3},{"imageOffset":191484,"symbol":"QGuiApplicationPrivate::createPlatformIntegration()","symbolLocation":7400,"imageIndex":4},{"imageOffset":191520,"symbol":"QGuiApplicationPrivate::createEventDispatcher()","symbolLocation":36,"imageIndex":4},{"imageOffset":1980024,"symbol":"QCoreApplicationPrivate::init()","symbolLocation":1164,"imageIndex":3},{"imageOffset":167784,"symbol":"QGuiApplicationPrivate::init()","symbolLocation":68,"imageIndex":4},{"imageOffset":54552,"symbol":"QApplicationPrivate::init()","symbolLocation":36,"imageIndex":5},{"imageOffset":54872,"symbol":"QApplication::QApplication(int&, char**, int)","symbolLocation":164,"imageIndex":5},{"imageOffset":1326944,"symbol":"mozc::gui::GuiUtil::InitQt(int&, char**)","symbolLocation":160,"imageIndex":6},{"imageOffset":88252,"symbol":"RunDictionaryTool(int, char**)","symbolLocation":48,"imageIndex":6},{"imageOffset":28656,"symbol":"main","symbolLocation":48,"imageIndex":6},{"imageOffset":24144,"symbol":"start","symbolLocation":2544,"imageIndex":7}]},{"id":9198126,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":9198127,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7192481792,
    "size" : 237548,
    "uuid" : "3dcd49b9-b3c5-3d90-be40-a3b807cb9cd7",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7192719360,
    "size" : 53244,
    "uuid" : "9f3b729a-ed04-3e65-adac-d75ad06ebbdc",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7191433216,
    "size" : 528380,
    "uuid" : "14cd841b-0c7b-34a2-a342-cc6796ef9259",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4312088576,
    "CFBundleShortVersionString" : "5.15",
    "CFBundleIdentifier" : "org.qt-project.QtCore",
    "size" : 4866048,
    "uuid" : "76ae5967-adb7-3210-9ee2-241f50a56a2e",
    "path" : "\/opt\/homebrew\/*\/QtCore.framework\/Versions\/5\/QtCore",
    "name" : "QtCore",
    "CFBundleVersion" : "5.15.8"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4323688448,
    "CFBundleShortVersionString" : "5.15",
    "CFBundleIdentifier" : "org.qt-project.QtGui",
    "size" : 4636672,
    "uuid" : "90fc3777-ebdc-3512-b509-987988876d53",
    "path" : "\/opt\/homebrew\/*\/QtGui.framework\/Versions\/5\/QtGui",
    "name" : "QtGui",
    "CFBundleVersion" : "5.15.8"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4335370240,
    "CFBundleShortVersionString" : "5.15",
    "CFBundleIdentifier" : "org.qt-project.QtWidgets",
    "size" : 4308992,
    "uuid" : "6af4673e-ed2a-3c9c-974c-d4fa05794b49",
    "path" : "\/opt\/homebrew\/*\/QtWidgets.framework\/Versions\/5\/QtWidgets",
    "name" : "QtWidgets",
    "CFBundleVersion" : "5.15.8"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4302159872,
    "CFBundleShortVersionString" : "2.28.4960",
    "CFBundleIdentifier" : "org.mozc.inputmethod.Japanese.Tool.DictionaryTool",
    "size" : 2277376,
    "uuid" : "9b62fe6c-5081-3750-b0f5-18773595c5aa",
    "path" : "\/Library\/Input Methods\/Mozc.app\/Contents\/Resources\/DictionaryTool.app\/Contents\/MacOS\/DictionaryTool",
    "name" : "DictionaryTool",
    "CFBundleVersion" : "2.28.4960.101"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7189405696,
    "size" : 568228,
    "uuid" : "191e84f1-4b95-39c8-b253-1c1ef56c0fa8",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 7188758528,
  "size" : 3447455744,
  "uuid" : "835716ae-b363-3187-b065-cf94139bfc85"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=990.1M resident=0K(0%) swapped_out_or_unallocated=990.1M(100%)\nWritable regions: Total=271.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=271.5M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nDispatch continuations            80.0M        1 \nKernel Alloc Once                   32K        1 \nMALLOC                            62.1M       19 \nMALLOC guard page                   96K        5 \nMALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M        3 \nStack                             9264K        3 \nVM_ALLOCATE                         16K        1 \n__AUTH                             572K      132 \n__AUTH_CONST                      10.3M      276 \n__DATA                            3052K      276 \n__DATA_CONST                      13.9M      289 \n__DATA_DIRTY                       678K       97 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       772.3M       13 \n__OBJC_CONST                      1161K      107 \n__OBJC_RO                         65.5M        1 \n__OBJC_RW                         1988K        1 \n__TEXT                           217.8M      304 \ndyld private memory                256K        1 \nmapped file                       29.3M        4 \nshared memory                     1136K        7 \n===========                     =======  ======= \nTOTAL                              1.4G     1544 \nTOTAL, minus reserved VM space     1.3G     1544 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "62cdf63ddb3b7109d6d765cc",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_TMDC" : "62cdf6dddb3b7109d6d765cd"
      },
      "deploymentId" : 240000007
    },
    {
      "rolloutId" : "62b4513af75dc926494899c6",
      "factorPackIds" : {
        "COREOS_ICD" : "62fbe3cfa9a700130f60b3ea"
      },
      "deploymentId" : 240000019
    }
  ],
  "experiments" : [

  ]
}
}

Model: Mac13,1, BootROM 8419.80.7, proc 10:8:2 processors, 64 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: LG HDR 4K, 6720 x 3780, Main, MirrorOff, Online
Display: LG HDR 4K, 6720 x 3780, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Nov 30 2022 02:49:13 version 20.10.965.13.8.7.131 FWID 01-c3a524b8
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Tailscale Tunnel, VPN (io.tailscale.ipn.macos), utun3
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.1 Hub
USB Device: USB2.0 Hub
USB Device: USB-C Digital AV Multiport Adapter
USB Device: USB31Bus
USB Device: USB2 Hub
USB Device: hub_device
USB Device: FeliCa Port/PaSoRi 4.0
USB Device: USB 2.0 Hub
USB Device: USB Charger
USB Device: M2
USB Device: YubiKey OTP+FIDO+CCID
USB Device: USB3 Gen2 Hub
USB Device: hub_device
Thunderbolt Bus: Mac Studio, Apple Inc.
Thunderbolt Bus: Mac Studio, Apple Inc.
Thunderbolt Bus: Mac Studio, Apple Inc.
Thunderbolt Bus: Mac Studio, Apple Inc.
</pre>
</details>

**Steps to reproduce**
1. Open ConfigDialog or DictionaryTool by:
  - IME Menu -> Mozc -> Preferences
  - IME Menu -> Mozc -> Dictionary Tool…
  - `open /Applications/Mozc/ConfigDialog.app`
  - `open /Applications/Mozc/DictionaryTool.app`
2. The app crashes.

**Expected behavior**
The app opened successfully.

**Actual behavior**
The app crashes immediately.

**Screenshots**
<img width="372" alt="image" src="https://user-images.githubusercontent.com/12772118/221072095-9c58a8d8-4b23-4d98-b7c0-80782c7eba89.png">

**Version or commit-id**
Mozc-2.28.4960.101+24.11.oss

**Environment**
 - OS: macOS 13.2.1 22D68 arm64
 - IMF (for Linux): N/A
 - Related Applications: N/A

**Investigations**
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + N/A
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + N/A
 - What applications this issue happens on (e.g. Chromium, gedit).
   + N/A
 - What applications this issue does not happen on (e.g. Chromium, gedit).
   + N/A
 - (optional) What versions or commit-ids this issue did not happen on
   (e.g. Mozc-2.28.4960.100+24.11.oss).
   + N/A

**Additional context**

**Comment by siketyan** [comment]
After rebuilding and reinstalling, it worked fine somehow.
If you do not know how the issue happen, could you please let me know and close this issue?

**Comment by hiroyuki-komatsu** [comment]
Hi siketyan,

That's nice that the issue has been resolved.

Looking at the log, the issue happened in Qt. So I guess the configuration or build of Qt was changed in your environment.

The following command shows the log in your terminal. When you get a similar error again, please try it too.

```
/Library/Input\ Methods/Mozc.app/Contents/Resources/AboutDialog.app/Contents/MacOS/AboutDialog --logtostderr
```

I'm going to close this issue. Thanks,

**Comment by siketyan** [comment]
Thank you for the investigation.

Maybe Qt path moved by upgrading them using Homebrew. As you may know Homebrew places formulas like Qt in the separated directory for each version (i.e. /opt/homebrew/Cellar/qt/x.y.z).

Since Mozc is linked to Qt dynamically, so upgrading it may occurs the error. I think there is a way to link Qt using the version-independent symlinked directory created by Homebrew, but by default it seems not used.

Anyway your investigation helped me a lot!
