### ISSUE TITLE
かな入力で"ー"を出すのにShiftキーを押す必要がある

### ISSUE THREAD

**Issue by ogadon** [google/mozc#693]
**Description**
かな入力で"ー"を入力しようとすると、"¥"が表示される。
Shiftキーを押すと"ー"を入力できるが正しくはないと思います。

**Steps to reproduce**
1. Mozcのツール→プロパティ→一般→基本設定→「ローマ字入力・かな入力」で「かな入力」を選択
2. 「半角/全角」キーで日本語入力モードにする。
3. [BackSpace]キー左の「|¥ー」の刻印のキーを押す

**Expected behavior**
4. 「ー」が入力されることを期待

**Actual behavior**
A clear and concise description of what you actually got.
4. 「¥」が入力される。
    (未変換文字の前に「¥」が入力される。)

**Screenshots**
e.g. 
キーボードで「は」「ー」「と」を入力すると
「¥はと」と入力される

**Version or commit-id**
[e.g. Mozc-2.28.4960.100+24.11.oss or d50a8b9ae28c4fba265f734b38bc5ae392fe4d25]
You can get the version string by converting "Version" or "ばーじょん".

$ dpkg -l | grep mozc
ii  ibus-mozc       2.20.2673.102+dfsg-2ubuntu0.18.04.1   amd64   Mozc engine for IBus - Client of the Mozc input method
ii  mozc-data       2.20.2673.102+dfsg-2ubuntu0.18.04.1   all          Mozc input method - data files
ii  mozc-server    2.20.2673.102+dfsg-2ubuntu0.18.04.1   amd64   Server of the Mozc input method
ii  mozc-utils-gui  2.20.2673.102+dfsg-2ubuntu0.18.04.1   amd64   GUI utilities of the Mozc input method

**Environment**
- OS: Ubuntu 18.04.6 LTS
- IMF: ibus
- Related Applications : Firefox, Vim

**Investigations**
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + N/A
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + N/A
 - What applications this issue happens on (e.g. Chromium, gedit).
   + Firefox, Vim
 - What applications this issue does not happen on (e.g. Chromium, gedit).
   + not-found
 - (optional) What versions or commit-ids this issue did not happen on
   (e.g. Mozc-2.28.4960.100+24.11.oss).
   + 2.20.2673.102+dfsg-2ubuntu0.18.04.1 

**Additional context**
- no other context

**Comment by hiroyuki-komatsu** [comment]
Hi ogadon,
Thank you for your feedback.

Your Mozc (2.20.2673) is a version 2300 days ago.
Would you check the recent version (2.28.5017) whether this problem happens?

If you need to use that version, you can modify and rebuild the logic of Kana input is in [unix/ibus/key_translator.cc](https://github.com/google/mozc/blob/master/src/unix/ibus/key_translator.cc).

**Comment by hiroyuki-komatsu** [comment]
I'm going to close this issue.
Please feel free to reopen it again as needed.

Thank you,
