### ISSUE TITLE
No Qt platform error

### ISSUE THREAD

**Issue by viasux** [google/mozc#694]
**Description**
It's possible this is a build error, but I get the following when I right click mozc in the windows system tray and hit properties:

**Steps to reproduce**
These are the commands I used to build:
cd C:\work\mozc\src
python build_mozc.py gyp --qtdir=C:\Qt\5.15.2\msvc2019 --msvs_version=2019
python build_mozc.py build -c Release package

I then followed the installation tutorial for 64bit (also happens on 32bit) and everything seemingly works until I try to open the preferences page.

**Expected behavior**
I expect the proper menu to appear.

**Actual behavior**
The screenshot attached ("This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.")

**Screenshots**
![image](https://user-images.githubusercontent.com/47131867/222031159-2e8ca436-b38a-4c3b-afd9-0d22b1af3efb.png)

**Version or commit-id**
Unsure, installed & downloaded today

**Environment**
 - Windows 10 21h1

**Investigations**
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + Yes? - I installed both, unsure if that could cause problems
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + Don't use others

**Additional context**
ありがとうぐざいます for any help <3

**Comment by hiroyuki-komatsu** [comment]
Hi viasux,

That error message comes from the Qt library.
I guess some configurations or rebuild of Qt may solve the problem.

By searching web pages with that error messages, removing or updating the following environment variables may change the situation.

* QT_PLUGIN_PATH
* QML2_IMPORT_PATH

However, I'm not so sure about the Qt configurations. I hope someone who are familiar with this issue would help this issue.

Thanks,

**Comment by yukawa** [comment]
The good news is that c7265ec5010b6b552d2be4fa7850d65d5208fc45 made it possible to build installer (`Mozc32.msi` and `Mozc64.msi`) with Qt dependencies. So you should no longer have to manually copy files by yourself. See our [latest build/installation instructions](https://github.com/google/mozc/blob/master/docs/build_mozc_in_windows.md) for details.

I'm going to close this issue as I've locally confirmed that the preference dialog can be launched without any error (in my Windows 11 environment) by installing Mozc with `Mozc64.msi`. Let us know if you still see some issues after installing Mozc with `Mozc64.msi`.

Thanks!

**Comment by hiroyuki-komatsu** [comment]
I close this issue.

please let us know If you still have the issue with the above possible solution.
Thanks,

**Comment by viasux** [comment]
> I close this issue.
> 
> please let us know If you still have the issue with the above possible solution. Thanks,

I've since switched to another solution. Thank you for all the help though!
