### ISSUE TITLE
Typing issue: 宇登呂（北海道斜里町の地名）

### ISSUE THREAD

**Issue by Hokkosha** [google/mozc#695]
**Category of the typing issue**
Choose one of them (delete rest of them)
1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

**Issues**
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
|うとろ| 宇登呂 |ウトロ,うとろ |

北海道斜里町の字名の旧表記です。
現在の行政地名にはカタカナの「ウトロ」が使用されていますが、「宇登呂郵便局」「宇登呂岬灯台」など施設名に漢字表記が残っているので、「ウトロ」より低い順位で変換候補に加えていただきたいです。

**Version or commit-id**
Mozc-2.28.4715.102+24.11.oss

**Additional context**

**Comment by hiroyuki-komatsu** [comment]
Hi Hokkosha,

d23536b added the word based on your feedback.

Thank you!

**Comment by hiroyuki-komatsu** [comment]
Ah sorry, the word has not been added yet.
I'm going to add it soon.

**Comment by hiroyuki-komatsu** [comment]
6e2edec added the words based on your feedback.
Thank you!
