### ISSUE TITLE
Typing issue: オホーツク・知床の地名

### ISSUE THREAD

**Issue by Hokkosha** [google/mozc#697]
**Category of the typing issue**
Choose one of them (delete rest of them)
1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

**Issues**
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| ちえんべつ | 知円別 | 遅延別,地縁別 |
| おんねべつ | 遠音別 | 温根別,遠音別岳 |
| さきむい | 崎無異 | 先無為 |
| うらしべつ | 浦士別 | 裏死別 |
| えとんびやま | 江鳶山 | 絵鳶山 |
| とっぷし | 富武士 | トップ市 |
| かっくみ | 活汲 | 各組 |
| みどり | 美禽 | みどり,緑 |
| ききん | 木禽 | 基金,飢饉 |
| いとしの | 愛し野 | 愛しの |
| おんねない | 音根内 | 恩根内,温根内 |

**Version or commit-id**
Mozc-2.28.4715.102+24.11.oss

**Additional context**
いずれもオホーツク沿岸や知床半島の山名及び字名です。

**Comment by hiroyuki-komatsu** [comment]
Hi Hokkosha,

Thank you for your report.
We are going to add words based on your feedback.

**Comment by hiroyuki-komatsu** [comment]
6e2edec added the words based on your feedback.
Thank you!
