### ISSUE TITLE
Typing issue: 圃場

### ISSUE THREAD

**Issue by nus** [google/mozc#701]
**Category of the typing issue**
Choose one of them (delete rest of them)
1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

**Issues**
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| ほじょう | 圃場 | ほ場 |

"ほ場" だけでなく漢字のみでの表記も加えていただきたいです。

**Version or commit-id**
Mozc-2.28.5029.101+24.11.oss

**Additional context**

**Comment by hiroyuki-komatsu** [comment]
PR#703 added this entry.
Thank you!
