### ISSUE TITLE
Typing issue: 桑田佳祐

### ISSUE THREAD

**Issue by Hokkosha** [google/mozc#709]
**Category of the typing issue**
1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

**Issues**
| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
|----------|----------|----------|
| くわたけいすけ | 桑田佳祐 | 桑田佳祐のやさしい夜遊び,桑竹居助|

**Version or commit-id**
Mozc-2.28.4715.102+24.11.oss

**Additional context**
桑田佳祐氏は日本の著名な歌手ですが、氏名を入力しようとしたらラジオ番組のタイトル「桑田佳祐のやさしい夜遊び」が選択候補の1位になり、ただの姓名のみの候補は出てきませんでした。改善を希望します。

**Comment by utuhiro78** [comment]
開発者ではありませんが、Mozc の最新版は
[Mozc-2.28.5065.102+24.11.oss](https://github.com/google/mozc/tree/master/src/data/version) です。

このバージョンで「くわたけいすけ」を変換すると、
「桑田圭介」になります。
「桑田」は1番目、「佳祐」は3番目の候補。
Mozc の辞書は、基本的に著名人の名前を収録していないと思います。

> 「桑田佳祐のやさしい夜遊び」が選択候補の1位になり、

今年1月時点の辞書を確認したところ、このようになっていました。

> くわたけいすけ	1925	1925	7949	桑竹居助
> くわたけいすけのやさしいよあそび	1919	1918	6624	桑田佳祐のやさしい夜遊び


「桑田佳祐のやさしい夜遊び」はサジェスト（提案）候補だと思います。
入力される言葉を予期して表示される候補。
「くわたけいすけ」と入力してスペースキーを押したときの第1候補は、
「桑竹居助」になると思います。

**Comment by hiroyuki-komatsu** [comment]
8646bf9 added the word based on your feedback.
Thank you!
