### ISSUE TITLE
Typing issue: 機会が泊まる

### ISSUE THREAD

**Issue by utuhiro78** [google/mozc#710]
**Category of the typing issue**
3. "機械が止まる" is not converted as expected.

**Issues**
| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| きかい | 機械 | 機会 |
| とまる | 止まる | 泊まる |

**Version or commit-id**
Mozc-2.28.5065.102+24.11.oss

**Additional context**
どうががとまる => 
動画が泊まる (NG)
動画が止まる (OK)

くるまがとまる => 
車が泊まる (NG)
車が止まる (OK)

くるまがとまっている => 
車が止まっている (OK)

Thank you for your development!

**Comment by hiroyuki-komatsu** [comment]
Hi utuhiro78,

d23536b updated test cases based on this issue.
ca75f3d updated the collocation data based on this issue.

Thank you for your feedback.
