### ISSUE TITLE
Typing issue: 制度が低い

### ISSUE THREAD

**Issue by utuhiro78** [google/mozc#711]
**Category of the typing issue**
3. "精度が低い" is not converted as expected.

**Issues**
| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| せいど | 精度 | 制度 |

**Version or commit-id**
Mozc-2.28.5065.102+24.11.oss

**Additional context**
せいどがたかい =>
制度が高い (NG)
精度が高い (OK)

**Comment by hiroyuki-komatsu** [comment]
Hi utuhiro78,

d23536b updated test cases based on this issue.
ca75f3d updated the collocation data based on this issue.

Thank you for your feedback.

**Comment by utuhiro78** [comment]
Thank you.
