### ISSUE TITLE
Build error: jsoncpp is not removed from gitmodules.

### ISSUE THREAD

**Issue by wengxt** [google/mozc#714]
**Description**
While src/third_party/jsoncpp is removed, the .gitmodules is not updated which would trigger git error when checkout a new repository.

**Commit-id**
This commit wrongly added the remove gitmodules back: https://github.com/google/mozc/commit/255f4f4d889a7086eb5aaeaf65e4223f47a9fbce

**Comment by hiroyuki-komatsu** [comment]
Hi wengxt,
Thank you for your report.

I accidentally rolled back .gitmodules to the previous version.
I'm going to fix it soon.

Best,

**Comment by hiroyuki-komatsu** [comment]
[0f08893](https://github.com/google/mozc/commit/0f08893601a175137d5391f5a5c8b82d77c12fab) removed jsoncpp from .gtimodules again.

Thank you,
