### ISSUE TITLE
[macOS] Suggesting implementing a null-checker for parameters passed to handleEvent:client: function.

### ISSUE THREAD

**Issue by ShikiSuen** [google/mozc#735]
The `handleEvent:client:` function in IMKInputController can sometimes receive nulled NSEvents, e.g. Click-inputting Emojis through macOS built-in Emoji panel.

I don't know why this doesn't cause a crash when a subclassed IMKInputController class is written in ObjC, but this will cause crash if such class is written in Swift.

Therefore, this issue is `only a suggestion`: Please consider adding a null-check for the parameter `event` in the following place (between line 855 and 856): If the event is null, then immediately return false and abort this function.

https://github.com/google/mozc/blob/811cb8c7606a4732a83abb89752664eb23728623/src/mac/GoogleJapaneseInputController.mm#L855-L856

P.S.: I am not an ObjC dev, hence being unable to provide a pull-request by myself. Sorry for the inconveniences.

**Comment by hiroyuki-komatsu** [comment]
Thank you ShikiSuen for your feedback.

9b0019d added the check based on your suggestion.
We hope it works.

**Comment by ShikiSuen** [comment]
@hiroyuki-komatsu ご対応ありがとうございます。これで大丈夫です。

**Comment by ShikiSuen** [comment]
Oh, I'm sorry that I forgot a thing: NSNull and nullptr are not equivalent. Both of them needs to be checked.

According to Apple:
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/NumbersandValues/Articles/Null.html

> The NSNull instance is semantically equivalent to nil, however it is also important to appreciate that **it is not equal to nil**. To test for a null object value, you must therefore make a direct object comparison.

I guess that the commit 9b0019d might need a further modification to check NSNull together:
```
if (event == nullptr || event == NSNull) {
    return NO;
}
```

**Comment by ShikiSuen** [comment]
... my usage of NSNull in the codeblock above might be completely wrong in Objective-C.
I wonder whether this is correct:
```
if (event == nullptr || event == [NSNull null]) {
    return NO;
}
```

**Comment by ShikiSuen** [comment]
I just sent a PR to add the check for NSNull:
https://github.com/google/mozc/pull/745

**Comment by hiroyuki-komatsu** [comment]
Thank you for your PR!

However, unfortunately, src/mac is not yet a directory that we can accept PRs.
Sorry for your inconvenience. 
* https://github.com/google/mozc/blob/master/CONTRIBUTING.md

I'm going to a change based on your feedback.
Best,

**Comment by hiroyuki-komatsu** [comment]
1d19e7a1072d73f48c6f176210ef61226edef5f0 added the check with NSNull.
Would you confirm this change?

**Comment by hiroyuki-komatsu** [comment]
Indeed, I wrote `event == [NSNull null]` at first, but I got an error of type mismatch between `NSEvent` and `NSNull`.
So I changed it to the `isEqual` one.

I guess using `id == NSNull` is OK, but `NSEvent == NSNull` is not OK.
