### ISSUE TITLE
Typing issue: 対象外

### ISSUE THREAD

**Issue by makiuchi-d** [google/mozc#766]
**Category of the typing issue**
Choose one of them (delete rest of them)
3. Conversion issue (e.g. "夕日がきれい" is not converted as expected).

**Issues**
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| たいしょうがい | 対象外 | 大賞害 |

**Version or commit-id**
[e.g. Mozc-2.28.4960.100+24.11.oss or d50a8b9ae28c4fba265f734b38bc5ae392fe4d25]
You can get the version string by converting "Version" or "ばーじょん".
Mozc-2.23.2815.102+24.2.oss

**Comment by hiroyuki-komatsu** [comment]
[932ee43](https://github.com/google/mozc/commit/932ee4324f065460078bb725e586107332a0f5ad) added the words based on your feedback.

Thank you!
