### ISSUE TITLE
Typing issue: 最終/決定/修正/改定稿

### ISSUE THREAD

**Issue by ftake** [google/mozc#768]
**Category of the typing issue**
Choose one of them (delete rest of them)
1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

**Issues**
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| さいしゅうこう | 最終稿  | 最終校 |
| けっていこう | 決定稿 | 決定校 |
| しゅうせいこう | 修正稿 | 週成功 |
| かいていこう | 改訂稿 | 書いていこう |

**Version or commit-id**
[e.g. Mozc-2.28.4960.100+24.11.oss or d50a8b9ae28c4fba265f734b38bc5ae392fe4d25]
You can get the version string by converting "Version" or "ばーじょん".
Mozc-2.29.5111.102+24.11.oss

**Additional context**

**Comment by hiroyuki-komatsu** [comment]
[0cf3e92](https://github.com/google/mozc/commit/0cf3e926112300c61e632a9ab0915fcd6eaed003) added words based on your feedback.

Thank you!
