### ISSUE TITLE
Clicking on "open source software" in the mozc about window does nothing.

### ISSUE THREAD

**Issue by jrom99** [google/mozc#777]
## Description
Clicking on "open source software" in the mozc about window does nothing.

## Steps to reproduce
1. Run `/usr/lib/mozc/mozc_tool`
2. Click on 'open source software'

## Expected behavior
A window or webpage is opened.

## Actual behavior
Nothing happens. The following message appears in the terminal:

```
gio: file:///usr/lib/mozc/documents/credits_en.html: Error when getting information for file “/usr/lib/mozc/documents/credits_en.html”: No such file or directory
```

## Screenshots
![image](https://github.com/google/mozc/assets/47498278/3f3b6e27-1773-4c4f-b2f1-a5383795b8fb)

## Version or commit-id
Mozc-2.28.4715.102+24.11.oss

## Environment
 - OS: Ubuntu 23.04
 - IMF (for Linux): I don't know how to check, but maybe ibus

## Investigations
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + no-investigation
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + no-investigation
 - What applications this issue happens on (e.g. Chromium, gedit).
   + not applicable
 - What applications this issue does not happen on (e.g. Chromium, gedit).
   + not applicable
 - (optional) What versions or commit-ids this issue did not happen on
   (e.g. Mozc-2.28.4960.100+24.11.oss).
   + no-investigation.

**Comment by yukawa** [comment]
Thank you for the report.

This looks to be an issue in Debian/Ubuntu packaging, not in the Mozc code itself. Our code by default expects the HTML file to be installed as `/usr/lib/mozc/documents/credits_en.html`, but it seems the file is not installed correctly in [Ubuntu 23.04](https://git.launchpad.net/ubuntu/+source/mozc/tree/debian?h=applied/ubuntu/lunar).

https://github.com/google/mozc/blob/b6aa2a31255f83b248de93eee99d07ecee795799/src/base/base.gyp#L34

Can you please report this to Ubuntu team?
It seems you can do so at https://bugs.launchpad.net/ubuntu/+source/mozc/+filebug

Thanks!

**Comment by jrom99** [comment]
Reported https://bugs.launchpad.net/ubuntu/+source/mozc/+bug/2028730

I know this is the wrong place to ask, but I'd like to confirm if mozc supports dark mode. I've installed Ubuntu today and set it to "dark style", but all mozc windows have a white background (except for the top panel and typing suggestions).

**Comment by yukawa** [comment]
> I know this is the wrong place to ask, but I'd like to confirm if mozc supports dark mode. I've installed Ubuntu today and set it to "dark style", but all mozc windows have a white background (except for the top panel and typing suggestions).

Mozc doesn't support dark mode yet.  The team is currently working hard to clean up legacy code and I guess it'd takes several months to complete. Once it's done, it'd be more easily to work on features like dark mode.

For that kind of questions, feel free to use our discussion forum.
https://github.com/google/mozc/discussions
