### ISSUE TITLE
Mozc Input Not Activating Properly When Switching from Non-Latin Language via Ibus

### ISSUE THREAD

**Issue by FlyingButteryTuna** [google/mozc#782]
## Description
When switching from a Non-latin language (e.g., Russian, Armenian, Greek, etc.) to Mozc using ibus, the input remains in the language you switched from instead of switching to the expected Japanese input.

## Steps to reproduce
1. Add any non-latin language in Ibus.
2. Switch to the selected non-latin language.
3. Type something in the selected non-latin language.
4. Switch to Mozc input.
5. Type something

## Expected behavior
After switching to Mozc input, the actual input should be in the JP.

## Actual behavior
The input remains in the previously selected non-latin language instead of switching to Mozc input.

## Screenshots
https://github.com/google/mozc/assets/67516242/8da52dec-1850-4e27-acf4-698653d733ca

## Version or commit-id
Version: 2.29.5160.102-1

## Environment
OS: Arch Linux x86_64
Kernel: 6.4.6-arch1-1
Input Method Framework (IMF) for Linux: Ibus
Related Applications: Any application where user input is allowed

### Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
specific to Ibus; Mozc on fcitx works as expected (I'm assuming that's the case for uim and other IMFs too).

### Whether this issue happens on other IMEs (e.g. Anthy, SKK).
N/A

### What applications this issue happens on (e.g. Chromium, gedit).
occurs in any application that allows user input.

### What applications this issue does not happen on (e.g. Chromium, gedit).
N/A

### (optional) What versions or commit-ids this issue did not happen on
no-investigation, but it's been there for at least 5 years (had the same issue on Debain + Ibus around that time).

## Additional context
Switching to English input and then switching to Mozc does fix this issue, so I assume the issue is related to some sort of initial input (keymap layout?).

**Comment by hiroyuki-komatsu** [comment]
Hi FlyingButteryTuna,
Thank you for your feedback with detailed investigations and the screen record. They are very helpful for us.

For Japanese input, Ibus uses the keyboard layout you previously used by default. You can specify the keyboard layout by modifying `~/.config/mozc/ibus_config.textproto`.

The details are described in [mozc/docs/configurations.md at master · google/mozc](https://github.com/google/mozc/blob/master/docs/configurations.md#ibus).

You might want to change `layout : "default"` to `layout : "ja"` or other specific layout. Then run `ibus write-cache; ibus restart`.

Thanks,

**Comment by hiroyuki-komatsu** [comment]
It should be a common issue for users of non-latin languages.
Your question is valuable to share the problem and solution.

Thank you!
