### ISSUE TITLE
"terekomu" → テレ込む

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#82]
```
When I type "terekomu" and transform, the IME does not propose テレコム (a 
very usual word) but テレ込む which makes no sense.

I had noticed IBus-Anthy had the same problem, so that's why I switched to 
mozc, but it seems to have the same problem. Can anyone confirm?
```

Original issue reported on code.google.com by `nicolas.raoul@gmail.com` on 9 May 2011 at 1:14

**Comment by hiroyuki-komatsu** [comment]
Added evaluation test cases in this issue.

* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv
