### ISSUE TITLE
Mozc Renderer: Windows are not placed under the cursor with HiDPI display

### ISSUE THREAD

**Issue by ftake** [google/mozc#823]
## Description
Qt6 does not support AA_EnableHighDpiScaling as mentioned in compiler warnings.

```
renderer/qt/qt_server.cc:109:34: warning: 'Qt::AA_EnableHighDpiScaling' is deprecated: High-DPI scaling is always enabled.
This attribute no longer has any effect. [-Wdeprecated-declarations]
 109 |   QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
```

It now always uses virtual pixels. However, IBus only knows about device pixels and it sends a preedit rect in device pixel coordinates. Thus, a candidate window is usually placed bottom-right of the appropriate place.

## Steps to reproduce
1. Set display DPI to 120
2. Open gEdit, type some keys
3. The suggestion window and candidate window is not shown in a correct place

## Screenshots
![Screenshot_20231017_222954](https://github.com/google/mozc/assets/160235/34764de2-8fb2-4d72-b356-57a56035505c)

## Version or commit-id
Mozc-2.29.5220.102+24.11.oss

## Environment
 - OS: openSUSE Leap 15.5, 
 - IMF (for Linux): IBus 1.5.25
 - Related Applications
   * Qt 6.4.2
   * KDE Plasma 5.27.4.1-bp155.1.7

## Investigations
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + N/A
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + N/A
 - What applications this issue happens on (e.g. Chromium, gedit).
   + gEdit, VSCode
 - What applications this issue does not happen on (e.g. Chromium, gedit).
 - (optional) What versions or commit-ids this issue did not happen on
   (e.g. Mozc-2.28.4960.100+24.11.oss).
   + list of versions or commit-ids, or no-investigation.

## Additional context

* I cannot find any function that converts device pixels to virtual. We might need to talk with the Qt community.
* Here is Qt-side code that converts virtual to device   
   https://codereview.qt-project.org/c/qt/qtbase/+/451617/2/src/plugins/platforminputcontexts/ibus/qibusplatforminputcontext.cpp
* Workaround: `QT_ENABLE_HIGHDPI_SCALING=0 /usr/lib64/mozc/mozc_renderer`
   * https://doc.qt.io/qt-6/highdpi.html

**Comment by yukawa** [comment]
> I cannot find any function that converts device pixels to virtual.

I think what you need to do is just divide the virtual screen coordinates with device pixel ratio, as explained [the Qt document you linked](https://doc.qt.io/qt-6/highdpi.html#conceptual-model).
> For example, creating a [QWindow](https://doc.qt.io/qt-6/qwindow.html) or [QWidget](https://doc.qt.io/qt-6/qwidget.html), and setting its size to 200x200 will cover 200x200 display pixels on a normal density display (with a device pixel ratio of 1.0), but will cover 400x400 pixels on a high density display (with a device pixel ratio of 2.0).

The device pixel ratio mentioned here can be obtained with [`QScreen::devicePixelRatio()`](https://doc.qt.io/qt-6/qscreen.html#devicePixelRatio-prop), and Given that X11 doesn't support per-display DPI, I guess you can simply use primary display's device pixel ratio.
```
const auto dpr = QGuiApplication::primaryScreen()->devicePixelRatio();
```

Can you confirm that 1) `QGuiApplication::primaryScreen()->devicePixelRatio()` is higher than `1.0` in your environment and 2) dividing the screen coordinates provided by IBus with `QGuiApplication::primaryScreen()->devicePixelRatio()` gives us the virtual screen coordinates that Qt relies on?

**Comment by ftake** [comment]
> 1) `QGuiApplication::primaryScreen()->devicePixelRatio()` is higher than 1.0 in your environment

It is 1.25

> 2) dividing the screen coordinates provided by IBus with QGuiApplication::primaryScreen()->devicePixelRatio() gives us the virtual screen coordinates that Qt relies on?

Unfortunately, no because the virtual coordinates of two displays are not continuous even if they are physically continuous, and the point of virtual top-left is the same as physical.

![Screenshot_20231105_235809](https://github.com/google/mozc/assets/160235/a8e162a5-6409-49f4-aba4-f6fef6b1af47)

It seems that we can convert physical coordinate (x, y) to virtual by checking `((x - left) / ratio, (y - top) / ratio)) < (width, height)` for each screen.
