### ISSUE TITLE
Remove `third_party/ipa_font`

### ISSUE THREAD

**Issue by yukawa** [google/mozc#842]
## Description
Files under [`third_party/ipa_font`](https://github.com/google/mozc/blob/ddd9730b068387631e3b4d212314ef0ed93befe0/src/third_party/ipa_font/) are currently used only from the rendering test for Windows.

https://github.com/google/mozc/blob/ddd9730b068387631e3b4d212314ef0ed93befe0/src/base/win32/win_font_test_helper.cc#L92-L108

In theory, a simple font that only contains a single glyph for `A` should be sufficient for our use cases.

Let's create our own test font and update our tests to use it so that we can reduce our third party dependencies.

## Version or commit-id
ddd9730b068387631e3b4d212314ef0ed93befe0

**Comment by hiroyuki-komatsu** [comment]
b82b8de95f48088a96f063032bc543218c98b6a1 removed `third_party/ipa_font`.
