### ISSUE TITLE
Build error: third_party/wil should be referenced as @com_microsoft_wil//:wil

### ISSUE THREAD

**Issue by wengxt** [google/mozc#859]
## Description
Current way of writing it doesn't break linux build, but breaks some bazel related, e.g. bazel fetch/ bazel query command.

For example, 

$ bazel query  'deps(//base:mmap)'
ERROR: Evaluation of query "deps(//base:mmap)" failed: preloading transitive closure failed: no such package 'third_party/wil': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.

## Commit-id
b96c8d55a0ed188f3c08ef0d3615efbe8a3eb5dd

## Build target
N/A I believe, but I ran the command under Linux

## CI build status
passing

## Environment
 - OS: Archlinux
 - bazel 6.4.0

## Build commands
Steps of command lines to reproduce your error.
bazel query  'deps(//base:mmap)'

## Error logs
ERROR: Evaluation of query "deps(//base:mmap)" failed: preloading transitive closure failed: no such package 'third_party/wil': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.

## Additional context
If I manually replace all third_party/wil in deps as @com_microsoft_wil//:wil, error will be resolved.

**Comment by hiroyuki-komatsu** [comment]
Hi wengxt,

Thank you for your report. We were able to reproduce the error.

We will fix this issue.

**Comment by hiroyuki-komatsu** [comment]
76843e0 fixed the error.
Thank you,
