### ISSUE TITLE
Typing issue: 取り損なって/た

### ISSUE THREAD

**Issue by chizuchizu** [google/mozc#865]
## Category of the typing issue
Choose one of them (delete rest of them)
2. Word ranking issue (e.g. "夕日" is in the list, but ranking is lower than expected).

## Issues
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| とりそこなって | 取り損なって | 取り残って |
| とりそこなった | 取り損なった | 取り残った |

## Version or commit-id
GoogleJapaneseInput-2.28.5050.1+24.11.9

**Comment by hiroyuki-komatsu** [comment]
Hi chizuchizu,
Thank you for your report.

381859f194acb9fa5bf52ddd2cc5e36fdd194f8b added a test case to track this issue.
