### ISSUE TITLE
IPC connection denied on start-up

### ISSUE THREAD

**Issue by k0aaa** [google/mozc#881]
## Description
On linux, with the latest commit and fcitx5, mozc claims that "互換性のない変換エンジンプログラムに接続しています" when being enabled.
The log (at log level 0) reveals the following error messages:

> kwin_wayland_wrapper[4816]: WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
> kwin_wayland_wrapper[4816]: W0000 00:00:1709070134.528216    4816 unix_ipc.cc:277] connect failed: 接続を拒否されました
> kwin_wayland_wrapper[4816]: W0000 00:00:1709070134.528260    4816 unix_ipc.cc:277] connect failed: 接続を拒否されました
> kwin_wayland_wrapper[4816]: E0000 00:00:1709070134.528267    4816 client.cc:596] Connection failure to session
> kwin_wayland_wrapper[4816]: W0000 00:00:1709070134.528560    4816 unix_ipc.cc:277] connect failed: 接続を拒否されました
> kwin_wayland_wrapper[4816]: W0000 00:00:1709070134.528587    4816 unix_ipc.cc:277] connect failed: 接続を拒否されました
> kwin_wayland_wrapper[4816]: E0000 00:00:1709070134.528592    4816 client.cc:596] Connection failure to session
> kwin_wayland_wrapper[5490]: WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
> kwin_wayland_wrapper[5490]: E0000 00:00:1709070134.530638    5490 tiny_storage.cc:131] the file is missing the header.
> kwin_wayland_wrapper[5490]: E0000 00:00:1709070134.530669    5490 registry.cc:73] cannot open registry
> kwin_wayland_wrapper[4816]: E0000 00:00:1709070134.729669    4816 message_lite.cc:124] Can't parse message of type "mozc.commands.Output" because it is missing required fields: engine_reload_response.status
> kwin_wayland_wrapper[4816]: E0000 00:00:1709070134.731103    4816 client.cc:709] Parse failure of the result of the request:
> kwin_wayland_wrapper[4816]: E0000 00:00:1709070134.731126    4816 client.cc:812] Call() failed
> kwin_wayland_wrapper[4816]: E0000 00:00:1709070134.731130    4816 client.cc:472] CheckVersionOrRestartServer() failed
> kwin_wayland_wrapper[4816]: E0000 00:00:1709070134.731136    4816 client.cc:201] CreateSession failed
> kwin_wayland_wrapper[4816]: E0000 00:00:1709070134.731140    4816 server_launcher.cc:245] OnFatal is called: 1
> kwin_wayland_wrapper[4816]: E0000 00:00:1709070134.731321    4816 client.cc:374] EnsureSession failed
> kwin_wayland_wrapper[4816]: E0000 00:00:1709070134.731335    4816 client.cc:374] EnsureSession failed

If mozc enables when the desktop environment is starting up, it could crash the environment. (Happens with KDE wayland)
Weirdly, mozc continues to function after the error message.

Commit: 8eddfbaaeb2ff64512f17e32eadef5c7cbac9457

## Environment
 - OS: Arch Linux
 - IMF (for Linux) Fcitx5
 - Related Applications none

## Investigations
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + N/A
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + no
 - What applications this issue happens on (e.g. Chromium, gedit).
   + any
 - What applications this issue does not happen on (e.g. Chromium, gedit).
   + none
 - (optional) What versions or commit-ids this issue did not happen on
   + Mozc-2.29.5374.102+24.11.oss and prior

**Comment by yukawa** [comment]
Reproduced a similar symptom on Windows 11.

Quick bisection in my local environment shows that this issue started happening from 34d479b73e3ed10196a488010f43abcdb54bd03a.

**Comment by utuhiro78** [comment]
> * Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
>   
>   * N/A

It happens on IBus and Fcitx5 (Arch Linux).
c2fcbf6515c5884437977de46187c16a8cb7bb50 doesn't show the warnings.

**Comment by phoepsilonix** [comment]
The error was avoided by revert the following commit.

a81b563b80ee8be06c3f6527a7c4d1453ae32628
303b05b815a70a82159893b76de965aea4b7e64f
f6f92e98b01e1c0e998779fb77e5f52ddbf2bf9a
34d479b73e3ed10196a488010f43abcdb54bd03a

```
git revert \
a81b563b80ee8be06c3f6527a7c4d1453ae32628 \
303b05b815a70a82159893b76de965aea4b7e64f \
f6f92e98b01e1c0e998779fb77e5f52ddbf2bf9a \
34d479b73e3ed10196a488010f43abcdb54bd03a \
--no-edit
```

**Comment by hiroyuki-komatsu** [comment]
Hi all,
Thank you for the reports and investigations.

34d479b73e3ed10196a488010f43abcdb54bd03a is apparently the problematic change and 0c34a3f6c209a40eb3dfdf2edbef3077fd04e9fe is the fix of the issue.

**Comment by phoepsilonix** [comment]
I have confirmed that the SERVER_BROKEN_MESSAGE issue(34d479b73e3ed10196a488010f43abcdb54bd03a) has been resolved.
Separately, the ibus-engine-mozc.log does not seem to break lines at the end of the sentence.

**Comment by utuhiro78** [comment]
> (https://github.com/google/mozc/commit/0c34a3f6c209a40eb3dfdf2edbef3077fd04e9fe) is the fix of the issue.

It works fine with Fcitx5.
Thanks hiroyuki-komatsu and k0aaa !

**Comment by k0aaa** [comment]
Thank you all for your support!
I have rebuilt mozc on my system with the latest commit.

Now mozc doesn't complain about incompatible engines anymore.

However, when I look at the logs, there is still a message about denied connections. Though it doesn't seem to be causing any imminent problems, as far as I can tell.

The log now looks like the following:

> WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
> W0000 00:00:1709118846.821850    3533 unix_ipc.cc:277] connect failed: 接続を拒否されました
> W0000 00:00:1709118846.821881    3533 unix_ipc.cc:277] connect failed: 接続を拒否されました
> E0000 00:00:1709118846.821883    3533 client.cc:596] Connection failure to session
> W0000 00:00:1709118846.822371    3533 unix_ipc.cc:277] connect failed: 接続を拒否されました
> W0000 00:00:1709118846.822388    3533 unix_ipc.cc:277] connect failed: 接続を拒否されました
> E0000 00:00:1709118846.822391    3533 client.cc:596] Connection failure to session
> WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
> E0000 00:00:1709118846.825445    5033 tiny_storage.cc:131] the file is missing the header.
> E0000 00:00:1709118846.825495    5033 registry.cc:73] cannot open registry
> I2024-02-28 12:14:07.036449 addonmanager.cpp:195] Loaded addon mozc

So apparently the IPC connection is a separate issue from the incompatibility message one.

**Comment by hiroyuki-komatsu** [comment]
Thank you all for the confirmations.

phoepsilonix, would you create an issue? It'd be great if some actual output is attached.

k0aaa, would you confirm if Ibus-mozc has the same issue or not?

**Comment by hiroyuki-komatsu** [comment]
> phoepsilonix, would you create an issue? It'd be great if some actual output is attached.

29672c60b2d316f57835ce95e5d8d8023f0d149e fixed the line break issue.

**Comment by k0aaa** [comment]
> k0aaa, would you confirm if Ibus-mozc has the same issue or not?

The incompatible engine issue seems to be already resolved as aforementioned.
As for the IPC connection denied message, there aren't any side-effects other than that error message in the fcitx5 logs, and I might need some help as I can't locate any ibus logs. (It doesn't seem to log to journalctl as verbosely as fcitx5 does, if it does log thereto at all.) 

Side by side, I wonder if we should close the issue for now, as it doesn't appear to be very much significant at this point.

**Comment by yukawa** [comment]
> Side by side, I wonder if we should close the issue for now, as it doesn't appear to be very much significant at this point.

+1 to close this for now. Regarding changes in logs, we recently switched (c77285efa096e6e400cacffbcded980d24c5b17f) from Mozc's  house-made [glog](https://github.com/google/glog) clone to Abseil's logging library. It might have changed what's actually logged to the file, even though the actual behavior itself remained the same.
