### ISSUE TITLE
誤変換: レベルのさでひどいことにnaru

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#89]
```
れべるのさでひどいことになる =>
レベルのさでひどいことにnaru
Mozc-1.1.758.102

It should be "レベルの差でひどいことになる".

わざのうまさにおどろいた =>
技の旨さに驚いた

"上手さ".
```

Original issue reported on code.google.com by `heathros...@gmail.com` on 5 Jul 2011 at 9:32

**Comment by hiroyuki-komatsu** [comment]
Added evaluation test cases in this issue.

* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv
