### ISSUE TITLE
Typing issue: 半透明

### ISSUE THREAD

**Issue by tokyo4j** [google/mozc#899]
## Category of the typing issue

1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

## Issues

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| はんとうめい | 半透明 | |

## Version or commit-id

Mozc-2.26.4632.102+24.10.oss

**Comment by siketyan** [comment]
Seems your Mozc is too outdated. Confirmed on Mozc-2.29.5374.101+24.11.oss

<img width="268" alt="image" src="https://github.com/google/mozc/assets/12772118/b665ab4c-a9c2-447b-ab63-772984034cd4">

**Comment by tokyo4j** [comment]
Alright. Thank you for reply!
