### ISSUE TITLE
macos: mozc_emacs_helper dosen't work

### ISSUE THREAD

**Issue by jhorology** [google/mozc#900]
```
$ mozc_emacs_helper --suppress_stderr
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1710812261.693371  912367 system_util.cc:328] ALREADY_EXISTS: mkdir failed: File exists
((mozc-emacs-helper . t)(version . "2.29.5400.101")(config . ((preedit-method . roman))))
```
I think should check if folder exists or or remove LOG(ERROR) in here:

https://github.com/google/mozc/blob/d8e5cfe921aa60c54f49b0b8d9d07575e886628c/src/base/system_util.cc#L326-L330

**Comment by hiroyuki-komatsu** [comment]
Hi jhorology,
Sorry for our late response.

We have confirmed this issue, and begun investigating solutions for it.
Thank you for your report.

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/68e99df9805875b1a5b9906652aa967678ac59bf is the fix against this issue.

Please let us know if this works on your environment.
Thank you,

**Comment by jhorology** [comment]
I confirmed that it's works fine, thank you.
```sh
MOZC_QT_PATH="$(pwd)/third_party/qt" bazel build --verbose_failures \
            --config oss_macos --compilation_mode opt \
            package //unix/emacs:mozc_emacs_helper
```
``` sh
mozc_emacs_helper --suppress_stderr
((mozc-emacs-helper . t)(version . "2.30.5448.101")(config . ((preedit-method . roman))))
```
