### ISSUE TITLE
Typing issue: 戻り値 is missing even though less commoner similar word 返り値 has been registered

### ISSUE THREAD

**Issue by tats-u** [google/mozc#917]
## Category of the typing issue
Choose one of them (delete rest of them)
1. Out-of-vocabulary

## Issues
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| もどりち | <u>戻り値</u> | <u>戻り</u> <u>地</u> |
| かえりち | <u>返り値</u> | <u>返り値</u> |

## Version or commit-id
[e.g. Mozc-2.28.4960.100+24.11.oss or d50a8b9ae28c4fba265f734b38bc5ae392fe4d25]
You can get the version string by converting "Version" or "ばーじょん".

Google Japanese Input Dev (GoogleJapaneseInput-2.29.5374.100+24.11.9), but I have confirmed that “返り値” has been registered even in a build artifact of the plain Mozc using Windows Sandbox

## Additional context

“戻り値” has been registered in the MS IME.

![image](https://github.com/google/mozc/assets/12870451/e8a2ed8f-9427-4727-8ddb-502609c89559)

“返り値” has been registered at line 84154 in https://github.com/google/mozc/blob/master/src/data/dictionary_oss/dictionary08.txt.

The reason why “戻り値” is commoner:

https://qiita.com/paul_soundprj/items/ffb34b28cceec7f1577b (Japanese)

![image](https://github.com/google/mozc/assets/12870451/34d8e7b6-5496-43c7-b61d-cf166f1f6b9a)

![image](https://github.com/google/mozc/assets/12870451/4e5839e3-8bfd-40d5-85b8-7cd23c2838ff)

![image](https://github.com/google/mozc/assets/12870451/1eafe412-3f36-47da-952a-04af1880e923)

![image](https://github.com/google/mozc/assets/12870451/0b5df8c9-ed8e-4918-aeef-5c7fbd84f8b1)

![image](https://github.com/google/mozc/assets/12870451/bbff7d27-e6af-439b-8028-23cabb467773)

**Comment by hiroyuki-komatsu** [comment]
Thank you for your report.
3c10b49fcf43db32f578acb49a45cfb4fe5e1cff has added the word.

FYI. [aux_dictionary.tsv](src/data/oss/aux_dictionary.tsv) is the file for manually adding words.

**Comment by tats-u** [comment]
> aux_dictionary.tsv 

I see. Now I can send a PR.
