### ISSUE TITLE
Typing issue: 𩸽 (ほっけ)

### ISSUE THREAD

**Issue by tats-u** [google/mozc#918]
## Category of the typing issue
Choose one of them (delete rest of them)
1. Out-of-vocabulary

## Issues
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| ほっけ | 𩸽 | ほっけ,ホッケ,法華,法花,法身 |

## Version or commit-id
[e.g. Mozc-2.28.4960.100+24.11.oss or d50a8b9ae28c4fba265f734b38bc5ae392fe4d25]
You can get the version string by converting "Version" or "ばーじょん".

GoogleJapaneseInput-2.29.5374.100+24.11.9

## Additional context

Commonly used as test cases for kanjis out of BMP:

**𠮷**野家で **𩸽**頼んで **𠮟**られる

```
rg "^ほっけ\t"
dictionary_oss\dictionary08.txt
1377:ほっけ     1847    1847    6174    ほっけ
69370:ほっけ    1919    1919    7208    法花
69371:ほっけ    1919    1919    7163    法身

dictionary_oss\dictionary07.txt
3164:ほっけ     1847    1847    5896    ホッケ
3165:ほっけ     1920    1920    7691    法花
3166:ほっけ     1847    1847    6479    法華
3167:ほっけ     1919    1919    5375    法華
3168:ほっけ     1920    1920    6581    法華
```

**Comment by tats-u** [comment]
I downloaded an installer from https://github.com/google/mozc/actions/runs/9058758344 and installed it in Windows Sandbox, but  𩸽 didn't appear...

![image](https://github.com/google/mozc/assets/12870451/6e2902ba-c2d7-4696-9a87-1ec875d7fc5d)
![image](https://github.com/google/mozc/assets/12870451/3a745714-e63d-4bfb-8e38-6568c768aa64)

**Comment by hiroyuki-komatsu** [comment]
In short, 

aux_dictionary.txt

**Comment by tats-u** [comment]
I see. I'll give up for that.
