### ISSUE TITLE
誤変換: 「言ってる」の候補が存在しない

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#92]
```
バージョン: Mozc-1.1.773.102

「いってる」を変換すると
「言ってる」という候補がありません

「りょうほう」を変換すると
「療法」が第一候補になります
(「両方」ではなく)
```

Original issue reported on code.google.com by `heathros...@gmail.com` on 2 Aug 2011 at 5:13

**Comment by hiroyuki-komatsu** [comment]
Added evaluation test cases in this issue.

* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv
