### ISSUE TITLE
Cannot find the POS for: 動詞,自立,*,*,ラ変,未然形,*

### ISSUE THREAD

**Issue by utuhiro78** [google/mozc#920]
## Description
I tried to build 3c10b49fcf43db32f578acb49a45cfb4fe5e1cff. It shows the warnings:

```
INFO: From Executing genrule //data_manager/oss:mozc_dataset_for_oss@user_pos:
WARNING:root:Cannot find the POS for: 動詞,自立,*,*,ラ変,未然形,*
WARNING:root:Cannot find the POS for: 動詞,自立,*,*,ラ変,体言接続,*
WARNING:root:Cannot find the POS for: 動詞,自立,*,*,ラ変,仮定形,*
WARNING:root:Cannot find the POS for: 動詞,自立,*,*,ラ変,命令ｅ,*
```

## Steps to reproduce
1. bazel build package --config oss_linux -c opt

## Environment
 - OS: Arch Linux

Thank you for updating the OSS dictionary!

**Comment by hiroyuki-komatsu** [comment]
Hi utuhiro78,

I have confirmed that the new dictionary or [id.def](https://github.com/google/mozc/blob/master/src/data/dictionary_oss/id.def) doesn't contain those ラ変 forms.

I've begun investigating solutions to address the warnings.
Please let us know if you also encountered actual issues beyond the build warnings.

Thank you!

**Comment by utuhiro78** [comment]
Maybe [src/data/test/dictionary](https://github.com/google/mozc/tree/master/src/data/test/dictionary) is not compatible with the latest OSS dictionary.
The [id.def](https://github.com/google/mozc/blob/master/src/data/test/dictionary/id.def) includes "ラ変,未然形,*" entries.

**Comment by hiroyuki-komatsu** [comment]
Thank you for the confirmation.

We have updated the dictionary generation logic to keep ラ変 entries.
The future dictionaries will contain the full ラ変 entries again.

Best,
