### ISSUE TITLE
Coding mistake of FilterNoisyNumberCandidate

### ISSUE THREAD

**Issue by benesult** [google/mozc#922]
## Description
In FilterNoisyNumberCandidate of "candidate_filter_test.cc", it seems that previous variables are used by human error.
The fixed file is attached.
Note that unit test "converter:candidate_filter_test" is passed before this fixing. It is also passed after this fixing.

Please confirm it.

## Difference of files

![candidate_filter_test_cc](https://github.com/google/mozc/assets/156664272/edcb0348-f168-4f69-9e7e-a7e3b9b70d06)

## Version or commit-id
a1121b34cf38d1a4537effbd13b44c9dae57fec9

## Fixed file
[candidate_filter_test_cc.zip](https://github.com/google/mozc/files/15090776/candidate_filter_test_cc.zip)

**Comment by hiroyuki-komatsu** [comment]
Hi benesult,
Thank you for your report.

fcbd2d3 fixed this mistake.

Best,
