### ISSUE TITLE
Typing issue: ☗ / ☖ should be able to be converted from "せんて" / "ごて"  | Add reversed shogi pieces U+26C9/U+26CA

### ISSUE THREAD

**Issue by tats-u** [google/mozc#929]
## Category of the typing issue
Choose one of them (delete rest of them)
1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

## Issues
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| せんて | ☗,先手,... | 先手,... |
| ごて | ☖,後手,... | 後手,... |
| 先手 | ☗ | (no candidate) |
| 後手 | ☖ | (no candidate) |
| しょうぎ | ☗,☖,⛊,⛉,将棋,... | ☗,☖,将棋,... |

## Version or commit-id
[e.g. Mozc-2.28.4960.100+24.11.oss or d50a8b9ae28c4fba265f734b38bc5ae392fe4d25]
You can get the version string by converting "Version" or "ばーじょん".

- GoogleJapaneseInput-2.30.5448.100+24.11.9
- Mozc-2.30.5448.100+24.11.oss

## Additional context

https://github.com/google/mozc/blob/6ba364e36378eeb16681950669363e4a140a7332/src/data/symbol/symbol.tsv#L386-L387

May I edit this file?

先手 / 後手: https://ja.wikipedia.org/wiki/%E6%A3%8B%E8%AD%9C#%E5%B0%86%E6%A3%8B%E3%81%AE%E6%A3%8B%E8%AD%9C (Japanese)

**Comment by hiroyuki-komatsu** [comment]
#933 has added those entries. Thank you for the PR.

**Comment by tats-u** [comment]
I forgot to close this in favor of that.
