### ISSUE TITLE
誤変換: 修正されずに板

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#93]
```
バージョン: Mozc-1.1.773.102

しゅうせいされずにいた => 修正されずに板
「修正されずにいた」にならない

```

Original issue reported on code.google.com by `heathros...@gmail.com` on 3 Aug 2011 at 12:13

**Comment by hiroyuki-komatsu** [comment]
Added evaluation test cases in this issue.

* https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
* https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv
