### ISSUE TITLE
The changes of `symbol.tsv` is not applied until cleaning (Windows)

### ISSUE THREAD

**Issue by tats-u** [google/mozc#932]
## Description

I'm trying to modify `src\data\symbol\symbol.tsv`, but its changes are difficult to be reflected because they require us to **clean the build**.

## Steps to reproduce
1. `python build_mozc.py gyp`
2. `python build_mozc.py build -c Release package`
3. Edit `src\data\symbol\symbol.tsv`
4. `python build_mozc.py build -c Release package`
5. Install the generated `Mozc64.msi` & Enable Mozc
6. Try the change

## Expected behavior

The change is applied

## Actual behavior
A clear and concise description of what you actually got.

The change is *not* applied

## Version or commit-id
[e.g. Mozc-2.28.4960.100+24.11.oss or d50a8b9ae28c4fba265f734b38bc5ae392fe4d25]
You can get the version string by converting "Version" or "ばーじょん".

6ba364e36378eeb16681950669363e4a140a7332 (master)

## Environment
 - OS: [e.g. Ubuntu 20.04, macOS 13.1, etc]
 - IMF (for Linux) [e.g. Ibus, Fcitx, etc]
 - Related Applications [e.g. Chromium 109, gedit, etc]

Windows 11 (on Windows Sandbox)
(Notepad)

## Investigations
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + yes, no, N/A
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + yes, no, N/A
 - What applications this issue happens on (e.g. Chromium, gedit).
   + list of applications
 - What applications this issue does not happen on (e.g. Chromium, gedit).
   + list of applications, or not-found
 - (optional) What versions or commit-ids this issue did not happen on
   (e.g. Mozc-2.28.4960.100+24.11.oss).
   + list of versions or commit-ids, or no-investigation.

## Additional context

We have to rebuild after cleaning once (`python build_mozc.py clean`) to apply the changes in `symbol.tsv`.

Solutions:

- Migrate to Bazel completely (#948)
- Fix GYP (will not done by maintainers)

**Comment by hiroyuki-komatsu** [comment]
Hi tats-u,
Thank you for your report.

I guess we might need to modify data_manager/data_manager.gypi or data_manager/oss/oss_data_manager_base.gyp (or other .gyp / .gypi files).

https://github.com/google/mozc/blob/master/src/data_manager/oss/oss_data_manager_base.gyp
https://github.com/google/mozc/blob/master/src/data_manager/data_manager_base.gypi

Since we are migrating the build system from GYP to Bazel (#948), we would not address this limitation.
If you are willing to fix it, we would appreciate it and review your PR.

Best,

**Comment by tats-u** [comment]
@hiroyuki-komatsu Will Mozc64.msi be built by Bazel in the future, won't it?
If so I think I can wait for it.

**Comment by hiroyuki-komatsu** [comment]
Yes, we want to build .msi files with Bazel in the future.

**Comment by tats-u** [comment]
I see.

**Comment by hiroyuki-komatsu** [comment]
We have supported Bazel build for Windows.

Please check the instruction.
https://github.com/google/mozc/blob/master/docs/build_mozc_in_windows.md#build-with-bazel-experimental

I will close this issue in a week if no issues are found.
Thank you,

**Comment by tats-u** [comment]
Even with `[Console]::OutputEncoding = [Console]::InputEncoding = [Text.Encoding]::UTF8` I got:

```
INFO: From Compiling base/win32/hresult.cc:
hresult.cc
ERROR: I:/mozc/src/gui/base/BUILD.bazel:85:12: Executing genrule //gui/base:qrc_tr failed: (Exit -1): bash.exe failed: error executing Genrule command (from target //gui/base:qrc_tr) C:\Users\tatsu\scoop\apps\msys2\current\usr\bin\bash.exe -c ... (remaining 1 argument skipped)
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\Users\tatsu\scoop\apps\msys2\current\usr\bin\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; external/_main~_repo_rules~qt_win/bin/rcc.exe -o bazel-out/x64_windows-opt/bin/gui/base/qrc_tr.cc -name qrc_tr gui/base/tr.qrc"): 指定されたファイルが見つかりません。
 (error: 2)
```

Note: not yet terminated by this error.

I wonder I should remove the stale Java 11.

**Comment by tats-u** [comment]
After removing Java 11 and `git clean -f`, stucked with `Extracting Bazel installation...`.

**Comment by yukawa** [comment]
```
ERROR: I:/mozc/src/gui/base/BUILD.bazel:85:12: Executing genrule //gui/base:qrc_tr failed: (Exit -1): bash.exe failed: error executing Genrule command (from target //gui/base:qrc_tr) C:\Users\tatsu\scoop\apps\msys2\current\usr\bin\bash.exe -c ... (remaining 1 argument skipped)
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\Users\tatsu\scoop\apps\msys2\current\usr\bin\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; external/_main~_repo_rules~qt_win/bin/rcc.exe -o bazel-out/x64_windows-opt/bin/gui/base/qrc_tr.cc -name qrc_tr gui/base/tr.qrc"): 指定されたファイルが見つかりません。
 (error: 2)
```
This error means most likely `bash.exe` is not installed in your system. Check out the following section for details.
 * https://bazel.build/install/windows#bazel_does_not_find_bash_or_bashexe

**Comment by tats-u** [comment]
I see. We should add the link to https://bazel.build/install/windows?hl=ja#install-compilers 
Should Java be 11, not 21? Java 11 is more than 5 years old.

**Comment by yukawa** [comment]
> Should Java be 11, not 21? Java 11 is more than 5 years old.

My understanding is that recent versions of Bazel (or [bazelisk](https://github.com/bazelbuild/bazelisk)) download JRE automatically, so you in general don't need to install Java by yourself.

Note also that we are most likely going to use GitHub Actions as our reference build environment. Setting up an environment similar enough to it may help.
 * https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md

**Comment by tats-u** [comment]
I tried MSYS2 via WinGet but it wasn't be recognized.
I had to reinstall it using Scoop.

However, I confirmed the fix of this issue.
