### ISSUE TITLE
変換候補の説明から「本字」ということばを取り除く

### ISSUE THREAD

**Issue by ghost** [google/mozc#945]
# 概要
変換候補の説明で「本字」ということばを使わないことを提案します。このことばは、辞書によって定義が異なり、混乱の元となるためです。

# 詳しい説明
漢字の字体における「本字」ということばには、2つの定義があります。

- 『説文解字』に掲載されている篆書を楷書化したもの。
  - この定義の採用例:『康煕字典』
  - 具体例: 衞/衛に対する「**䘙**」。普に対する「**暜**」。𠛬に対する「**㓝**/**𠛜**」。
- 戦前の日本で一般的に使われていた字体に対して、『康煕字典』で正字とされている字体。
  - 具体例: 澁に対する「**澀**」。衛に対する「**衞**」。
  
日本の多くの辞書は、この2つの異なる定義を混同した記述をしています。

---
具体例を追記しました

**Comment by shinohara137** [comment]
# 対応策
とりあえず、私から言い換えの案を出しておきます。

- 旧字：戦前の日本で一般的に使われていた字体
- 康煕字典体：康煕字典の字体
- 篆書：説文解字の字体
