### ISSUE TITLE
基本語とかぶるカタカナ語について: 失敗ＳＵＬ

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#96]
```
Mozc-1.1.773.102でカタカナ語辞書を有効にしたまま
「しっぱいする」を変換すると、
４番目あたりの候補から
「失敗ＳＵＬ」「失敗SUL」「しっぱいＳＵＬ」のような
ありえない候補が続出します。

SULのような基本語とかぶるカタカナ語については、
無くてもいいのではないでしょうか。
候補としても、ひょっとしたら辞書そのものにおいても。
```

Original issue reported on code.google.com by `heathros...@gmail.com` on 5 Aug 2011 at 10:15

**Comment by hiroyuki-komatsu** [comment]
If the first conversion is expected and other reasonable conversions are ranked higher than those candidates.
We think this is acceptable behavior.
