### ISSUE TITLE
The icons of `ConfigDialog` and `DictionaryTools` looks jaggy on macOS.

### ISSUE THREAD

**Issue by lazylynx** [google/mozc#964]
## Description

The icons of `ConfigDialog` and `DictionaryTools` looks jaggy on macOS.

## Steps to reproduce
1. Build and install Mozc for macOS.
2. Open launchpad and confirm `ConfigDialog` and `DictionaryTool` s' icons.

## Screenshots

![jaggy](https://github.com/google/mozc/assets/1285728/0ebdeb4b-0540-4600-b96a-302213b59d7b)

## Version or commit-id

Mozc-2.30.5490.101+24.11.oss
But it seems that this behavior continues from older Mozc.

## Environment
 - OS: macOS Sonoma 14.5

## Investigations

This behavior is due to the fact that `src/data/images/mac/product_icon.icns` does not have sufficient resolution images. 
Currently, the file seems to only include a 32x32 pixels image.
Once product_icon.icns contains larger images, this issue will be resolved.

Here is a screenshot showing Mozc built from my working branch with higher resolution images in product_icon.icns( https://github.com/lazylynx/mozc/actions/runs/9681442036 ）. They are created from `src/data/images/icon.svg` with margins modified.

![smooth](https://github.com/google/mozc/assets/1285728/a35fbfe7-6634-4cc4-8af6-fe9891000073)

## Additional context

icns specification is here:
https://en.wikipedia.org/wiki/Apple_Icon_Image_format
https://web.archive.org/web/20180618155438/https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

**Comment by lazylynx** [comment]
If there are no problem,  I'll prepare a PR for replacing the icons.

**Comment by hiroyuki-komatsu** [comment]
Hi lazylynx,

Thank you for your report. Yes, please feel free to send a PR.

Could you please add a note about how to reproduce your PR to the commit log? (i.e. how to create the same product_icon.icns for other people)

Best regards,

**Comment by lazylynx** [comment]
> Could you please add a note about how to reproduce your PR to the commit log? (i.e. how to create the same product_icon.icns for other people)

Yes, off course!
Is it better to include not just the product_icon.icns file, but also the PNG images used to create the .icns file in the PR?
As shown [here](https://gist.github.com/jamieweavis/b4c394607641e1280d447deed5fc85fc), icns files are generated from PNG images with specific sizes and names.

**Comment by hiroyuki-komatsu** [comment]
If the PNG images can be programmatically created from the SVG file, a comment is totally fine.
If you needed to retouch the PNG images by hands, I'd like have the PNG images too.

Thank you,

**Comment by lazylynx** [comment]
Since I've retouched images with Figma, I add all PNG images to the PR.
I'd appreciate if you check the PR.

Thank you.

**Comment by lazylynx** [comment]
@hiroyuki-komatsu `src/data/images/mac/product_icon.icns` seems to be rollbacked since this commit.
https://github.com/google/mozc/commit/183b5e86694ff789b0fc9311550d484c717289e5#diff-478c54cda0463846d2afc61cdaa89800c9d9db902a6008c27369e98fa4729bb1
I'd appreciate it if you could fix it.

**Comment by hiroyuki-komatsu** [comment]
Sorry, I accidentally moved those files. I will fix the file locations.
Thank you for your report!

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/1b7ffbdca0d5e52f201acca42fdb0c1e3da317de fixed the issue.
Thank you,
