### ISSUE TITLE
Typing issue: 礦坑, 砿坑

### ISSUE THREAD

**Issue by fu-creator** [google/mozc#977]
## Category of the typing issue
Choose one of them (delete rest of them)
1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

## Issues
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| こうこう | 礦坑 | (optional, write here) |
| こうこう | 砿坑 | (optional, write here) |

## Version or commit-id
Mozc-2.30.5490.102+24.11.oss

## Additional context

> [!NOTE]
>
> Typing issues will be closed when the entries are added to test cases and
> evaluations.
>
> https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
> https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv

**Comment by tats-u** [comment]
https://www.google.com/search?client=firefox-b-d&q=%E7%A0%BF%E5%9D%91

You should add more context including the difference from "鉱坑".
