### ISSUE TITLE
Typing issue: 合辦

### ISSUE THREAD

**Issue by fu-creator** [google/mozc#979]
## Category of the typing issue
Choose one of them (delete rest of them)
1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

## Issues
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| ごうべん| 合辦 | (optional, write here) |

## Version or commit-id
Mozc-2.30.5490.102+24.11.oss

## Additional context

> [!NOTE]
>
> Typing issues will be closed when the entries are added to test cases and
> evaluations.
>
> https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
> https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv

**Comment by tats-u** [comment]
Old notation of 合弁

**Comment by tats-u** [comment]
今の日本で聯合は聯合ニュース程度しか（普通の人は）使いませんよね？
そういう意味のold notationです

**Comment by tats-u** [comment]
「『合弁』を差し置いてトップ候補として出すべきではない」「<https://github.com/google/mozc/blob/master/src/data/dictionary_oss/aux_dictionary.tsv?plain=1>を編集すべき場合、優先度の設定基準語を『合弁』とすべきで、『合弁』より高い優先度を設定すべきではない」「新規のマイナー語彙ではなくあくまでも『合弁』の別表記（旧表記）」程度です。あしからず。

> 合辦という語は今の日本で登場頻度が低いから変換候補の順位を下げるべき」という主張としてはあまりにも言葉足らずですし

「辦」「聯」ともに常用漢字外ですが？

> 「辮髪」「飛驒国」「石鹼」

「辮髪」「弁髪」は両方とも既に組み込み辞書（dictionary06.txt）内に登録されており、「辮髪」の方がも高い優先度出てきますので、特に文句はありません。IPAに両表記ともに認知されているということです。
そもそも「合弁」だけ関連語句含めて収録されている時点で察するべきです。
![image](https://github.com/user-attachments/assets/fd8b019d-b636-4ad2-8111-977301cf5071)
「驒」「鹼」は新旧以前にUnicode専用です。（「𠮟る」と同じ類）Shift_JIS / JISで登録されておらず使い勝手が悪いのでWindowsやソフトのUnicode対応がさらに進まない限り簡易慣用字体を差し置くべきではありません。Shift_JISは未だにVisual C++やバッチファイルなどの標準文字コードなので根絶までまだ時間がかかります。

**Comment by tats-u** [comment]
「連合」も関連語句数で「聯合」を圧倒しています。
「聯合」はほぼ東アジアの機関しか収録されていません。「連合」は国内、及び東アジア以外含め幅広い機関名を網羅しています。

**Comment by tats-u** [comment]
そもそも「辦」自体がShift_JIS（Windows-31J含む）に収録されていません。
