### ISSUE TITLE
Typing issue: 鶏卵紙

### ISSUE THREAD

**Issue by fu-creator** [google/mozc#991]
## Category of the typing issue
Choose one of them (delete rest of them)
1. Out-of-vocabulary (e.g. "夕日" is not in the candidate list at all).

## Issues
Write issues to the following table. (It's in the markdown format)

| input [e.g.ゆうひ] | expected [e.g. 夕日] | actual [e.g. ユウヒ] |
| ------------ | ------------ | ------------|
| けいらんし | 鶏卵紙 | 鶏卵氏 |

## Version or commit-id
Mozc-2.30.5520.102+24.11.oss

## Additional context

> [!NOTE]
>
> Typing issues will be closed when the entries are added to test cases and
> evaluations.
>
> https://github.com/google/mozc/blob/master/src/data/test/quality_regression_test/oss.tsv
> https://github.com/google/mozc/blob/master/src/data/dictionary_oss/evaluation.tsv

**Comment by hiroyuki-komatsu** [comment]
Hi fu-creator,

Thank you for your feedback!
I will update test cases and evaluations based on this and other your reports.

**Comment by hiroyuki-komatsu** [comment]
https://github.com/google/mozc/commit/f518d3d6be4ebc938a1db0df914d54c34ba86213 updated test cases and evaluations to track the reports.

Thank you,
